### ISSUE TITLE
Column information cannot be retrieved error

### ISSUE THREAD

**Issue by advancedspectrum** [ibmdb/python-ibmdb#611] opened 2021-03-03 01:52 UTC
I get the error above in this post's subject line as I am working on a project: Python application (local on my laptop) calling Db2 (instance hosted on IBM cloud). The create or update commit successfully. It's just that I get the error as a return message and I cannot use it for additional logic. If I run the update or create directly on IBM cloud sql editor, there is no error of course.

My Python code for the database update (but I also get this error on a create in this same table)

from ibm_db import *
from ibm_db import tables
from ibm_db import exec_immediate
from ibm_db import fetch_assoc

def databaseConn(sqlStatement):
    connection = connect('DATABASE=BLUDB;'
                     'HOSTNAME=XXX'
                     'PORT=XXX;'
                     'PROTOCOL=TCPIP;'
                     'UID=XXX;'
                     'PWD=XXX')

    results = fetch_assoc(exec_immediate(connection, sqlStatement))
    status = close(connection)
    return results

//Main program    
sqlStatement = "UPDATE PATIENT_HISTORY SET CANCER="+str(True)+" WHERE PATIENT_ID =649"

sqlResults = databaseConn(sqlStatement)

print (sqlResults)

Here is the table (also note the Foreign key column was constrained to being unique through an ALTER I did later):

CREATE TABLE PATIENT_HISTORY (
PATIENT_HISTORY_ID integer not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), 
HIGH_BLOOD_PRESSURE BOOLEAN ,
HEART_DISEASE BOOLEAN ,
DIABETES BOOLEAN ,
TUBERCOLOSIS BOOLEAN ,
CANCER BOOLEAN ,
ALLERGIES VARCHAR(800) ,
MEDICATIONS VARCHAR(800) ,
SURGERIES VARCHAR(800) ,
SMOKING BOOLEAN ,
COV19_VACCINATED BOOLEAN,
PATIENT_ID  INT not null,
PRIMARY KEY(PATIENT_HISTORY_ID),
FOREIGN KEY (PATIENT_ID)
		REFERENCES JWB03988.PATIENT(PATIENT_ID) 
		ON UPDATE RESTRICT 
		ON DELETE CASCADE
)
ORGANIZE BY ROW;

**Comment by imavo** [comment] 2021-03-03 13:06
If the sqlStatement you supply to exec_immediate() is an `UPDATE` statement, then that will not return a result-set.   But  fetch_assoc()  requires a valid result-set, and when fetch_assoc() does not get a result set then it will throw this exception.   Suggest you change your code to conditionally call fetch_assoc() only when the statement can return a result set.

**Comment by advancedspectrum** [comment] 2021-03-03 14:43
Thank you Imavo. I missed understanding this before using fetch_assoc. I think the sql statement for my UPDATE can also be modified to return the number of rows modified using the GET DIAGNOSTICS command to force a return so that fetch still works.

**Comment by imavo** [comment] 2021-03-03 15:08
`get diagnostics` is a separate statement i.e it is not part of update statement , and additionally this statement `get diagnostics ... row_count` can only be used in a routine context.  

If you replace your update statement by a call to a routine, and if that routine returns a result-set then the fetch_assoc() may  be relevant.  The code you showed previously is incorrect code for a statement that does not return a result-set.

You should close this ticket, because your symptom is the expected behaviour.

**Closed** 2021-03-03 15:11 UTC
