### ISSUE TITLE
Mac M1 Support

### ISSUE THREAD

**Issue by jsiebrand** [ibmdb/python-ibmdb#741] opened 2022-04-04 06:41 UTC
Can we kindly get native Mac M1 support for aarch64?  Using the x64 python is not an option.

This stops Db2 being a source for several projects.

**Comment by amukherjee28** [comment] 2022-04-04 08:06
We have had a similar request before. Please check the update provided in the below similar issue raised.
#739

**Comment by bimalkjha** [comment] 2022-04-04 09:02
Duplicate of issue #739.

**Closed by bimalkjha** 2022-04-04 09:02 UTC
Labels: New OS Support
