### ISSUE TITLE
pip install ibm_db failed 

### ISSUE THREAD

**Issue by kodaliy** [ibmdb/python-ibmdb#458] opened 2020-01-04 16:24 UTC
I am using the python version 3.6. When i try to install ibm_db using pip install it failed with the error as explained in the below screen shot.

I need to access the DB2 which is installed on mainframe. Could you suggest me if this the right module that i need to install.

Will python 3.X versions support accessing the IBM mainframe DB2 access ?.

![pip-install-ibm-db-fail](https://user-images.githubusercontent.com/20738237/71768528-c2257780-2f3c-11ea-8e71-d1c72138c9df.PNG)

**Comment by SabaKauser** [comment] 2020-01-06 02:22
can you try installation in verbose mode and see if more information is dumped. One earlier occurence of this problem was resolved by clearing IBM_DB_HOME env var as per the errors logged to verbose output.

**Comment by kodaliy** [comment] 2020-01-11 09:04
Thank You SabaKauser. I could able to install the ibm_db after clearning the IBM_DB_HOME. 

I am now facing the below error while connecting the DB2 which is on z/OS from windows machine.

I am receiving the following error when i am trying to connect to the DB2 which is on z/OS. 

Traceback (most recent call last):
File “D:/user/Python/Python Examples/DBConnectionExample.py”, line 23, in
ibm_db.connect(‘DATABASE=XXXXX;HOSTNAME=XXXX.XXXX.net;PORT=50000;PROTOCOL=TCPIP;UID=user_id;PWD=pswd;’,”,”)
SystemError: returned NULL without setting an error

**Comment by SabaKauser** [comment] 2020-01-13 02:47
Can you try from a cmd window with admin privileges and see if the problem is gone.

**Comment by SabaKauser** [comment] 2020-01-21 06:11
Hi, are you able to connect?

**Comment by SabaKauser** [comment] 2020-02-03 05:08
hey, are you able to connect now.

**Closed** 2020-02-19 05:13 UTC
