### ISSUE TITLE
Error when installing ibm_db

### ISSUE THREAD

**Issue by CGarcia3** [ibmdb/python-ibmdb#744] opened 2022-04-19 13:34 UTC
### I'm using pip version 22.0.4 and python 3.10.4 and run into an error when installing ibm_db:

ERROR Failed building wheel for ibm_db
Failed to build ibm_db
ERROR Could not build wheels for ibm_db, which is required to install pyproject.toml-based projects

Full error attached.

[Error IBM_DB.txt](https://github.com/ibmdb/python-ibmdb/files/8513378/Error.IBM_DB.txt)

Edit: the error solved itself just by restarting and reinstalling a couple of times.

**Comment by pjiangcoding** [comment] 2022-04-20 22:39
Are you using Mac?  

This might be caused by several different issues.  I tried following based on the error messages that I got during the build, and finally got it resolved.
1,  `brew install pkg-config`, which showed I need to install cairo
2,  `brew install cairo`, which turned to install 
3,  `pip install picairo`, which failed with the following error, 
`"clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12'"`
4,  found "clang" was not the supported version, so I reinstalled MacOS SDK follow this link (https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target)

Things worked afterwards.

**Comment by amukherjee28** [comment] 2022-04-22 07:03
@CGarcia3 

Could you mention the platform in which the installation is failing.

However in case there is error in install due to pyproject.toml file try the following approach

```
To install the package ibm_db it is necessary at first to install the build dependency package - wheel:
pip3 install wheel
Install ibm_db with the pip flag --no-build-isolation:
pip3 install ibm_db --no-build-isolation
```

Let me know if this works for you.

Thanks

**Comment by amukherjee28** [comment] 2022-05-04 07:24
Did the above command help resolving the issue ? Can this issue be closed.

**Comment by CGarcia3** [comment] 2022-05-04 08:25
Didn't try it, the problem was solved by restarting mutiple times and  
trying different versions of pip and python. Ended up working on the  
first set of versions that I tried it on.

**Closed** 2022-05-08 19:02 UTC
