### ISSUE TITLE
Autocommit does not Work with ibm_db.callproc(conn, 'ADMIN_MOVE_TABLE'

### ISSUE THREAD

**Issue by armaanfarhadi-2000** [ibmdb/python-ibmdb#834] opened 2023-03-11 07:45 UTC
- Operating System Name: Linux
- db2level output from clidriver if in use:
```
DB21085I  This instance or install (instance name, where applicable: 
"afarhadi") uses "64" bits and DB2 code release "SQL12010" with level 
identifier "02010110".
Informational tokens are "DB2 v12.1.0.0", "z2212010100", "DYN2212010100AMD64", 
and Fix Pack "0".
Product is installed at "/home/afarhadi/sqllib".
```
- Target Db2 Server Version: 12.1.0.0
- Python Version: python3.6
- ibm_db version:
- For non-Windows, output of below commands:
  uname: Linux
  uname -m: x86_64
- Value of below environment variables if set:
  IBM_DB_HOME: `/home/afarhadi/sqllib`
  PATH: ```/usr/share/Modules/bin:/home/afarhadi/sqllib/java/jdk64/bin:/usr/bin:/opt/kde/bin:/supp/oemtools/linuxamd64/bin:/supp/oemtools/linux/bin:/home/afarhadi/bin:/bin:.:/sbin:/usr/sbin:/supp/tools:/supp/tools/share:/usr/bin/X11:/home/afarhadi/sqllib/int:/usr/local/bin:/opt/fortran/bin:/home/afarhadi/sqllib/int/TOP/bin:/home/afarhadi/sqllib/int/TOP/test/fvt/standalone/tools:/home/afarhadi/sqllib/java/jdk64/bin:/usr/lib/perl5:/supp/tools/bin:/supp/oemtools/lib/perl5/5.8.6:/supp/tools/perllib:/supp/tools/regrtools:/home/afarhadi/sqllib/bin:/home/afarhadi/sqllib/adm:/home/afarhadi/sqllib/misc:/home/afarhadi/sqllib/pd:/home/afarhadi/sqllib/gskit/bin:/home/afarhadi/sqllib/db2tss/bin```
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: `/home/afarhadi/sqllib/lib64:/home/afarhadi/sqllib/lib64/gskit:/home/afarhadi/sqllib/lib32`

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

We have seen a problem with auto-commit and `ibm_db.callproc` when they are run through ibm_db python library; `autocommit=True` does not have any effect on `ibm_db.callproc(conn, 'ADMIN_MOVE_TABLE,` and `ADMIN_MOVE_TABLE` runs in uncommitted mode despite the fact that auto-commit has been set to True. Now, `auto-commit=True` works as expected with `ibm_db.exec_immediate`, and sql statements run by `ibm_db.exec_immediate` are committed automatically. So it seems it is only `ibm_db.callproc` that has this problem with `auto-commit=True`. The other thing we have seen is that explicit commit `ibm_db.commit(conn`) works fine after `ibm_db.callproc(conn, 'ADMIN_MOVE_TABLE'`. Thus, `ibm_db.callproc(conn, 'ADMIN_MOVE_TABLE'` does not have any issue with explicit commit, and the problem is only with autocommit.
Here's an example:
```
commit_option = ibm_db.SQL_AUTOCOMMIT_ON
options = {ibm_db.SQL_ATTR_AUTOCOMMIT: commit_option}
conn = ibm_db.connect(DB, "", "", options)

# Work as expected - committed
ibm_db.exec_immediate(conn, 'create table armaantable (c1 int) organize by row')

# Runs in uncommitted mode
ibm_db.callproc(conn, 'ADMIN_MOVE_TABLE', (schema_name, table_name, table_name_2, 'ALLOW_READ_ACCESS', 'MOVE'))
```

**Comment by imavo** [comment] 2023-03-11 09:30
I believe you may misunderstand how that ADMIN_MOVE_TABLE procedure operates.

Please take a careful read of the following technote, which discusses the transactions involved and whether/where users can influence commit:

https://www.ibm.com/support/pages/can-we-control-commits-different-phases-adminmovetable

**Comment by armaanfarhadi-2000** [comment] 2023-03-11 10:53
> I believe you may misunderstand how that ADMIN_MOVE_TABLE procedure operates.
> 
> Please take a careful read of the following technote, which discusses the transactions involved and whether/where users can influence commit:
> 
> https://www.ibm.com/support/pages/can-we-control-commits-different-phases-adminmovetable

We are running ADMIN_MOVE_TABLE using MOVE option, which according to IBM externals, performs the entire table move (INIT, COPY, REPLAY, and SWAP operations) in one step:
https://www.ibm.com/docs/en/db2/11.5?topic=procedure-admin-move-table-move-tables-online

Having said that, when `ibm_db.callproc(conn, 'ADMIN_MOVE_TABLE'` returns with MOVE option, the whole thing must have been finished, so the expectation is the commit should have happened if auto commit is set to True. However, that is not what we are seeing with the tests. Moreover, we see this problem with autocommit and ADMIN_MOVE_TABLE only on ibm_db python library. I tried `ibm_db.callproc(conn, 'ADMIN_MOVE_TABLE'` with MOVE option using the command line, and auto commit was working fine, there.

**Comment by imavo** [comment] 2023-03-11 19:10
I believe that the line on the db2-doc page "...MOVE: Performs the entire table move (INIT, COPY, REPLAY, and SWAP operations) in one step."  does not mean one unit of work  (one transaction) , instead I believe it refers to a single command issued by the programmer (as distinct from each of the subcommands per phase of work that could be issued separately by the programmer).  

How does your table size relate to available txnlog capacity at the time? The default commit-rate for copy I believe is 1000 rows, although the stored procedure can vary it according to prevailing circumstances.   You can take an event monitor for transactions to observe what is happening for the move of a non trivial table whose size exceeds available txnlog capacity at the time of the move.




Apart from that, best to not compare ibm_db with CLP, because CLP does not use the CLI apis but instead older functions. ibm_db is  a wrapper for CLI and does not use the functions that CLP uses.
Instead, test with the `db2cli` command (it accepts a script written in a certain way, see docs).


One thing to know is that ibm_db will issue a rollback on either ibm_db.close or whenever the destructor for the connection object fires. So any dangling transaction, whatever its origin, will be unconditionally lost. The programmer is also free to use the explicit ibm_db.commit API before closing (or ibm_db.rollback as desired ) to take care of dangling transactions.   But your issue suggests you believe that admin_move_table leaves a dangling transaction. So will need to verify.

Meanwhile I will take a look next week at what is happening under the covers, but I suspect that ibm_db.c simply tells CLI whether or not to autocommit and expects CLI to sort it out from there onwards.

**Comment by armaanfarhadi-2000** [comment] 2023-03-11 23:35
Thanks for the info. To provide more details,, tables are either empty, or there are only few rows in them in our tests; nothing close to 1000 rows. 
I put` while True` in the python script right after `ibm_db.callproc` call. (i.e. the the connection has not been closed or anything like that.) Then, from another terminal, I ran `db2pd -locks showlocks -db bludb`:
```
conn = self.get_connection(auto_commit=True)
ibm_db.callproc(conn, 'ADMIN_MOVE_TABLE',
                                    (schema_name, table_name, table_name_2, 'ALLOW_READ_ACCESS', 'MOVE'))
while True:
     pass
 ```

```
$ db2pd -locks showlocks -db bludb

Database Member 0 -- Database BLUDB -- Active -- Up 0 days 00:02:58 -- Date 2023-03-11-14.49.17.057623

Locks:
Address            TranHdl    Lockname                   Type           Mode Sts Owner      Dur HoldCount  Att        ReleaseFlg rrIID TableNm            SchemaNm 
0x00007F12E7309032 35         03000900080000000000000052 RowLock        ..X  G   35         1   0          0x00200020 0x40000000 0     ADMIN_MOVE_TABLE   SYSTOOLS 	03000900080000000000000052 SQLP_RECORD (obj={3;9}, rid=d(0;0;8), x0800000000000000)
0x00007F12E73090F3 35         010000000100000001000072D6 VarLock        ..S  G   35         1   0          0x00000000 0x40000000 0     N/A                N/A      	010000000100000001000072D6 SQLP_VARIATION (anchor,stmt,env,var={912,1,1,1}, loading = 0, )
0x00007F12E73091A2 35         03000900090000000000000052 RowLock        ..X  G   35         1   0          0x00200020 0x40000000 0     ADMIN_MOVE_TABLE   SYSTOOLS 	03000900090000000000000052 SQLP_RECORD (obj={3;9}, rid=d(0;0;9), x0900000000000000)
0x00007F12E7309263 35         414141414147466BC3901F1EC1 PlanLock       ..S  G   35         1   0          0x00000000 0x40000000 0     N/A                N/A      	414141414147466BC3901F1EC1 SQLP_PLAN ({41414141 6B464741 1E1F90C3}, loading=0)
0x00007F12E7309312 35         03000900000000000000000054 TableLock      .IX  G   35         2   0          0x00202000 0xC0000000 0     ADMIN_MOVE_TABLE   SYSTOOLS 	03000900000000000000000054 SQLP_TABLE (obj={3;9})
```
As you see above, the transaction is holding the locks.
I then ran the following command to see whether or not there is any long-running query, and it did not return anything:
```
db2 "SELECT session_auth_id, application_handle, elapsed_time_sec, activity_state, rows_read, CAST(STMT_TEXT as varchar(5000)) FROM sysibmadm.mon_current_sql ORDER BY elapsed_time_sec DESC"
```

To see what uncommitted transactions there are, I ran the following command:
```
$ db2 "SELECT
> con.application_handle,
> con.application_id,
> con.application_name,
> con.client_pid,
> uow.uow_start_time,
> uow.uow_log_space_used
> FROM
> table(mon_get_connection(cast(null as bigint), -1)) as con,
> table(mon_get_unit_of_work(null, -1)) as uow
> WHERE
> con.application_handle = uow.application_handle and
> uow.uow_log_space_used != 0
> ORDER BY uow.uow_start_time "
```
And the result is:
```
APPLICATION_HANDLE   APPLICATION_ID                                                                                                                   APPLICATION_NAME                                                                                                                 CLIENT_PID           UOW_START_TIME             UOW_LOG_SPACE_USED  
-------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------- -------------------------- --------------------
                 195 *LOCAL.afarhadi.230311224917                                                                                                     python3.6                                                                                                                                       22908 2023-03-11-14.47.19.002852                 1432

  1 record(s) selected.
```
Confirming that there is an uncommitted transaction.

**Comment by imavo** [comment] 2023-03-13 10:13
I don't find any uncommitted work on the table that got moved, but instead on the protocol table.

It seems the final UOW in ADMIN_MOVE_TABLE includes changes to content of the protocol table and returning the result set therefrom, via an open cursor (which takes the locks that you see). CLI cannot commit immediately because that would close the cursor, but the cursor has to stay open to allow the result-set to be consumed.

You can replicate this behaviour with your own simple sproc. You can also replicate the behaviour with CLI (without using python).

See also the detail of expected commit behaviour when using CLI to run sprocs (Table 1 has a row for CLI-client (python ibm_db) autocommit on,  and stored procedure "manual commit"
https://www.ibm.com/docs/en/db2/11.5?topic=cli-commit-behavior

So it looks to me to be working as designed, and not a problem in ibm_db and also not specific to admin_move_table. After consuming a result-set (which gets done by the python script usually), the script should explicitly commit, regardless of the autocommit setting.

**Comment by Earammak** [comment] 2023-05-04 12:44
@armaanfarhadi-2000 Do you expect any update on this? 
Thanks

**Comment by bimalkjha** [comment] 2023-05-24 06:35
Closing the issue as working as designed. Thanks.

**Closed by bimalkjha** 2023-05-24 06:35 UTC
