### ISSUE TITLE
malloc error: pointer being freed was not allocated

### ISSUE THREAD

**Issue by nomy950** [ibmdb/python-ibmdb#774] opened 2022-07-29 14:01 UTC
I am trying to work with ibm_db package but getting below issue in my local as well as anaconda virtual env. I am using macOS Monetery version 12.5.

noumannaseer@noumans-MacBook-Pro lib % python -V
Python 3.7.10

noumannaseer@noumans-MacBook-Pro lib % pip list
Package            Version
------------------ -------
appnope            0.1.3
backcall           0.2.0
click              8.1.3
debugpy            1.6.2
decorator          5.1.1
entrypoints        0.4
Flask              2.1.3
ibm-db             3.1.2
…

Getting this error while trying to execute ,
>>> conn = ibm_db.connect(conn_string,"","")
**Error:**
python(2472,0x201366600) malloc: *** error for object 0x7ffb559e3800: pointer being freed was not allocated python(2472,0x201366600) malloc: *** set a breakpoint in malloc_error_break to debug

I referred the link [issue](https://github.com/ibmdb/python-ibmdb/issues/705) and tried the steps but unable to fix it.
I tried renaming the libstdc++.6.dylib  under site-packages/clidriver/lib but then started getting below error while importing the package.

>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so, 0x0002): Symbol not found: (___cxa_throw_bad_array_new_length)
  Referenced from: '/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib'
  Expected in: '/usr/lib/libstdc++.6.dylib'

**Comment by bimalkjha** [comment] 2022-07-31 15:56
@nomy950 Check this comment for [solution](https://github.com/ibmdb/python-ibmdb/issues/748#issuecomment-1117627801). This issue seems duplicate of issue #748 . Thanks.

**Comment by nomy950** [comment] 2022-08-01 15:24
I tried that before opening this issue. I have that file present,

noumannaseer@noumans-MacBook-Pro 11 %  ls /usr/local/lib/gcc/11/libgcc_s.1.dylib
/usr/local/lib/gcc/11/libgcc_s.1.dylib

I even tried using pyhton2.7 but still didnt work.

**Comment by bimalkjha** [comment] 2022-08-03 08:09
@nomy950 In the shared comment, I clearly mentioned about `/usr/local/lib/gcc/8/libgcc_s.1.dylib` and not `/usr/local/lib/gcc/11/libgcc_s.1.dylib`. Please install homebrew/versions/gcc8. Your system should have `/usr/local/lib/gcc/8/libgcc_s.1.dylib`.
Problem is due the presence of `/usr/lib/libstdc++.6.dylib` in your system. Undo the rename `site-packages/clidriver/lib/libstdc++.6.dylib` and rename file `/usr/lib/libstdc++.6.dylib`. If issue still exist, please share output of below commands:
```
otool -L /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib
otool -L /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libstdc++.6.dylib
ls -l /usr/lib/libstd*
ls /usr/local/lib/gcc/
gcc --version
```
Thanks.

**Comment by bimalkjha** [comment] 2022-08-03 08:14
In the output of `otool -L clidriver/lib/libstdc++.6.dylib`, check which version of `libgcc_s.1.dylib` it want. You need to install gcc of same version to get the pull path of libgcc_s.1.dylib in your system. Then ibm_db should work fine. Thanks.

**Comment by bimalkjha** [comment] 2022-08-03 08:18
If `otool -L clidriver/lib/libstdc++.6.dylib` shows that libstdc++.6.dylib has dependency on `/usr/local/lib/gcc/10/libgcc_s.1.dylib`, then you should have /usr/local/lib/gcc/10/libgcc_s.1.dylib in your system. For that you need to install gcc10 using `brew install homebrew/versions/gcc10` command. Thanks.

**Comment by bimalkjha** [comment] 2022-08-03 08:35
@nomy950 I think renaming `clidriver/lib/libstdc++.6.dylib` and executing `export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/11:$DYLD_LIBRARY_PATH` should also fix your problem. Just check that /usr/local/lib/gcc/11 has both libraries libstdc++.6.dylib libgcc_s.1.dylib. Thanks.

**Comment by nomy950** [comment] 2022-08-03 16:14
> @nomy950 In the shared comment, I clearly mentioned about `/usr/local/lib/gcc/8/libgcc_s.1.dylib` and not `/usr/local/lib/gcc/11/libgcc_s.1.dylib`. Please install homebrew/versions/gcc8. Your system should have `/usr/local/lib/gcc/8/libgcc_s.1.dylib`. Problem is due the presence of `/usr/lib/libstdc++.6.dylib` in your system. Undo the rename `site-packages/clidriver/lib/libstdc++.6.dylib` and rename file `/usr/lib/libstdc++.6.dylib`. If issue still exist, please share output of below commands:
> 
> ```
> otool -L /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib
> otool -L /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libstdc++.6.dylib
> ls -l /usr/lib/libstd*
> ls /usr/local/lib/gcc/
> gcc --version
> ```
> 
> Thanks.

Please check below command results, I deleted gcc@11 and installed 8. But still get the same error.


**noumannaseer@noumans-MacBook-Pro lib % otool -L /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib**

```
/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib:
	libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	@loader_path/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

```

**noumannaseer@noumans-MacBook-Pro lib % otool -L /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libstdc++.6.dylib**

```
/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libstdc++.6.dylib:
	/usr/local/opt/gcc/lib/gcc/10/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.28.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	@loader_path/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

```
**noumannaseer@noumans-MacBook-Pro lib % ls -l /usr/lib/libstd***`
`lrwxr-xr-x  1 root  wheel  21 Jul 14 03:48 /usr/lib/libstdc++.6.dylib -> libstdc++.6.0.9.dylib``

**Note:** Tried to rename libstdc++.6.dylib under /usr/lib/ but getting this error.
```
noumannaseer@noumans-MacBook-Pro lib % mv /usr/lib/libstdc++.6.dylib /usr/lib/libstdc++.7.dylib
mv: rename /usr/lib/libstdc++.6.dylib to /usr/lib/libstdc++.7.dylib: Operation not permitted
noumannaseer@noumans-MacBook-Pro lib % sudo mv /usr/lib/libstdc++.6.dylib /usr/lib/libstdc++.7.dylib
Password:
mv: rename /usr/lib/libstdc++.6.dylib to /usr/lib/libstdc++.7.dylib: Operation not permitted
```

**noumannaseer@noumans-MacBook-Pro lib % ls /usr/local/lib/gcc/**
`8`
**noumannaseer@noumans-MacBook-Pro lib % gcc --version**
```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by bimalkjha** [comment] 2022-08-03 16:22
@nomy950 If you have installed gcc version 8 now, then rename `site-packages/clidriver/lib/libstdc++.6.dylib` and run command `export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/11:$DYLD_LIBRARY_PATH`. Then run python test program.
If still do not see any difference, the install `gcc10` and verify.
Problem is your /usr/lib/libstdc++.6.dylib -> libstdc++.6.0.9.dylib, but /usr/lib/libstdc++.6.0.9.dylib does not exist. Copy site-packages/clidriver/lib/libstdc++.6.dylib as /usr/lib/libstdc++.6.0.9.dylib and verify. Thanks.

**Comment by nomy950** [comment] 2022-08-03 16:40
**With gcc@8**
```
noumannaseer@noumans-MacBook-Pro lib % ls -ltr
total 89192
-rwxr-xr-x   1 noumannaseer  staff   3372520 Jul 28 21:29 libDB2xml4c.58.0.dylib
-rwxr-xr-x   1 noumannaseer  staff   3372520 Jul 28 21:29 libDB2xml4c.58.dylib
-rwxr-xr-x   1 noumannaseer  staff   3372520 Jul 28 21:29 libDB2xml4c.dylib
-rwxr-xr-x   1 noumannaseer  staff  31909864 Jul 28 21:29 libdb2.dylib
-rwxr-xr-x   1 noumannaseer  staff     63536 Jul 28 21:29 libdb2clixml4c.dylib
-rw-r--r--   1 noumannaseer  staff    136376 Jul 28 21:29 libgcc_s.1.dylib
-rwxr-xr-x   1 noumannaseer  staff   3422608 Jul 28 21:29 libstdc++.6.dylib
drwxr-xr-x  17 noumannaseer  staff       544 Jul 28 21:29 icc
noumannaseer@noumans-MacBook-Pro lib % pwd
/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib
noumannaseer@noumans-MacBook-Pro lib % mv libstdc++.6.dylib libstdc++.7.dylib
noumannaseer@noumans-MacBook-Pro lib % export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/8:$DYLD_LIBRARY_PATH
noumannaseer@noumans-MacBook-Pro lib % python
Python 3.7.10 (default, Jul 27 2022, 15:20:21) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so, 0x0002): Symbol not found: (___cxa_throw_bad_array_new_length)
  Referenced from: '/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib'
  Expected in: '/usr/lib/libstdc++.6.dylib'

```

**Uninstalled gcc@8 and installed gcc@10**

```
🍺  /usr/local/Cellar/gcc@10/10.4.0: 1,461 files, 340.8MB
==> Running `brew cleanup gcc@10`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
noumannaseer@noumans-MacBook-Pro lib % ls    
icc			libDB2xml4c.58.dylib	libdb2.dylib		libgcc_s.1.dylib
libDB2xml4c.58.0.dylib	libDB2xml4c.dylib	libdb2clixml4c.dylib	libstdc++.7.dylib
noumannaseer@noumans-MacBook-Pro lib % pwd
/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib
noumannaseer@noumans-MacBook-Pro lib % python
Python 3.7.10 (default, Jul 27 2022, 15:20:21) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so, 0x0002): Symbol not found: (___cxa_throw_bad_array_new_length)
  Referenced from: '/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib'
  Expected in: '/usr/lib/libstdc++.6.dylib'
  
noumannaseer@noumans-MacBook-Pro lib % echo $DYLD_LIBRARY_PATH
/usr/local/lib/gcc/8:/usr/local/lib/gcc/10:

```
I tried to copy /usr/lib/libstdc++.6.dylib to /usr/lib/libstdc++.6.0.9.dylib but getting operation not permitted error.
```

noumannaseer@noumans-MacBook-Pro lib % ls
icc			libDB2xml4c.58.dylib	libdb2.dylib		libgcc_s.1.dylib
libDB2xml4c.58.0.dylib	libDB2xml4c.dylib	libdb2clixml4c.dylib	libstdc++.6.dylib
noumannaseer@noumans-MacBook-Pro lib % cp libstdc++.6.dylib /usr/lib/libstdc++.6.0.9.dylib
cp: /usr/lib/libstdc++.6.0.9.dylib: Operation not permitted
noumannaseer@noumans-MacBook-Pro lib % sudo cp libstdc++.7.dylib /usr/lib/libstdc++.6.0.9.dylib
Password:
cp: /usr/lib/libstdc++.6.0.9.dylib: Operation not permitted

```

Still getting same error.

**Comment by nomy950** [comment] 2022-08-03 16:51
Found out that we cant make any changes under /usr/lib/ as it is being managed by OS. Operation permitted under this directory is valid behavior.

**Comment by bimalkjha** [comment] 2022-08-04 05:49
@nomy950 Copy libstdc++.6.dylib from /usr/local/lib/gcc/10 to site_packages/clidriver/lib. It should work without setting any environment variable. If still see error, copy /usr/local/lib/gcc/10/libgcc_s.1.dylib to clidriver/lib directory. Thanks.

**Comment by nomy950** [comment] 2022-08-04 16:05
> @nomy950 Copy libstdc++.6.dylib from /usr/local/lib/gcc/10 to site_packages/clidriver/lib. It should work without setting any environment variable. If still see error, copy /usr/local/lib/gcc/10/libgcc_s.1.dylib to clidriver/lib directory. Thanks.


Below I have tried copying files as you suggested but unfortunately issue still persists. Below are the commands that i ran before retrying python script.

```

noumannaseer@noumans-MacBook-Pro 10 % cd /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib

noumannaseer@noumans-MacBook-Pro lib % ls
icc			libDB2xml4c.58.dylib	libdb2.dylib		libgcc_s.1.dylib
libDB2xml4c.58.0.dylib	libDB2xml4c.dylib	libdb2clixml4c.dylib	libstdc++.6.dylib

noumannaseer@noumans-MacBook-Pro lib % mv libstdc++.6.dylib libstdc++.8.dylib  

noumannaseer@noumans-MacBook-Pro lib % cp /usr/local/lib/gcc/10/libstdc++.6.dylib /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib

noumannaseer@noumans-MacBook-Pro lib % ls
icc			libDB2xml4c.58.dylib	libdb2.dylib		libgcc_s.1.dylib	libstdc++.8.dylib
libDB2xml4c.58.0.dylib	libDB2xml4c.dylib	libdb2clixml4c.dylib	libstdc++.6.dylib

noumannaseer@noumans-MacBook-Pro lib % python 
Python 3.7.10 (default, Jul 27 2022, 15:20:21) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> conn_string = "DATABASE=<connection-string>"
>>> conn = ibm_db.connect(conn_string,"","")
python(92997,0x10be27600) malloc: *** error for object 0x7ffb4361d080: pointer being freed was not allocated
python(92997,0x10be27600) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python

noumannaseer@noumans-MacBook-Pro lib % pwd
/Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/clidriver/lib
noumannaseer@noumans-MacBook-Pro lib % ls
icc			libDB2xml4c.58.dylib	libdb2.dylib		libgcc_s.1.dylib	libstdc++.8.dylib
libDB2xml4c.58.0.dylib	libDB2xml4c.dylib	libdb2clixml4c.dylib	libstdc++.6.dylib
noumannaseer@noumans-MacBook-Pro lib % mv libgcc_s.1.dylib libgcc_s.8.dylib
noumannaseer@noumans-MacBook-Pro lib % cp /usr/local/lib/gcc/10/libgcc_s.1.dylib .
noumannaseer@noumans-MacBook-Pro lib % python
Python 3.7.10 (default, Jul 27 2022, 15:20:21) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>>  conn_string = "DATABASE=<connection-string>"
>>> conn = ibm_db.connect(conn_string,"","")
python(93040,0x107ba4600) malloc: *** error for object 0x7ffb4361d080: pointer being freed was not allocated
python(93040,0x107ba4600) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python

noumannaseer@noumans-MacBook-Pro lib % echo $DYLD_LIBRARY_PATH
/usr/local/lib/gcc/8:/usr/local/lib/gcc/11:
noumannaseer@noumans-MacBook-Pro lib % cd /usr/local/lib/gcc
noumannaseer@noumans-MacBook-Pro gcc % ls
10
noumannaseer@noumans-MacBook-Pro gcc % export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/10:$DYLD_LIBRARY_PATH
noumannaseer@noumans-MacBook-Pro gcc % echo $DYLD_LIBRARY_PATH                                          
/usr/local/lib/gcc/10:/usr/local/lib/gcc/8:/usr/local/lib/gcc/11:
noumannaseer@noumans-MacBook-Pro gcc % python
Python 3.7.10 (default, Jul 27 2022, 15:20:21) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>>  conn_string = "DATABASE=<connection-string>"
>>> conn = ibm_db.connect(conn_string,"","")
python(93085,0x1124a3600) malloc: *** error for object 0x7ffb4361d080: pointer being freed was not allocated
python(93085,0x1124a3600) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python
```

**Comment by bimalkjha** [comment] 2022-09-07 19:32
@nomy950 Let us look into the issue from start. Uninstall existing ibm_db, then execute below commands and share the complete output:
```
cd /Users/noumannaseer/.pyenv/versions/3.7.10/lib/python3.7/site-packages/
rm -rf clidriver ibm_db*
pip install ibm_db
otool -L ibm_db.cpython-37-darwin.so
otool -L clidriver/lib/libdb2.dylib
echo $DYLD_LIBRARY_PATH
echo $PATH
ls /usr/local/lib/gcc
db2level
```
Thanks.

**Closed** 2022-09-22 12:13 UTC
