### ISSUE TITLE
Py3, missing changes and 2.0.8a vs 2.0.8 issues.

### ISSUE THREAD

**Issue by Raisins** [ibmdb/python-ibmdb#318] opened 2018-05-17 23:56 UTC
Hello, 
I am working on a py3 project trying to connect to db2. Currently if you do a pull from master and build. ibm_db_dbi fails due to python3 syntax issue. 

Looking into it more, and the history I found that releases and code for py3 are missing or exist elsewhere. My working theory is that the relevant changes were wrongfully left out of master. 

https://pypi.org/project/ibm_db/#history
If you do a either a pull from master or a pip install you get verion `2.0.8`
on Dec 13, 2017 there is another version 2.0.8a. This one correctly works with python3

local machine, mac os, python 3, 2.0.8a
```Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> ibm_db_conn = ibm_db.connect('db_name', 'username', 'PaSsWoRd')
>>> import ibm_db_dbi
>>> conn = ibm_db_dbi.Connection(ibm_db_conn)
>>> conn.tables('SYSCAT', '%')
```

vs master build

```
>>> import ibm_db_dbi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mypath/ibm_db_dbi.py", line 442
    except Exception, inst:
```

currently master shows 2.0.8
https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/setup.py
Looking through the history and PRs I was unable to find 8a anywhere in both ibmdb repo or recent prs

Not only that it seems as if some changes for python3 among others where lost at some point.
Missing python3 changes in the ibm_db project:
https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db_dbi.py#L450

Also in the django project:
https://github.com/ibmdb/python-ibmdb/pull/307/commits/c05c72b8e4cf2af09a5b6ff71d5d1cd10346fae5#diff-38a49b640e17fc546f693a3e1ad20154L217
vs
https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db_django/ibm_db_django/base.py#L218

This is from a PR by @hemlatabhatt on March 5th. Looking at the github PR it claims only 2 files were changed, but the commit log shows many other file changes which were never merged to master.
https://github.com/ibmdb/python-ibmdb/pull/307

Most basic example is the `django/__init__.py` version:
https://github.com/ibmdb/python-ibmdb/pull/307/commits/c05c72b8e4cf2af09a5b6ff71d5d1cd10346fae5#diff-c974bc6fe2a07058759b61c5fb9e72c7L1
vs 
https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db_django/ibm_db_django/__init__.py

I am looking for any clarification on these discrepencies and any info on how to successfully build and connect db2 to a python3 project.

**Comment by kadler** [comment] 2018-05-18 20:11
@SabaKauser the problem with 2.0.8a is that Python packaging docs say that a letter after the version number is used for a "pre-release tag" so 2.0.8a is considered a beta/pre-release version of 2.0.8 and will always be considered "older" than 2.0.8. To fix the line, but keep the 2.0.8 version you could have added a "post-release" tag (2.0.8-1 or 2.0.8pl1).

You can read more here: http://setuptools.readthedocs.io/en/latest/setuptools.html#specifying-your-project-s-version

**Comment by Raisins** [comment] 2018-05-18 22:31
There are more differences between 2.0.8 and 2.0.8a than just a test folder rename.

There are several instances of non py3 compliant code in Master branch. For example there is a discrepancy between the file that pip action installs and that same file in Master. The Master version includes basestring which was removed in python3. So therefor it fails to compile with python3 since basestring is no longer supported. Any code with basestring cannot be valid.


You can track my process as follows:

On a fresh pip install of 2.0.8a:
```
root@88c0e9ac4025:/# pip install ibm_db==2.0.8a
Collecting ibm_db==2.0.8a
  Downloading https://files.pythonhosted.org/packages/02/76/2362a41e360596bb544ee0a85192fe26c3291d2fa595876e04f700a8f7a2/ibm_db-2.0.8a.tar.gz (689kB)
    100% |████████████████████████████████| 696kB 2.0MB/s 
Building wheels for collected packages: ibm-db
  Running setup.py bdist_wheel for ibm-db ... done
  Stored in directory: /root/.cache/pip/wheels/c7/3a/b6/99d59eafcde8a221cb5b361968770f0f02ae239819c5a4b951
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-2.0.8a0
root@88c0e9ac4025:/# python
Python 3.6.5 (default, May  5 2018, 03:09:35) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> import ibm_db_dbi
>>> ibm_db_conn = ibm_db_dbi.connect(.......)
```
This works and is able to be imported.


If we then go to the file that the above pip action installed. For me it was:
```
>>> import ibm_db_dbi
>>> ibm_db_dbi.__file__
'/usr/local/lib/python3.6/site-packages/ibm_db_dbi.py'
```
opening it in a editor. See in `ibm_db_dbi.py` around line 423
    
```
if (not isinstance(dsn, str)) | \
       (not isinstance(user, str)) | \
       (not isinstance(password, str)) | \
       (not isinstance(host, str)):
        raise InterfaceError("Arguments should be of type string or unicode")
```
 
Master's version of this code looks like this:
```
if (not isinstance(dsn, basestring)) | \
       (not isinstance(user, basestring)) | \
       (not isinstance(password, basestring)) | \
       (not isinstance(host, basestring)):
        raise InterfaceError("Arguments should be of type string or unicode")
```
https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db_dbi.py#L423


Since basestring is no longer valid, and Master uses basestring, there are missing changes. @SabaKauser your example of the import must not be from master or pip install.  Can you post your version of `ibm_db_dbi.py` so we can confirm its not ahead of master. 

There are clearly missing changes since (as shown above) the code differs between Master and 2.0.8a.  Do these changes exist in another repo? Were they not checked in? Were they lost via bad merge? Why is 2.0.8a different?

(I'll also mention that basestring is just one example of non py3 compliant code, there are more changes as well)

**Comment by kadler** [comment] 2018-05-19 00:31
@Raisins, setup.py detects Python 3 and adds `use_2to3` to the call to `setup()`: https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/setup.py#L244-L245 This will cause `2to3` to be run at build time to convert the code to Python 3 syntax: http://setuptools.readthedocs.io/en/latest/python3.html

I'd rather see the code support both versions directly (perhaps using something like [six](https://pythonhosted.org/six/)), but it does seem to work.

**Comment by Raisins** [comment] 2018-05-19 01:12
Thank for for that clarification. That explains some things.  Sorry for overlooking that. 
Follow up question and example. 
Doing a checkout of master. Running setup.py does not seem to run `2to3` any idea why? 

```
root@7001c44e9f46:/ibm# git clone https://github.com/ibmdb/python-ibmdb.git
Cloning into 'python-ibmdb'...
remote: Counting objects: 2831, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 2831 (delta 9), reused 25 (delta 7), pack-reused 2800
Receiving objects: 100% (2831/2831), 1.26 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1687/1687), done.
Checking connectivity... done.
.....
.....



root@7001c44e9f46:/ibm/python-ibmdb/IBM_DB/ibm_db# python setup.py install 
Detected 64-bit Python
setup.py:220: UserWarning: Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the ibm_db module install
 
running install
running bdist_egg
running egg_info
creating ibm_db.egg-info
writing ibm_db.egg-info/PKG-INFO
writing dependency_links to ibm_db.egg-info/dependency_links.txt
writing top-level names to ibm_db.egg-info/top_level.txt
writing manifest file 'ibm_db.egg-info/SOURCES.txt'
...
...
...
Installed /usr/local/lib/python3.6/site-packages/ibm_db-2.0.8-py3.6-linux-x86_64.egg
Processing dependencies for ibm-db==2.0.8
Finished processing dependencies for ibm-db==2.0.8
```

then while testing it

```
root@7001c44e9f46:/ibm/python-ibmdb/IBM_DB/ibm_db# python 
Python 3.6.5 (default, May  5 2018, 03:09:35) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> import ibm_db_dbi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ibm/python-ibmdb/IBM_DB/ibm_db/ibm_db_dbi.py", line 450
    except Exception, inst:
                    ^
SyntaxError: invalid syntax
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
>>> 
```

**Comment by kadler** [comment] 2018-05-19 02:14
Huh, you got me there. I'm not sure why that's not working, but I can reproduce it here as well.

**Comment by SabaKauser** [comment] 2018-05-19 08:43
I have master cloned on my machine(linuxamd64 is down, tried on PPC 64) and I see  this in ibm_db_dbi.py:

    if (not isinstance(dsn, basestring)) | \
       (not isinstance(user, basestring)) | \
       (not isinstance(password, basestring)) | \
       (not isinstance(host, basestring)):
        raise InterfaceError("Arguments should be of type string or unicode")

I then build and install the driver:
writing build/bdist.linux-ppc64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.ibm_db.cpython-36: module references __file__
__pycache__.testfunctions.cpython-36: module MAY be using inspect.stack
__pycache__.tests.cpython-36: module references __file__
tests.__pycache__.test_000_PrepareDb.cpython-36: module references __file__
tests.__pycache__.test_144_BindParamInsertStmtPARAM_FILE.cpython-36: module references __file__
creating 'dist/ibm_db-2.0.8-py3.6-linux-ppc64.egg' and adding 'build/bdist.linux-ppc64/egg' to it
removing 'build/bdist.linux-ppc64/egg' (and everything under it)
Processing ibm_db-2.0.8-py3.6-linux-ppc64.egg
creating /home/skauser/python_installs/python3.6/lib/python3.6/site-packages/ibm_db-2.0.8-py3.6-linux-ppc64.egg
Extracting ibm_db-2.0.8-py3.6-linux-ppc64.egg to /home/skauser/python_installs/python3.6/lib/python3.6/site-packages
Adding ibm-db 2.0.8 to easy-install.pth file

Installed /home/skauser/python_installs/python3.6/lib/python3.6/site-packages/ibm_db-2.0.8-py3.6-linux-ppc64.egg
Processing dependencies for ibm-db==2.0.8

>>> import ibm_db_dbi
>>> ibm_db_dbi.__file__
'/home/skauser/python_installs/python3.6/lib/python3.6/site-packages/ibm_db-2.0.8-py3.6-linux-ppc64.egg/ibm_db_dbi.py'

and the above file  has this:
    if (not isinstance(dsn, str)) | \
       (not isinstance(user, str)) | \
       (not isinstance(password, str)) | \
       (not isinstance(host, str)):
        raise InterfaceError("Arguments should be of type string or unicode")

basestring replaced by str. 

tried on my windows and I see same result.
C:\Users\skauser\AppData\Local\Programs\Python\Python36>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> import ibm_db_dbi
>>> ibm_db_dbi.__file__
'C:\\Users\\skauser\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\ibm_db-2.0.8-py3.6-win-amd64.egg\\ibm_db_dbi.py'

What exactly do I need to do to reproduce this?

**Comment by shawnzhu** [comment] 2018-08-08 15:12
@SabaKauser I've seen release v2.0.9 (contains fix to this issue) from #332 but not found it from pypi.org yet. May I ask when user can install v2.0.9?

**Comment by SabaKauser** [comment] 2018-08-09 02:32
The binaries would be released to pypi by next week.

Thanks!

**Comment by SabaKauser** [comment] 2018-08-14 05:17
closing. I believe you meant the issue is fixed

**Closed by SabaKauser** 2018-08-14 05:17 UTC

**Comment by tgtimoteo** [comment] 2020-01-29 18:42
Hi @SabaKauser, I'm trying to use the 3.0.1 and I'm having the same issue. I can't import the ibm_db_dbi. I get the message: 

File "c:\users\spe6404\env_aulas_python\lib\site-packages\ibm_db_dbi.py", line 846
    
    ^
SyntaxError: invalid syntax
