### ISSUE TITLE
Crucial Issue When Installing ibm_db on Linux

### ISSUE THREAD

**Issue by ghost** [ibmdb/python-ibmdb#351] opened 2018-10-23 12:30 UTC
Seems like there is some Back End issue when downloading/installing the ibm_db package. Running: `pip install ibm_db` generates this error log:

`Collecting ibm_db==2.0.8 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/f8/6f/5f8186cb31021409235a948be5e29d77761ef92747a101360003747c4105/ibm_db-2.0.8.tar.gz (689kB)
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-90jxmm5n/ibm-db/setup.py", line 170, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-90jxmm5n/ibm-db/`

I have tried upgrading pip and setuptools, but still producing the same issue. Also tried this on other machines running on Linux, producing the same error. 

I am running on Python 3.6.6 and have been running this package on the same environment previously with no problems. Trying out `curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz` returns `500 Internal Server Error`.

**Comment by SabaKauser** [comment] 2018-10-23 12:40
Hello,
This is duplicate of 
https://github.com/ibm-functions/runtime-python/issues/65
#350 
https://github.com/ibmdb/node-ibm_db/issues/470

**Closed** 2018-11-30 04:54 UTC
