### ISSUE TITLE
 SQLNumResultCols failed: [IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201 in IBM_DB and Langchain

### ISSUE THREAD

**Issue by Vikas-beyondkey** [ibmdb/python-ibmdb#908] opened 2024-01-12 14:12 UTC
- Operating System Name: Windows 10
- Python Version: 3.10.0
- ibm_db version: 3.1.4

- following other libraries used in this code.
- IfxAlchemy                1.0.1
- langchain                 0.0.352
- SQLAlchemy                1.4.50
- Code to reproduce the issue
- from langchain.sql_database import SQLDatabase
- db = SQLDatabase.from_uri('db2+ibm_db://USERID:PASS@SERVERNAME:PORT/DBNAME, view_support=True, include_tables=["tblpolicy_fri"])
In the above line, I got the below error: 

Exception has occurred: DatabaseError
•	
(ibm_db_dbi.DatabaseError) ibm_db_dbi::DatabaseError: SQLNumResultCols failed: [IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201 [SQL: SELECT "SYSCAT"."TABLES"."TABNAME" FROM "SYSCAT"."TABLES" WHERE "SYSCAT"."TABLES"."TYPE" = ? AND "SYSCAT"."TABLES"."TABSCHEMA" = ? ORDER BY "SYSCAT"."TABLES"."TABNAME"] [parameters: (b'T', b'INFORMIX')] (Background on this error at: https://sqlalche.me/e/14/4xp6)
Exception: SQLNumResultCols failed: [IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201 During handling of the above exception, another exception occurred: ibm_db_dbi.DatabaseError: ibm_db_dbi::DatabaseError: SQLNumResultCols failed: [IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201 The above exception was the direct cause of the following exception: File "E:\Prod_Master_Code\Production_Report\PR_SQLAgent.py", line 8, in <module> db = SQLDatabase.from_uri('db2+ibm_db://xxxx:xxx@SERVERDB:PORT/DBNAME', view_support=True, include_tables=["policy_fri"]) sqlalchemy.exc.DatabaseError: (ibm_db_dbi.DatabaseError) ibm_db_dbi::DatabaseError: SQLNumResultCols failed: [IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201 [SQL: SELECT "SYSCAT"."TABLES"."TABNAME" FROM "SYSCAT"."TABLES" WHERE "SYSCAT"."TABLES"."TYPE" = ? AND "SYSCAT"."TABLES"."TABSCHEMA" = ? ORDER BY "SYSCAT"."TABLES"."TABNAME"] [parameters: (b'T', b'INFORMIX')] (Background on this error at: https://sqlalche.me/e/14/4xp6)

This issue is in SQLDatabase() for informix database when I use same code for SQLite its working fine. 

I am using the correct details to connect the database when trying to connect and create an engine 
from sqlalchemy import create_engine
engine = create_engine('db2+ibm_db://USERID:PASS@SERVERNAME:PORT/DBNAME') 
this will working fine and create engine. but when I pass that engine in the SQLDatabase() it will give same issue.
db = SQLDatabase(engine, view_support=True, include_tables=["policy_fri"])

**Steps to Reproduce:**

1. from langchain.sql_database import SQLDatabase
2. db = SQLDatabase.from_uri('db2+ibm_db://USERID:PASS@SERVERNAME:PORT/DBNAME, view_support=True, include_tables=["tblpolicy_fri"])

Thanks for your help in advance.

**Comment by imavo** [comment] 2024-01-12 17:41
in your create_engine(), you should not use prefix `db2:` but use instead `informix:` , and the url should be formatted as an informix url.

**Comment by bimalkjha** [comment] 2024-01-15 06:51
@Vikas-beyondkey The SQL is being framed and sent by ibm_db_sa to ibm_db. The `ibm_db_sa` does not support Informix server. Check the documentation, hence the generated SQL is not correct for Informix Server and hence error by ibm_db driver.
The problem is with ibm_db_sa and not ibm_db. Hence, closing it. Thanks.

**Closed by bimalkjha** 2024-01-15 06:51 UTC
