### ISSUE TITLE
how to get more information than SQLCODE and SQLSTATE for an SQL in error?

### ISSUE THREAD

**Issue by hapez** [ibmdb/python-ibmdb#468] opened 2020-01-20 09:39 UTC
hi
like in REXX i hope to get more information than just SQLCODE and SQLSTATE. If i have a big SQL for example the SQLCODE -204 didn't tell which object is wrong. In REXX i have DSNTIAR with the SQLCA to get this but as i read there is no SQLCA. So how can i managa this situation?
thx for answering
hapez

**Comment by SabaKauser** [comment] 2020-01-20 09:47
Hi, we have ibm_db.stmt_errormsg() that returns the error message as well. Is that not helpful in your case? error messages are usually constructed from the same sqlca that is filled with error information and serves the purpose.

**Comment by hapez** [comment] 2020-01-20 09:55
hi
yes it doesn't help

code:
    try:
        results = ibm_db.exec_immediate(db2ID, sqlStmt)
    except:
        print("\nERROR: Unable to execute the SQL statement specified.\n" + ibm_db.stmt_errormsg())

output:
ERROR: Unable to execute the SQL statement specified.
 SQLCODE=-204

Message from IBM Documentation for Db2 V11:
-204 name IS AN UNDEFINED NAME
Explanation
The object that is identified by name is not defined in the Db2 subsystem. This SQLCODE can be generated for any type of Db2 object.

So i cann't see the"name" object

or do i something wrong?

regards
hapez

**Comment by SabaKauser** [comment] 2020-01-22 02:24
Hi,
are you using z/OS database?
I tried to reproduce a -204 error and I can see stmt_errormsg returning full error message.

>>> res=ibm_db.exec_immediate(conn,"select * from notab")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 SQLCODE=-204BM][CLI Driver][DB2] SQL0204N  "TS5968.NOTAB" is an undefined name.  SQLSTATE=42704
>>> ibm_db.stmt_errormsg()
'[IBM][CLI Driver][DB2] SQL0204N  "TS5968.NOTAB" is an undefined name.  SQLSTATE=42704\r SQLCODE=-204'

**Comment by hapez** [comment] 2020-01-22 06:16
thx for answering
yes i'm using a Db2 z/OS. If you don't have access to such a database we can fix this together? Do you need a SQLCA or something like this?
regards
hapez

**Comment by hapez** [comment] 2020-01-22 06:17
PS or maybe a Codepage Problem (our database talks in EBCDIC)

**Comment by SabaKauser** [comment] 2020-01-22 06:38
My reproduction is connecting to Db2 on z/OS and I am using ibm_db.stmt_errormsg().Your example shows ibm_db.stmt_error(). ibm_db.stmt_error() is expected to return only SQLSTATE.

https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbstmt_error

ibm_db.stmt_errormsg() is expected to return additional information.
https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbstmt_errormsg

**Comment by hapez** [comment] 2020-01-22 06:46
hi
no i'm using 
pls read my whole coding above:
-----------------------
code:
try:
results = ibm_db.exec_immediate(db2ID, sqlStmt)
except:
print("\nERROR: Unable to execute the SQL statement specified.\n" + ibm_db.stmt_errormsg())
output:
ERROR: Unable to execute the SQL statement specified.
SQLCODE=-204
-------------------------------
there i'm using ibm_db.stmt_errormsg())

but also (as described) 
-----------------------------------------------------------
plus if i have
print(" SQLSTATE=" + ibm_db.stmt_error())
i get as output
SQLSTATE=42S02
which isn't a SQLSTASTE (ibm_db.stmt_error() in the docu was described as SQLSTATE)
correct ist 42704 | An undefined object or constraint name was detected.
--------------------------
is wrong

regards 
hapez

**Comment by SabaKauser** [comment] 2020-01-22 07:11
Hi, 
Please collect db2 traces and share:
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by hapez** [comment] 2020-01-22 07:37
hi
i have no Db2 Client (or a Db2 LUW instance) installed. So as i understood i have no db2trc command. Or is it installed in the Python ibm_db Folder?
regards hapez

**Comment by hapez** [comment] 2020-01-22 07:40
hi
found it:
C:\Program Files (x86)\Python37-32\Lib\site-packages\clidriver\bin
not adm correct?
regards 
hapez

**Comment by hapez** [comment] 2020-01-22 07:41
on
db2trc on -f trc.dmp
i get
Trace could not allocate the necessary IPC resources.  Please retry
using a smaller buffer size.

**Comment by SabaKauser** [comment] 2020-01-22 08:06
yes. adm is folder non-windows. 
try this:
db2trc on -l 1024M 
<run your application>
db2trc dmp trc.dmp
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli

if you get same problem, try reducing the size to -l option.

**Comment by hapez** [comment] 2020-01-22 08:10
on
db2trc on -l 1024M
get same error
Trace could not allocate the necessary IPC resources.  Please retry
using a smaller buffer size.

**Comment by hapez** [comment] 2020-01-22 08:11
on
db2trc on -l 2M
same error

**Comment by hapez** [comment] 2020-01-23 06:27
any ideas what i could do?

**Comment by SabaKauser** [comment] 2020-01-23 07:51
try adding this to db2dsdriver.cfg's database section:
<parameter name="db2trcStartupSize" value="1024"/>

The cfg example is available here -> https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbconnect

You can add db2trcStartupSize to <database> section like other parameters in example and retry.

**Comment by hapez** [comment] 2020-01-23 08:23
there is no file db2dsdriver.cfg on the c: drive. There is a db2dsdriver.xsd file on the /cfg Folder.
Could you pls give me an example python Code for Windows how the Connection string should be to set the db2trcStartupSize?
I think there are too many differences to anticipate Linux to Windows Python ibm_db.
It would be nice if the SQL error handling works well with Python and Db2 on z/OS

**Comment by SabaKauser** [comment] 2020-01-23 09:08
The keyword cannot be added to connection string. The support is available only through db2dsdriver.cfg.
the cfg can be created under C:\Program Files (x86)\Python37-32\Lib\site-packages\clidriver\cfg. There should be a sample file db2dsdriver.cfg.sample.
or create a new file as follows: copy below contents:
``` xml
<configuration>
   <dsncollection>
      <dsn alias="sampledb" name="sample" host="x.y.z.com" port="50000">
      </dsn>
   </dsncollection>
   <databases>
      <database name="sample" host="x.y.z.com" port="50000">
	  <parameter name="userid" value="username"/>
	  <parameter name="password" value="xxxxxx"/>
          <parameter name="db2trcStartupSize" value="1024"/>
       </database>
   </databases>
</configuration>
```
replace sampledb with the database alias that you would like to use or leave it as it is. replace 'sample' with the actual database name, x.y.z.com with the hostname or ip address of the host machine where db2 resides, 50000 with the Db2 port on z/OS, username with the username for connection and xxxxxx with the password. 

in connection, use this:
conn=ibm_db.connect('dsn=sampledb','','')

**Comment by hapez** [comment] 2020-01-23 12:45
this line:
db2ID=ibm_db.connect('dsn=ds0tdb' , '' , '')
gives this result:
 SQLCODE=-1531
with this cfg:
<configuration>
   <dsncollection>
      <dsn alias="ds0tdb" name="DS0T" host="locds0t.eil.x.de" port="4000">
      </dsn>
   </dsncollection>
   <databases>
      <database name="DS0T" host="locds0t.eil.x.de" port="4000">
	  			<parameter name="userid" value="UUUUU"/>
	  			<parameter name="password" value="PPPPPPPP"/>
          <parameter name="db2trcStartupSize" value="1024"/>
       </database>
   </databases>
</configuration>
where UUUUU is userid from z/OS
and PPPPPPPP is password

**Comment by hapez** [comment] 2020-01-23 12:46
<configuration>
   <dsncollection>
      <dsn alias="ds0tdb" name="DS0T" host="locds0t.eil.x.de" port="4000">
      </dsn>
   </dsncollection>
   <databases>
      <database name="DS0T" host="locds0t.eil.x.de" port="4000">
	  			<parameter name="userid" value="UUUUU"/>
	  			<parameter name="password" value="PPPPPPPP"/>
          <parameter name="db2trcStartupSize" value="1024"/>
       </database>
   </databases>
</configuration>

**Comment by hapez** [comment] 2020-01-23 12:48
configuration>
   dsncollection>
      dsn alias="ds0tdb" name="DS0T" host="locds0t.eil.x.de" port="4000">
      /dsn>
   /dsncollection>
   databases>
      database name="DS0T" host="locds0t.eil.x.de" port="4000">
	  			parameter name="userid" value="UUUUU"/>
	  			parameter name="password" value="PPPPPPPP"/>
          parameter name="db2trcStartupSize" value="1024"/>
       /database>
   /databases>
/configuration>
on every line the first < is missing because otherwise you don't see the data

**Comment by SabaKauser** [comment] 2020-01-24 05:36
can you run "db2cli validate -all" from C:\Program Files (x86)\Python37-32\Lib\site-packages\clidriver\bin and share the output.
Also run python in verbose mode and execute import statement like below and share the output:
python -v
import ibm_db

The clidriver(beneath the ibm_db driver) is unable to see the dsn alias 'ds0tdb' in the db2dsdriver.cfg that belongs to it. I am trying to understand if you have other installation of the clidriver in your system or the path that driver is searching for the cfg file. db2cli validate should help me understand that.
I am trying python 3.7 from windows 10 connecting to z/OS 12 and I can correctly see the error SQL0204N. My suspicion is that the server itself is returning just the sqlstate.

There is another way to enable just CLI traces and **for now this should be sufficient to understand what message is returned by server**:
Create a folder trace under c:\ and  create db2cli.ini file under cfg folder and add below lines, make sure to leave an empty line at the end:

[common]
trace = 1
tracepathname = c:\trace

Run your application and you should see trace file name in format p<pid>t<tid>.cli. Share that file.

You need to make sure that db2cli.ini is picked from the intended location, otherwise trace keyword will not be effective. 
The db2cli.ini file exist under 3 places : 
1. c:\Users
2. C:\ProgramData\IBM\DB2\<DB2copy name>\cfg
3. C:\Program Files (x86)\Python37-32\Lib\site-packages\clidriver\cfg


I am trying python 3.7 from windows 10 connecting to z/OS

**Comment by hapez** [comment] 2020-01-24 06:29
the validate Output:
===============================================================================
Client information for the current copy (copy name: C_PROGRA~2_Python37-32_Lib_site-packages_clidriver):
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v10.5.500.107 (s141128/32-bit)
Client Platform           : NT
Install/Instance Path     : C:\PROGRA~2\Python37-32\Lib\site-packages\clidriver

Common App Data Path      : C:\ProgramData\IBM\DB2\C_PROGRA~2_Python37-32_Lib_site-packages_clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname                                              Version Package Language Installed-Location
-------------------------------------------------------------------------------
C_PROGRA~2_Python37-32_Lib_site-packages_clidriver[C] 10.5.05 CLI     EN       C:\PROGRA~2\Python37-32\Lib\site-packages\clidriver
-------------------------------------------------------------------------------
 CLI: IBM Data Server Driver for ODBC and CLI
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"C:\ProgramData\IBM\DB2\C_PROGRA~2_Python37-32_Lib_site-packages_clidriver\cfg\db2dsdriver.cfg".

===============================================================================
The validation is completed.
===============================================================================

**Comment by hapez** [comment] 2020-01-24 06:31
Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v10.5.500.107 (s141128/32-bit)
Client Platform           : NT
Install/Instance Path     : C:\PROGRA~2\Python37-32\Lib\site-packages\clidriver

Common App Data Path      : C:\ProgramData\IBM\DB2\C_PROGRA~2_Python37-32_Lib_site-packages_clidriver
DB2DSDRIVER_CFG_PATH value: not-set>
db2dsdriver.cfg Path      : Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : not-set>
db2cli.ini Path           : Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : Common App Data Path>\db2diag.log

**Comment by hapez** [comment] 2020-01-24 06:43
[output_import_ibm_db.txt](https://github.com/ibmdb/python-ibmdb/files/4107106/output_import_ibm_db.txt)

**Comment by hapez** [comment] 2020-01-24 06:58
done the thing with the db2cli.ini as described i get no output. I have to change c:\trace into C:\Users\Public\trace because i have no right to make folders on c: . So i have also changed the db2cli.ini and add one blank line and put the db2cli.ini under C:\Program Files (x86)\Python37-32\Lib\site-packages\clidriver\cfg

**Comment by SabaKauser** [comment] 2020-01-24 07:21
ok I see this:
>Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"C:\ProgramData\IBM\DB2\C_PROGRA~2_Python37-32_Lib_site-packages_clidriver\cfg\db2dsdriver.cfg". 

So its searching for db2cli.ini or db2dsdriver.cfg under common appdata path. 
Can you create a cfg folder under the same path, and then copy the db2cli.ini from your site-packages location and retry.

**Comment by hapez** [comment] 2020-01-24 07:48
that also didn't work but i have copied the db2dsdriver.cfg to this folder and can connect to my dsn definition. So probably after here we can start to trace? The db2trc in the ...clidriver/bin folder didn't work  but maybe another command on invoking the db2 connect?

**Comment by SabaKauser** [comment] 2020-01-24 08:35
Ok, good to hear that. 
Move the db2trcstartupsize parameter to global parameter section like below:
```
configuration>
dsncollection>
dsn alias="ds0tdb" name="DS0T" host="locds0t.eil.x.de" port="4000">
/dsn>
/dsncollection>
databases>
database name="DS0T" host="locds0t.eil.x.de" port="4000">
parameter name="userid" value="UUUUU"/>
parameter name="password" value="PPPPPPPP"/>

/database>
/databases>
<parameters>
parameter name="db2trcStartupSize" value="1024"/>
</parameters>
/configuration>
```
don't forget to run db2cli validate -all  to validate if the syntax is correct. Then turn trace on and see if the trace problem is gone. 
If you have added the trace keywords to correct db2cli.ini file, you should see them in *db2cli validate -all* output.

Example:
===============================================================================
db2cli.ini validation for data source name "home":
===============================================================================

[ Keywords used for the connection ]

Keyword                   Value
---------------------------------------------------------------------------
PATCH2                    69
TRACEFLUSH                0
COMMITONEOF               1
**TRACEPATHNAME             c:\trace
TRACE                     1**

If the db2trc problem is not resolved from db2dsdriver.cfg setting, only way is to go with tracing using db2cli.ini.

db2trc needs the shared memory segment allocation and hence the IPC. This is dependent on the OS IPC limits and you might need to check your OS IPC limits. The tracing using db2cli.ini however does not use IPC and should work.

**Comment by hapez** [comment] 2020-01-24 09:36
[db2cli_validate_all.txt](https://github.com/ibmdb/python-ibmdb/files/4107654/db2cli_validate_all.txt)

**Comment by hapez** [comment] 2020-01-24 09:37
it seems that now everything is ready for trace. How do istart now the trace?

**Comment by hapez** [comment] 2020-01-24 09:41
with other words if i start the programm it aborts with -204 but no trace file in the folder C:\Users\Public\trace which you see in the validate statement

**Comment by SabaKauser** [comment] 2020-01-27 04:55
Hi, from the db2cli validate output, db2cli.ini is correctly read. Not sure why would this not generate trace. I wil check more and get back to you.

**Comment by SabaKauser** [comment] 2020-01-28 07:19
Hi,
Please remove extra white space between keywords and value pair in db2cli.ini
e.g:
Trace = 1 
should be
Trace=1

**Comment by hapez** [comment] 2020-01-28 09:48
excellent!!! i get the trace output and in the trace output i can see the correct SQLstate and the correct message - so imho it seems there is something wrong in the Python driver to show the result 
[p12588t12648.cli.txt](https://github.com/ibmdb/python-ibmdb/files/4121695/p12588t12648.cli.txt)

**Comment by SabaKauser** [comment] 2020-01-28 12:11
hmm. 
I am able to see the error message correctly.
Tried from both linux and windows:
>>> stmt=ibm_db.exec_immediate(conn, "SELECT * FROM SYSIBM.SYSTABLESw fetch first 10 rows only with ur")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 SQLCODE=-204BM][CLI Driver][DB2] SQL0204N  "SYSIBM.SYSTABLESW" is an undefined name.  SQLSTATE=42704
>>> ibm_db.stmt_errormsg()
'[IBM][CLI Driver][DB2] SQL0204N  "SYSIBM.SYSTABLESW" is an undefined name.  SQLSTATE=42704\r SQLCODE=-204'

**Comment by hapez** [comment] 2020-01-28 12:20
but there must be an error in the python driver. Question at which point do the driver get the information? At this point should be a trace output what the driver does.
First point could be that you make the same trace as i have done to compare the differences from the trace output.  Do you see in the trace this line:
SQLGetDiagRec( pszSqlState="42S02", pfNativeError=-204, pszErrorMsg="[IBM][CLI Driver][DB2] SQL0204N  "SYSIBM.SYSTABLESW" is an undefined name.  SQLSTATE=42704
the pszSqlState is in my "handle".stmt_error(). So there mustbe something wrong

**Comment by hapez** [comment] 2020-01-29 06:15
whats your idea to solve the Problem? Should i open a CASE on IBM site? Or what would you suggest?

**Comment by SabaKauser** [comment] 2020-01-29 07:58
I am using same client codepage settings as you are using, same driver version i.e 3.0.1 and connecting to z 12. Right now, I am not sure why is the message not reaching application. I remember there was another case where python exception came empty. 
I will need to check the code to see if there is any possibility of the error. I will get back.

**Comment by SabaKauser** [comment] 2020-01-30 14:11
@hapez , I did not get time yet to look into this further.  In the meantime, can you check with other python version and share the behavior you are observing. 
What is the python version that you are using.

**Comment by hapez** [comment] 2020-02-03 07:21
@SabaKauser thats bad. As you see and wrote i'm using 3.7. I will test it with another Version. This means that in our Company we can not use Python witf Db2 z in production. Thats really not a good thing.

**Comment by SabaKauser** [comment] 2020-02-03 07:37
@hapez,  i asked you to check another version just to make sure if things are working fine there and if I get clue on reproducing this by seeing the difference. As I told you earlier, I am trying same setting as yours and unable to reproduce the problem.

**Comment by hapez** [comment] 2020-02-04 08:31
@SabaKauser so i have tried to install ibm_db under Python 3.8 64 Bit - not possible. It seems that there are no DLLs created but i get no Errors on pip install.:
C:\Users\UserID\AppData\Local\Programs\Python\Python38>python -m pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.0.1.tar.gz (642 kB)
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (setup.py) ... done
  Created wheel for ibm-db: filename=ibm_db-3.0.1-cp38-cp38-win_amd64.whl size=23786334 sha256=167e489a0145c99c1d81581ce6698d03256a18d687d0e81289b038b763b26795
  Stored in directory: c:\users\UserID\appdata\local\pip\cache\wheels\35\b6\c3\6582ecbf2da45d44763538407db29e79a7d21438e9782c2d2f
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.0.1

C:\Users\UserID\AppData\Local\Programs\Python\Python38>python -m pip install ibm_db
Requirement already satisfied: ibm_db in c:\users\UserID\appdata\local\programs\python\python38\lib\site-packages (3.0.1)

But i get Errors if  i use Import ibm_db:
Traceback (most recent call last):
  File "hape_function.py", line 12, in <module>
    import ibm_db
ImportError: DLL load failed while importing ibm_db: Das angegebene Modul wurde nicht gefunden.
(in english the choosen module not found)

so here i can get nothing

**Comment by SabaKauser** [comment] 2020-02-04 08:39
As you said, there is no binary for python 3.8 yet and the failure is expected. 
Per code inspection, the only reason I see is if the error message returned by server has new line, it is replaced with a null character. However, from the cli trace file that you shared, I don't see any new line in the message returned by server. 
I will investigate this further.  If you can try with python 3.6, that will be helpful.
FYI, I am not available starting tomorrow and back next monday.

**Comment by SabaKauser** [comment] 2020-02-04 08:44
hey, can which locale are you using?

**Comment by hapez** [comment] 2020-02-04 09:01
my locale is Deutsch(Deutschland) thats i think the correct answer

**Comment by hapez** [comment] 2020-02-04 09:22
under 3.6.6 it worked half (the message is correct but in stmt_error() is not the SQLstate
3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
Connected to DS0T !
ERROR: Unable to execute the SQL statement specified.
 SQLCODE=-204ver][DB2] SQL0204N  "SYSIBM.SYSTABLESW" is an undefined name.  SQLSTATE=42704
 SQLSTATE=42S02

**Comment by hapez** [comment] 2020-02-04 09:46
so here is the summary:
under 3.6.6 and 3.7.4 it worked half (the message is correct but in stmt_error() is not the SQLstate
Python 3.8 ibm_db doesn't install right 
but in PyCharm Community Edition 2019.3 it didn't show the SQLCode Message for 3.7.4 3.6.6
so error in 3.8 should be corrected and PyCharm should also work
did you agree?

**Comment by hapez** [comment] 2020-02-12 11:16
hi @SabaKauser
any news on the error?
regards hapez

**Comment by SabaKauser** [comment] 2020-02-13 03:57
@hapez, ibm_db is not yet built to support python 3.8. 
can you share the python level that you intend to use for your work, I have a probable fix( guess work as I am unable to reproduce problem at my end). I will prepare the dll and you can replace in your env to see if your problem is resolved.

**Comment by hapez** [comment] 2020-02-13 06:35
hi @SabaKauser
thx for your Feedback. I want to use Python 3.7.4 with PyCharm 2019.3.2 in our Company. The stmt_error() never has the SQLState. Did you have in your Environment the stmt_error() with the correct SQLstate? So i will test the dll if you create some for testing. Your hope is that this also works than under PyCharm?
regards hapez

**Comment by SabaKauser** [comment] 2020-02-17 02:52
In my environment, I have the correct sqlstate.
Try the dll and let me know.
[win37.zip](https://github.com/ibmdb/python-ibmdb/files/4211610/win37.zip)

**Comment by hapez** [comment] 2020-02-17 08:06
hi
how should i use the *.pyd file? I didn't found any files like this to replace them. Start with python is also not possible. 
thx for advice

**Comment by SabaKauser** [comment] 2020-02-17 08:22
HI,
Under site packages, you will see ibm_db install directory. Under that, you will have ibm_db python extension module. You can rename according to the name it has in your installation(either plain ibm_db or ibm_db.cp<python version>-win_amd64.

**Comment by hapez** [comment] 2020-02-18 07:07
i didn't have this files i have this one:

**Comment by hapez** [comment] 2020-02-18 07:08
![Unbenannt](https://user-images.githubusercontent.com/60093422/74712102-d2ac5b80-5225-11ea-9598-199c70742668.jpg)

**Comment by SabaKauser** [comment] 2020-02-18 08:31
I have created ibm_db.dll.
please replace and test.

[win37.zip](https://github.com/ibmdb/python-ibmdb/files/4218118/win37.zip)

**Comment by hapez** [comment] 2020-02-18 13:59
got this error:
Traceback (most recent call last):
  File "C:/Users/"user"/PycharmProjects/what/deadlock.py", line 13, in <module>
    import ibm_db
  File "C:\Users\"user"\AppData\Roaming\Python\Python37\site-packages\ibm_db.py", line 10, in <module>
    __bootstrap__()
  File "C:\Users\"user"\AppData\Roaming\Python\Python37\site-packages\ibm_db.py", line 9, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\Program Files (x86)\Python37-64\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: %1 ist keine zulässige Win32-Anwendung.

**Comment by SabaKauser** [comment] 2020-02-19 03:10
oops sorry! I created 64-bit dll. You seem to be using 32-bit one. I will create 32bit dll and share.

**Comment by hapez** [comment] 2020-02-20 08:04
hi
so what exactly should this dll proof? If it is the SQLstate i have get a tip that this is the ODBC SQLstate. Important would be for me that PYCharm did work correct and Python 3.8.
I have changed to the Db2 V11.5 Driver Package but the Errors are the same so it is an Python Driver Problem. If you see my message:
ERROR: Unable to execute the SQL statement specified.
 SQLCODE=-204ver][DB2] SQL0204N  "SYSIBM.SYSTABLESW" ist ein nicht definierter Name.  SQLSTATE=42704
 SQLSTATE=42S02
without PyCharm the message .....-204ver][DB2] SQL0204N  "S.... is also incorrect. I think that it is 
....[Driver][DB2] SQL0204N  "S... and that the -204 is put over the first Bytes of the message.
What do you think about it?
rergards
hapez

**Comment by SabaKauser** [comment] 2020-02-21 08:43
With the dll, I am hoping to get the correct error message printed. 
The sqlstate is as received by ibm_db driver  from the odbc driver. I can see odbc driver is mapping the sqlstate to 42S02.
PyCharm should not make additional difference. I see that error message is overwritten and I will debug this.

**Comment by hapez** [comment] 2020-02-25 06:15
hi
so i'm waiting for the dll in 32Bit and pls take a look at PyCharm. As you wrote it should not make any difference but in fact there is no error message! 
regards 
hapez

**Comment by SabaKauser** [comment] 2020-02-26 08:43
Hi,
here is the 32-bit one.
[win37.zip](https://github.com/ibmdb/python-ibmdb/files/4254358/win37.zip)

The file name is ibm_db.dll

**Comment by hapez** [comment] 2020-02-26 09:54
hi
ist the same as before:

Output from Python without PyCharm:
ERROR: Unable to execute the SQL statement specified.
 SQLCODE=-204ver][DB2] SQL0204N  "SYSIBM.SYSTABLESW" ist ein nicht definierter Name.  SQLSTATE=42704
 SQLSTATE=42S02

Output from Python with PyCharm:
ERROR: Unable to execute the SQL statement specified.
 SQLCODE=-204
 SQLSTATE=42S02

**Comment by SabaKauser** [comment] 2020-02-26 12:53
hmm. Let me spend sometime on this. I have another priority delivery commitment and I will try to debug this when I get time.

**Comment by SabaKauser** [comment] 2020-03-06 07:27
The problem does  seem to happen only on windows. Linux and other platforms can print the error message correctly.
The problem see to be happening here -> https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db.c#L503

I need to inspect memory. more details as I progress.

**Comment by chrisT-Z** [comment] 2020-03-16 10:06
Hi, I just recreated hapez's scenario with python 3.7.6 as well as with PyCharm 2019.3.3 along with ibm-db 3.0.1 under Windows 10. Got the same results, i.e. no error message text with PyCharm. Looks better if I use sqlalchemy with ibm_sa instead. Is there any chance that this issue will be fixed in ibm-db under Windows?
Kind regards
Christoph

**Comment by hapez** [comment] 2020-03-18 06:15
hi
is there any News about the Progress in correcting this issue and porting to 3.8?
regards
hapez

**Comment by zohebhussain** [comment] 2020-12-28 17:20
Do you have any update on this ? I have the same issue.

**Comment by kenjaninja** [comment] 2021-08-03 19:27
I think the problem with `ibm_db.stmt_errormsg()` is the lone carriage return (\r) before the SQLCODE in the returned error message:
>[IBM][CLI Driver][DB2] SQL0204N "TS5968.NOTAB" is an undefined name. SQLSTATE=42704\r SQLCODE=-204

On Windows, the carriage return seems to be eating the error message preceding it. I was able to see the error message by removing it.

**Comment by kenjaninja** [comment] 2021-11-19 01:33
@SabaKauser Hi, any updates? If the carriage return mentioned in my comment above is somehow removed I think this issue can be resolved.

**Comment by amukherjee28** [comment] 2022-01-03 19:19
@kenjaninja @hapez 

After investigating this bug I am able to reproduce some special cases where the SQLSTATE returned as part of the error message is not same as returned by the call ibm_db.stmt_error().

When complete error message is returned using the call ```ibm_db.stmt_errormsg()``` then the whole error message contains three segment :

1. The actual error message in statement explaining the cause/reason of the error.
2. SQLSTATE - corresponds to the cause of the error during some incorrect operations
3. SQLCODE - The error code of the occurance.

Based on all of the above points is error message is displayed when the call for ```ibm_db.stmt_errormsg()``` is made.

However when the call is made using ```ibm_db.stmt_error()``` only the SQLSTATE is displayed for the particular invalid operation.

This value of SQLSTATE could be different from the SQLSTATE shown as part of complete error message.
It a default clidriver behavior to show the ODBC standard SQLSTATE when the call is made.

This behavior is part of the DB2 driver code and its expected to work in the same manner.

Please refer to the below link for ODBC standard SQLSTATE.
https://www.easysoft.com/developer/interfaces/odbc/sqlstate_status_return_codes.html

Also to explain the above occurrence here's a sample output from my repro

```
  python3 error1.py
=> Creating the connection
=> Connected to Server ... SUCCESSFULL
=> Error during CREATE TABLE SYNTAX
=> Error creating Table
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "INNT" is an undefined name.  SQLSTATE=42704 SQLCODE=-204
SQLSTATE : 42704
=> Error creating Table
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "test_tab_error" was found following "create tabl ".  Expected tokens may include:  "<space>".  SQLSTATE=42601 SQLCODE=-104
SQLSTATE : 42601
=> Error creating Table
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0612N  "C1" is a duplicate name.  SQLSTATE=42711 SQLCODE=-612
SQLSTATE : 42711
=> Error creating Table
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0601N  The name of the object to be created is identical to the existing name "NEWTON.TEST_TAB_ERROR" of type "TABLE".  SQLSTATE=42710 SQLCODE=-601
SQLSTATE : 42S01
=> Error Inserting Data
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "AB" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206
SQLSTATE : 42S22
=> Error Inserting Data
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0433N  Value "abcdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" is too long.  SQLSTATE=22001 SQLCODE=-433
SQLSTATE : 22001
=> Error Inserting Data
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0117N  The number of values assigned is not the same as the number of specified or implied columns or variables.  SQLSTATE=42802 SQLCODE=-117
SQLSTATE : 21S01
=> Error Inserting Data
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "value" was found following "into test_tab_error".  Expected tokens may include:  "VALUES".  SQLSTATE=42601 SQLCODE=-104
SQLSTATE : 42601
=> Error Inserting Data
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "C3" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206
SQLSTATE : 42S22
=> Error Fetching Data
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "fro" was found following "select * ".  Expected tokens may include:  "FROM".  SQLSTATE=42601 SQLCODE=-104
SQLSTATE : 42601
```

As seen above there are few cases where the SQL STATE in the error message does not match the SQL STATE returned from the API directly.
This is in par with the ODBC standard SQLSTATE returned by the driver.

**Comment by kenjaninja** [comment] 2022-01-03 22:13
@amukherjee28 
Could you address the issue where `ibm_db.stmt_errormsg()` cannot be printed correctly on Windows & PyCharm when connecting to Db2 for z/OS?

# Reproduction example
## Code
```python
import ibm_db
connection_string = "..."  # Replace with valid connection string targeting Db2 for z/OS
conn = ibm_db.connect(connection_string, '', '')
try:
    stmt = ibm_db.exec_immediate(conn, 'SELECT NULL FROM SYSIBM.SYSDUMMY1')  # Throws -206 SQL error
except Exception as e:
    print(ibm_db.stmt_errormsg())
```
## Output
### Linux
```
[IBM][CLI Driver][DB2] SQL0206N  "NULL" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206
```
Prints error message correctly.
### On Windows
**Outside PyCharm**
```
SQLCODE=-206ver][DB2] SQL0206N  "CURRENT" is not valid in the context where it is used.  SQLSTATE=42703
```
**PyCharm**
```
 SQLCODE=-206
```
Outside of PyCharm, the error message is partially overwritten.
In PyCharm, the whole detailed error message is missing.

## Possible cause/solution
I believe the weird overwriting in the first example and the absence of the detailed error message in the second is due to **an extraneous carriage return** in the returned error message on Windows, as seen in the debugger screenshot below:
![image](https://user-images.githubusercontent.com/12107190/147984989-38875d06-3f64-4873-970a-de3d49dc98fc.png)

On Linux, this carriage return is not present when calling `ibm_db.stmt_errormsg()`:
```
(Pdb) p ibm_db.stmt_errormsg()
'[IBM][CLI Driver][DB2] SQL0206N  "NULL" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206'
```

@SabaKauser seemed to be making progress in figuring out the issue as seen in this [comment](https://github.com/ibmdb/python-ibmdb/issues/468#issuecomment-595637360), but no updates have been made since then.

**Comment by kenjaninja** [comment] 2022-01-24 21:00
Any updates on this? @amukherjee28

**Comment by hapez** [comment] 2022-01-25 06:37
i think everything here is dead. Nothing happens no one is interested in this major bug.
therefor pls to other programmers: if you don't want to waste your lifetime don't do anything with Python on Db2/z because there is no support at all

**Comment by amukherjee28** [comment] 2022-01-25 06:48
@kenjaninja This is a windows only occurrence and we are working on getting it fixed on the python code base to fix the additional character being introduced into the error message.

**Closed** 2022-06-13 09:42 UTC
Labels: bug
