### ISSUE TITLE
Error On Connection related to "IBMLDAPauthclient" 

### ISSUE THREAD

**Issue by dmallory42** [ibmdb/python-ibmdb#378] opened 2019-02-26 16:40 UTC
I have set up a Docker container running DB2 and I am trying to connect to it using the ibm_db library. I can successfully connect to this DB2 instance via other means (specifically, DBeaver) using the same connection string details so I'm hoping to debug why exactly this doesn't work in ibm_db. 

This is a minimal example of the code I am running:

`conn = ibm_db.connect("DATABASE=<db_name>;HOSTNAME=127.0.0.1;PORT=50000;PROTOCOL=TCPIP;UID=<uid>;PWD=<password>;")`

and this is the Exception that gets thrown:

`[IBM][CLI Driver] SQL1366N  A security plug-in "IBMLDAPauthclient" processing error occurred on the client. Reason code = "7". SQLCODE=-1366`

As I said, connecting to this works when I do it through other means using the same connection string so I'm hoping to shed some light to why it doesn't work in ibm_db.

**Comment by SabaKauser** [comment] 2019-02-27 03:03
which other interface worked for you? Can you please provide more detail on it.
For connection error in ibm_db, please collect traces as:
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

Also share the db2diag.log file from clidriver/db2dump folder.

**Comment by dmallory42** [comment] 2019-02-27 13:16
Thanks for your response.

What I meant was, I was able to successfully connect to the docker db2 instance via DBeaver (which is an Eclipse extension allowing you to connect and interact with databases) -- it doesn't do anything special, it just uses the same DB2 JDBC drivers that I believe the ibm_db library also uses. I simply set the host, database name, port, user name and password and it successfully connects -- I just mentioned this to show that the database is reachable (however I cannot connect to it via ibm_db library in Python)

I have provided the logs you requested here: https://we.tl/t-MsUtabCqmt (they were too big to share via a Gist or within this response).

Many thanks

**Comment by SabaKauser** [comment] 2019-03-01 04:29
Hello Daniel,
The traces as I believe are from server and only server side processing is captured in traces. Have you configured LDAP for databases? Because, the library in error is used for LDAP authentication.
ibm_db driver uses ODBC driver underneath.

**Comment by SabaKauser** [comment] 2019-03-01 06:24
Hello Daniel,
I am able to reproduce the same problem as yours. 
The problem seem to arise due to missing IBMLDAPSecurity.ini under sqllib/cfg.
If you intend to use LDAP authentication, you need to configure IBMLDAPSecurity.ini file with necessary information like ldap server, userid, password etc. 
If you  do not intend to use LDAP authentication, kindly unset the CLNT_PW_PLUGIN dbm cfg parameter as:
db2 update dbm cfg using CLNT_PW_PLUGIN NULL

**Comment by dmallory42** [comment] 2019-03-01 14:18
Hello,

Thank you for your responses and your patience.

As you said, I do not want to use LDAP authentication. I have now disabled the CLNT_PW_PLUGIN cfg parameter as you suggested. However this problem persists even after disabling that parameter, which is very confusing. Do you have any other possible ideas I can try?

Thanks again,
Daniel

**Comment by SabaKauser** [comment] 2019-03-04 03:00
Hello,
If CLNT_PW_PLUGIN  is unset, ldap authentication should't take place. To dig further, I really need client side traces where you have unset the dbm cfg parameter. The traces to be turned on before you attempt your connection. 
Please note that, you would need to unset the parameter at client. 

let's try collecting traces only security plugin processing. To do that, execute as below:
db2trc on -Madd SQLEX -f ldap.dmp
<run your connection>
db2trc off
db2trc flw ldap.dmp ldap.flw
db2trc fmt ldap.dmp ldap.fmt
db2trc fmt -c ldap.dmp ldap.fmtc

and share ldap.flw, ldap.fmt and ldap.fmtc. The traces should be small enough to attach here.

**Comment by dmallory42** [comment] 2019-03-04 11:59
Hi again,

I managed to get this working in the end. The only thing I changed was to do a fresh (non-cached) uninstall and install of the ibm_db library via Pip. So:

`pip uninstall ibm_db`
`pip install --no-cache-dir ibm_db`

I'm not sure why exactly this fixed it as I was running version 2.0.9 previously and the version hasn't changed. My theory was that possibly I had an outdated version of the clidriver with a problem, and that forcing the reinstall forced pip to pull down a fresh copy of it.

Thanks for all of your help!

**Comment by SabaKauser** [comment] 2019-03-04 13:15
Unless you set IBM_DB_HOME to a clidriver installation directory, ibm_db is going to pull the driver at same level. 
Another thing to note is that if you have automatic installation of clidriver, you would not be able to execute "update dbm cfg" as its an instance-less client. As you said, you earlier had ibm_db refer to instance-based client that was having some settings pointing to do ldap authentication.

Thanks! closing.

**Closed by SabaKauser** 2019-03-04 13:15 UTC
