### ISSUE TITLE
module 'ibm_db_dbi' has no attribute 'BOOLEAN'

### ISSUE THREAD

**Issue by brittomoses** [ibmdb/python-ibmdb#604] opened 2021-02-12 19:15 UTC
Hi,
I'm trying to install Django in IBM i. On running python manage.py test, getting the error
$ AttributeError: module 'ibm_db_dbi' has no attribute 'BOOLEAN'

ibm-db (3.0.3)
ibm-db-django (1.4.0.0)
Python 3.6.12

**Comment by imavo** [comment] 2021-02-15 12:49
See https://github.com/ibmdb/python-ibmdb-django/issues/58

**Comment by brittomoses** [comment] 2021-02-15 13:33
Thanks, When would the version that supports boolean would be released?

**Comment by dgbarclay** [comment] 2021-02-15 15:32
Experiencing the same issue here, there doesn't seem to be any immediate fix so I'm having to use another service. Annoying.

**Comment by amukherjee28** [comment] 2021-02-15 15:46
@dgbarclay 

We are really sorry for not delivering the fix in the last release.

However I can workout on the fix and provide the code in the github repository.

You can clone the code and install it in order to work with the existing driver.

Once i have made the code changes I will provide you with the complete set of instructions in how to install.

It will be seamless will help you get pass the issue.

Thanks.

**Comment by brittomoses** [comment] 2021-03-09 21:02
Is there any code fix for this?

**Comment by amukherjee28** [comment] 2021-03-11 17:44
We are working to ways to provide the fix.
Please allow me another day and I will be able to provide the fix for the already released version.

Thanks.

**Comment by vmorris** [comment] 2021-03-22 21:05
i just ran into this problem myself.. where's the fix?

**Comment by amukherjee28** [comment] 2021-03-23 06:20
Hi @brittomoses @vmorris @dgbarclay 

The fix for this issue is difficult to deliver without making a release as the issue is seen in django layer and the fix needs to come from ibm_db layer.

So we will make another release of the ibm_db driver with the fix in place by 31st march including multiple fixes.

Thanks.

**Comment by vmorris** [comment] 2021-03-23 11:53
:+1: Thanks for the update @amukherjee28

Is there a link to a related issue in the ibm_db driver?

**Comment by vmorris** [comment] 2021-04-05 14:04
Unfortunately I cannot delay being blocked any longer and will be switching to use postgresql or sqlite.

**Comment by brittomoses** [comment] 2021-04-08 20:19
Is there any update on this?

**Comment by amukherjee28** [comment] 2021-04-09 18:11
New version released with the fix has been released.

Please install the latest version of ibm_db (3.0.4) and try this.

Thanks

**Comment by brittomoses** [comment] 2021-04-13 02:37
@amukherjee28 Thanks, that solved the issue but getting 'ibm_db_django' isn't an available database backend.

**Comment by amukherjee28** [comment] 2021-04-14 06:14
Hi,

With the latest release from ibm_db_django there has been doc update tpo install regex package from pip as well.

pip install regex

This should solve the issue you are facing.

This will resolved from django in the next release.

Thanks.

**Comment by imavo** [comment] 2021-04-16 09:48
At today's date, 16/April/2021, I confirm that the following combination of versions allows django framework to be used by ibm_db_django with IBM Db2 LUW v11.5:

linux x64 (ubuntu)
python 3.8.5
pip 21.0.1
regex 2021.4.4
django 3.1.8
ibm_db 3.0.4
ibm_db_django 1.4.0.0

After configuring the project `settings.py`, The `python manage.py test` and `python manage.py migrate` both complete successfully and without errors or warnings.

**Comment by amukherjee28** [comment] 2021-04-16 09:59
Thanks a lot for the update @imavo.

I am closing this issue.

**Closed by amukherjee28** 2021-04-16 09:59 UTC
