### ISSUE TITLE
ibm_db installation on windows fails using python version 3.11

### ISSUE THREAD

**Issue by selvanchammu** [ibmdb/python-ibmdb#810] opened 2022-11-18 14:19 UTC
![image](https://user-images.githubusercontent.com/84575156/199654546-6bff8ede-593e-47f9-88e4-c52cd5f44ea7.png)

i am gettiing this kind of error please help me

_Originally posted by @deeraj2527 in https://github.com/ibmdb/python-ibmdb/issues/399#issuecomment-1301673044_

**Comment by bimalkjha** [comment] 2022-11-19 17:29
https://user-images.githubusercontent.com/84575156/199654546-6bff8ede-593e-47f9-88e4-c52cd5f44ea7.png

**Comment by bimalkjha** [comment] 2022-11-19 17:36
@selvanchammu Its a duplicate of issue #806 . Please install python 3.10, it would work as support for python 3.11 on windows will be available with next release of ibm_db.
If you still want to use python 3.11 now, then as per error message, you need to download and install Microsoft C++ Build tools for Visual C++ 14.0 and add path of MSBuild.exe into PATH system environment variable. Then install ibm_db.  Thanks.

**Comment by bimalkjha** [comment] 2022-11-25 20:00
@selvanchammu ibm_db version 3.1.4 has fix for this issue. Thanks.

**Closed by bimalkjha** 2022-11-25 20:00 UTC
