### ISSUE TITLE
Version 11.5.7 and Python - Symbol not found: (___cxa_throw_bad_array_new_length)

### ISSUE THREAD

**Issue by mjdavisibm** [ibmdb/python-ibmdb#786] opened 2022-09-01 15:47 UTC
#540 
Wondered where the above issue got to with the latest releases as I am having what looks like the same issue

My environment
Brand new Mac: Monterey 12.5.1
Installed : IBM Data Server Driver Package (DS Driver) V11.5.4 and then used fix central to get version 11.5.7 installed over it. I noticed 11.5.7 was released in Dec 2021, i.e. before @bimalkjha last comment on Jan 3rd in the above issue
Installed to default location : /Applications/dsdriver
Then I executed the following

```
$ export IBM_DB_HOME=/Applications/dsdriver
$ export LD_LIBRARY_PATH=$IBM_DB_HOME/lib
$ pip install --upgrade --force-reinstall ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.3-cp39-cp39-macosx_12_0_x86_64.whl
Installing collected packages: ibm_db
  Attempting uninstall: ibm_db
    Found existing installation: ibm-db 3.1.3
    Uninstalling ibm-db-3.1.3:
      Successfully uninstalled ibm-db-3.1.3
Successfully installed ibm_db-3.1.3
$ python
Python 3.9.13 (main, Aug  9 2022, 06:41:34) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/matt/.pyenv/versions/venv_Storefront/lib/python3.9/site-packages/ibm_db.cpython-39-darwin.so, 0x0002): Symbol not found: (___cxa_throw_bad_array_new_length)
  Referenced from: '/Applications/dsdriver/lib/libdb2.dylib'
  Expected in: '/usr/lib/libstdc++.6.dylib'
>>> 
```
Any thoughts? Do I need to wait for 11.5.8? and if so is that due out soon?

**Comment by bimalkjha** [comment] 2022-09-01 17:40
@mjdavisibm Please share output of `otool -L /Applications/dsdriver/lib/libdb2.dylib` command from terminal. Thanks.

**Comment by mjdavisibm** [comment] 2022-09-01 19:41
```
$ otool -L /Applications/dsdriver/lib/libdb2.dylib
/Applications/dsdriver/lib/libdb2.dylib:
	libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by bimalkjha** [comment] 2022-09-02 07:27
@mjdavisibm Check your system have libraries `/usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib` and `/usr/local/lib/gcc/8/libgcc_s.1.dylib` or not. I think it is missing, hence error. If missing, install it using below commands:
```
$ brew tap homebrew/versions
$ brew install homebrew/versions/gcc8
$ ls /usr/local/lib/gcc/8/libgcc_s.1.dylib
$ export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/8:$DYLD_LIBRARY_PATH
```
Now, check `import ibm_db`. Thanks.

**Comment by mjdavisibm** [comment] 2022-09-06 18:58
Thanks @bimalkjha that seemed to fix the problem. Just for anyone else popping by this issue i did the following

**Comment by wormwd** [comment] 2022-09-06 19:34
I've tried this, and now I'm stuck with a different error:
```
python3(60473,0x204c5d600) malloc: *** error for object 0x7ffb4c4e6080: pointer being freed was not allocated
python3(60473,0x204c5d600) malloc: *** set a breakpoint in malloc_error_break to debug
```

I ran into this same error with the clidriver installed through pip. I got that resolved by renaming `libstdc++.6.dylib` to `libstdc++.7.dylib` as mentioned in #705, presumably letting it fall back to the gcc8 version I had in DYLD_LIBRARY_PATH. The clidriver installed by pip is only 11.5.6, and I need 11.5.7. The dsdriver for mac does not have a copy of libstdc++.6.dylib with it. I've tried every combination of DYLD_LIBRARY_PATH, with GCC 8, 9, 10, 11, and 12, with and without the dsdriver lib directory. Every combination produces the same error. My otool output is:
```
% otool -L /Applications/dsdriver/lib/libdb2.dylib
/Applications/dsdriver/lib/libdb2.dylib:
	libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
This is on an Apple M1 Macbook Pro. All of this is running under Rosetta 2.

**Comment by bimalkjha** [comment] 2022-09-07 19:10
@wormwd Probably `/usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib` in the otool output of libdb2.dylib is causing issue. We need gcc8 only and not other version. If you are using other version of gcc, then corresponding path for libstdc++ and libgcc_s.1.dylib need correction in libdb2.dylib.
If you have `/usr/local/lib/gcc/8/libgcc_s.1.dylib` and `/usr/local/lib/gcc/8/libstdc++.6.dylib` in your system, then running below command from a terminal should fix your problem:
```
cd /Applications/dsdriver/lib/
install_name_tool -change /usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib /usr/local/lib/gcc/8/libstdc++.6.dylib  libdb2.dylib
export DYLD_LIBRARY_PATH=/Applications/dsdriver/lib:/Applications/dsdriver/bin:/usr/local/lib/gcc/8
```
Thanks.

**Comment by wormwd** [comment] 2022-09-08 14:01
That didn't work. I get the same error message:
```
python(17500,0x2013f0600) malloc: *** error for object 0x7ffb4c4e6080: pointer being freed was not allocated
python(17500,0x2013f0600) malloc: *** set a breakpoint in malloc_error_break to debug
```

```
otool -L /Applications/dsdriver/lib/libdb2.dylib
/Applications/dsdriver/lib/libdb2.dylib:
	libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by bimalkjha** [comment] 2022-09-09 10:37
@wormwd Now, everything looks fine. Now, you should uninstall the older ibm_db and reinstall it after setting IBM_DB_HOME env variable to pickup libs from correct location.
Also, check the output of `file /usr/local/lib/gcc/8/libstdc++.6.dylib` and `file /usr/local/lib/gcc/8/libgcc_s.1.dylib`. It should be x86-64 version of libs.
Also, if possible, delete /usr/lib/libstdc++.6.dylib which is a broken symlink and it might be getting picked up causing the issue. Thanks.

**Comment by wormwd** [comment] 2022-09-09 14:25
That didn't work. I reinstalled ibm_db with IBM_DB_HOME and DYLD_LIBRARY_PATH set, and I get the same error.
```
file /usr/local/lib/gcc/8/libstdc++.6.dylib
/usr/local/lib/gcc/8/libstdc++.6.dylib: Mach-O 64-bit dynamically linked shared library x86_64

file /usr/local/lib/gcc/8/libgcc_s.1.dylib
/usr/local/lib/gcc/8/libgcc_s.1.dylib: Mach-O universal binary with 1 architecture: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64Mach-O 64-bit dynamically linked shared library x86_64]
```

`/usr/lib/libstdc++.6.dylib` does seem to be broken, but I can't remove it:
```
file /usr/lib/libstdc++.6.dylib
/usr/lib/libstdc++.6.dylib: broken symbolic link to libstdc++.6.0.9.dylib

ls -alh /usr/lib/libstdc++.6.dylib
lrwxr-xr-x  1 root  wheel    21B Aug 11 02:44 /usr/lib/libstdc++.6.dylib -> libstdc++.6.0.9.dylib

sudo rm /usr/lib/libstdc++.6.dylib
rm: /usr/lib/libstdc++.6.dylib: Operation not permitted
```

**Comment by bimalkjha** [comment] 2022-09-09 14:31
@wormwd After reinstallation of ibm_db, please share the output of `tool -L ibm_db.cpython-39-darwin.so` from your site_packages directory. Library name will differ for different python version. Thanks.

**Comment by wormwd** [comment] 2022-09-09 14:42
```
otool -L ibm_db.cpython-39-darwin.so
ibm_db.cpython-39-darwin.so:
	/Applications/dsdriver/lib/libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

```
gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by bimalkjha** [comment] 2022-09-09 14:47
@wormwd In my system, gcc -v is show below output:
```
$  gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
I have `clidirver/lib/libstdc++.6.dylib`, so not installed any gcc8 and ibm_db is working fine without any issue. Could you please install Developer Toolchains for XCode and check? Thanks.

**Comment by bimalkjha** [comment] 2022-09-09 15:37
@wormwd If clidriver for 11.5.6 is working, then 11.5.7 should also work as you have corrected the libstdc++ path in libdb2.dylib. If you have both v11.5.6 and v11.5.7, just replace with another and verify the difference. If still 11.5.6 works but not 11.5.7, then please zip or tar /Applications/dsdriver and attach here. I'll investigate it. Thanks.

**Comment by wormwd** [comment] 2022-09-09 16:20
I think I have it working now. It appears to be caused by the pyenv python/python3 shim scripts. I'm not sure why yet, but it was always failing when using those. Using the python executable directly from the virtualenv I created does work for both 11.5.6 clidriver installed through pip, and 11.5.7 dsdriver installed manually.

@bimalkjha Thanks for all your help!

**Comment by bimalkjha** [comment] 2022-09-09 19:59
@wormwd I think the DYLD_LIBRARY_PATH may not be effective in the shim script environment. If you can find some way to set DYLD_LIBRARY_PATH to work at global level, it may work.
Anyway glad to know that it is working now in normal python environment. Closing the issue now. Thanks.

**Closed by bimalkjha** 2022-09-09 19:59 UTC
