### ISSUE TITLE
(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: [IBM][CLI Driver] SQL10013N  The specified library "GSKit Error: 207" could not be loaded.  SQLSTATE=42724 SQLCODE=-10013

### ISSUE THREAD

**Issue by j-mon** [ibmdb/python-ibmdb#870] opened 2023-07-18 19:58 UTC
- Operating System Name:
- db2level output from clidriver if in use: 
- Target Db2 Server Version: 
- Python Version: python3.10
- ibm_db version: 3.1.1
- For non-Windows, output of below commands:
  uname: Darwin
  uname -m: arm64
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:
/usr/local/Cellar/gcc/12.2.0/lib/gcc/12:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.11/site-packages/clidriver/lib:/usr/local/Cellar/gcc/12.2.0/lib/gcc/12:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/usr/local/Cellar/gcc/12.2.0/lib/gcc/12:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.11/site-packages/clidriver/lib:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.11/site-packages/clidriver/bin:/usr/local/Cellar/gcc/12.2.0/lib/gcc/12:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/usr/local/Cellar/gcc/12.2.0/lib/gcc/12:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.9/site-packages/clidriver:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver:/usr/local/lib/gcc/8:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/bin:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/lib:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/Users/jeffreymonsalve/mambaforge/envs/cirrus-data-analytics-env/lib/python3.10/site-packages/clidriver/lib:/Users/jeffreymonsalve/Desktop/code/libraries/venv/lib/python3.9/site-packages/clidriver/lib:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

Importing ibm_db works fine in a conda environment for mac arm, however when trying to connect to a database the following error appears: 

**(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: [IBM][CLI Driver] SQL10013N  The specified library "GSKit Error: 207" could not be loaded.  SQLSTATE=42724 SQLCODE=-10013**

**Comment by Earammak** [comment] 2023-07-19 04:18
@j-mon Looks like this issue is similar to https://github.com/ibmdb/python-ibmdb/issues/800.
  Please refer the same. 

Thanks,

**Comment by j-mon** [comment] 2023-07-19 14:32
@Earammak thanks! I ran a find on the root directory and can't find that file. Is it not downloaded through anaconda.

**Comment by j-mon** [comment] 2023-07-19 14:56
@Earammak Is GSKit V8 required for mac?

**Comment by Earammak** [comment] 2023-07-20 03:48
@j-mon If you don't have that file, there might be issue with your connection string. Please verify with your connection string once.

**Comment by j-mon** [comment] 2023-07-20 16:09
The connection string looks fine. Is there anywhere else that i can get support for this? Thanks!

**Comment by j-mon** [comment] 2023-07-20 18:08
Who can we reach out to to raise this issue?

**Comment by Earammak** [comment] 2023-07-21 05:00
@j-mon Can you please share what is the connection string you tried and what is the error message?

**Comment by imavo** [comment] 2023-07-21 14:39
Some suggestions:

(1) Ensure you are running the latest release of python ibm_db (3.1.4). Your question mentions 3.1.1 .
If in doubt, unset IBM_DB_HOME,  `pip uninstall ibm_db`, and `pip install ibm_db` (ensure you get the x64 build) . If IBM_DB_HOME environment is NOT set then this will download the latest clidriver also (it changes often, unrelated to ibm_db).

(2) As you are encrypting the connection (;security=SSL;), GSK8 is required (it contains the crypto algorithms) and the relevant parts of GSK are supplied with clidriver. Always ensure you have the latest clidriver (you can run its `db2level` command to show the exact build of clidriver that you are using, you should show `db2level` output in your question).

(3) Verify your SSL certificate externally to python before trying to make it work with ibm_db.
Your question should specify what kind of certificate you are using (self signed, IBM supplied, other...).
You should also mention which platform of Db2-server you are attempting to connect (z/os, i series, linux/unix/windows/cloud).

If you are using a self-signed certificate, or a non-ibm-supplied certificate, your connection string should additionally have `;sslServerCertfificate=/path/to/certfile;` as well as `;security=SSL;`. The final character in the connection string should be a semi-colon.

For example, if it is not an ibm supplied certificate then you can verify the certificate with a jdbc app, or you can verify the certificate with the `db2cli validate -connect -dsn XXX -user YYY -passwd ZZZ` if you have already previously created/configured your `db2dsdriver.cfg` XML file in your clidriver/cfg directory. (Google for examples of `db2dsdriver.cfg`). If you cannot validate the certificate file externally to python or ibm_db then your job is more difficult. Equally, if you prove the certificate is working with `db2cli` then you will have no problems using it with python ibm_db.



(4) Clean up your PATH, LD_LIBRARY_PATH
It is unwise to have more than one copy of Python or its packages e.g. clidriver/bin and/or clidriver/lib in your PATH or LD_LIBRARY_PATH.  The chances of picking up the wrong version of some executable or library are greatly increased.
Ensure only a single reference to Python and clidriver/bin, clidriver/lib appears on those environment variables, apart from searches taking longer.

**Comment by bimalkjha** [comment] 2023-07-26 04:44
@j-mon The problem seems missing `SSLServerCertfificate=/path/to/certfile.arm;` in connection string. Could you print your connection string just before `db2_engine.connect()` and share here after masking passwd and other values that you want to hide? We want to see what all keywords you are passing in connection string and which one is missing. Thanks.

**Comment by bimalkjha** [comment] 2023-08-21 06:24
@j-mon I hope you are able to identify the root cause and resolve the issue. If still issue is not resolved, please provide the requested info else let us know to close this issue. Thanks.

**Comment by bimalkjha** [comment] 2023-08-23 14:02
No update since a month. Closing due to inactivity. Please update here if issue is not resolved yet. Thanks.

**Closed by bimalkjha** 2023-08-23 14:02 UTC
