### ISSUE TITLE
Multi thread application fails.

### ISSUE THREAD

**Issue by op123singh** [ibmdb/python-ibmdb#622] opened 2021-04-19 17:23 UTC
Hi
I have a multi thread python application which run and inserts specified about of row to Db2 zOS table.
The application works from LUW clients to  Db2 zOS.  But the same application fails when run from zOS USS to Db2 zOS.

Here is the output of the errors :
Starting data generation and insertion...
<ibm_db.IBM_DBConnection object at 0x5008F4FC60>
<ibm_db.IBM_DBConnection object at 0x5008F4FCB0>
<ibm_db.IBM_DBConnection object at 0x5008F594E0>
<ibm_db.IBM_DBConnection object at 0x5008F4FE90>
<ibm_db.IBM_DBConnection object at 0x5008F59260>
<ibm_db.IBM_DBConnection object at 0x5008F592B0>
<ibm_db.IBM_DBConnection object at 0x5008F4FF80>
<ibm_db.IBM_DBConnection object at 0x5008F59300>
<ibm_db.IBM_DBConnection object at 0x5008F59620>
<ibm_db.IBM_DBConnection object at 0x5008AEBB70>
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
    self.run()
  File "main.py", line 77, in run
    self.run()
  File "main.py", line 77, in run
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
    self.run()
  File "main.py", line 77, in run
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
Exception in thread Thread-8:
Traceback (most recent call last):
    self.run()
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
  File "main.py", line 77, in run
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
    self.run()
  File "main.py", line 77, in run
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
    self.run()
  File "main.py", line 77, in run
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/SVT/usr/lpp/python38/pyz/lib/python3.8/threading.py", line 938, in _bootstrap_inner
    self.run()
  File "main.py", line 77, in run
    self.run()
  File "main.py", line 77, in run
    self.run()
  File "main.py", line 77, in run
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
    self.run()
  File "main.py", line 77, in run
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
Exception: SQLRowCount failed: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HY010  ERRLOC=7:14:4 SQLCODE=-99999
(ibm_python_venv) <STLABB5:/u/opsingh/python>

**Comment by op123singh** [comment] 2021-04-19 17:27
I have the application traces for ODBC .. please let me know if that will help.

**Comment by amukherjee28** [comment] 2021-04-19 17:33
Hi @op123singh

It would be really helpful if you can provide a sample code snippet that you are using.
This is help in debugging the issue into both the platforms.

Thanks

**Comment by op123singh** [comment] 2021-04-19 18:06
import threading
import ibm_db
from datetime import datetime, date
import configparser
import random
import string
import os
import logging
import sys

exitFlag = 0


class MyThread(threading.Thread):
    def __init__(self, id, base_thread_name, rows, conn_info, schema_name, table_name):
        threading.Thread.__init__(self)
        self.id = id
        self.base_name = base_thread_name
        self.rows = rows
        self.conn_info = conn_info
        self.schema = schema_name
        self.table = table_name

    # each thread will go through this function and run it all in sequence
    # define external functions outside of "def run", then call them here
    def generate_thread_name(self):
        return

    def run(self):
        logger.debug(f"Starting {self.base_name}")
        logger.debug(f"{self.base_name} is connecting...")
        conn = connect_to_db2(self.conn_info)
        if conn:
            global global_rows_inserted
            logger.info(f"{self.base_name} connected successfully.")
            max_mass_insert_value = 100  # ibm_db can only handle around 100 rows of data at a time
            rows_inserted = 0
            rs, stmt = get_result_set(conn, schema, table)

            # convert resultSet to nested list, for repeat processing
            meta_data_list = convert_result_set_to_nested_list(rs, stmt)

            # create a formatted string of column names out of the meta_data_list
            formatted_column_names = generate_column_name_list(meta_data_list)

            # create a string of question marks to fill in the mass_insert
            mass_insert_format = generate_mass_insert_format(meta_data_list)

            # prepare the insert SQL template
            insertSQL = f"INSERT INTO {self.schema}.{self.table} ({formatted_column_names}) " \
                        f"VALUES({mass_insert_format})"
            logger.debug(f"Prepared insert SQL statement (special query used by ibm_db): {insertSQL}")

            # loop to gen and insert data
            while self.rows > 0:
                if self.rows > max_mass_insert_value:
                    rows_to_generate = max_mass_insert_value
                else:
                    rows_to_generate = self.rows

                # generate a nested list of random data rows
                random_data_list = generate_list_of_random_data_rows(meta_data_list, rows_to_generate)

                # convert to nested tuple
                tuple_random_data_list = tuple(tuple(i) for i in random_data_list)

                stmt_insert = ibm_db.prepare(conn, insertSQL)
                try:
                    # attempt to insert each of the generated rows
                    ibm_db.execute_many(stmt_insert, tuple_random_data_list)
                except Exception as inst:
                    logger.warning(
                        "Warning: Not all of the rows were successfully inserted. "
                        "Updating total count to account for failures.")
                    logger.warning(inst)
                finally:
                    row_count = ibm_db.num_rows(stmt_insert)  # check number of successfully inserted rows
                    self.rows = self.rows - row_count # decrement total rows this thread has to do
                    rows_inserted = rows_inserted + row_count
                    logger.debug(f"{self.base_name} has inserted a total of {rows_inserted} rows.")
                    logger.debug(f"{self.base_name}: Successful inserts this loop: {row_count}, "
                                 f"total inserted since program began: {rows_inserted}\n")
                    with threadLock:
                        global_rows_inserted += row_count
                        logger.info(f"Program has inserted {global_rows_inserted} rows of random data so far.\n")
                        print(f"Program has inserted {global_rows_inserted} rows of random data so far.\n")

            logger.debug(f"{self.base_name} finished.\n")


def read_properties_file():

    config = configparser.ConfigParser()
    try:
        path = '/'.join((os.path.abspath(__file__).replace('\\', '/')).split('/')[:-1])
        config.read(os.path.join(path, 'properties.ini'))
        user_conn_info = config['PROPERTIES']['CONNECTION']
        user_schema = config['PROPERTIES']['SCHEMA']
        user_table = config['PROPERTIES']['TABLE']
        user_row_count = int(config['PROPERTIES']['RECORDS'])
        user_thread_count = int(config['PROPERTIES']['THREADS'])
        user_logging_level = int(config['PROPERTIES']['LOGLEVEL'])
    except configparser.NoSectionError:
        print("ERROR: Could not find section '[PROPERTIES]' inside of 'properties.ini'. "
              "Did you accidentally delete it? Exiting program.")
        raise SystemExit
    except configparser.error:
        print("ERROR: Could not find 'properties.ini' file in same directory.")
        raise SystemExit

    #

    print(f"Values pulled from 'properties.ini': \n \t conn: {user_conn_info} \n \t schema_name: {user_schema} \n \t table_name: "
          f"{user_table} " f"\n \t row count: {user_row_count} \n \t threads: {user_thread_count} "
          f"\n \t logging level: {user_logging_level}")
    return user_conn_info, user_schema, user_table, user_row_count, user_thread_count, user_logging_level


def setup_logging(logging_level):
    path = '/'.join((os.path.abspath(__file__).replace('\\', '/')).split('/')[:-1])
    file_timestamp = datetime.now().strftime("%Y%m%d-%H%M%S") + ".log"
    file_location = os.path.join(path, file_timestamp)
    if logging_level == 1:
        logging.basicConfig(
            filename=file_location,
            level=logging.DEBUG,
            format="%(asctime)s: %(message)s"  # adds a timestamp before the logging message
        )
    elif logging_level == 2:
        logging.basicConfig(
            filename=file_location,
            level=logging.INFO,
            format="%(asctime)s: %(message)s"  # adds a timestamp before the logging message
        )
    elif logging_level == 3:
        logging.basicConfig(
            filename=file_location,
            level=logging.ERROR,
            format="%(asctime)s: %(message)s"  # adds a timestamp before the logging message
        )
    logger = logging.getLogger(__name__)
    return logger


def calculate_rows_per_thread(total_row_count, number_of_threads):
    if number_of_threads > total_row_count:
        logger.error(f"Thread count is higher than requested row count. Math impossible.")
        exit()
    elif total_row_count >= number_of_threads:
        rows = int(total_row_count / number_of_threads)
        logger.debug(f"{number_of_threads} threads will generate {rows} each.")
    return rows


def build_threads(thread_count, thread_rows, connection_info, user_schema, user_table):
    threads_list = []
    for i in range(1, thread_count+1):  # threads start at 1 rather than 0
        this_thread = MyThread(i, f"Thread", thread_rows, connection_info, user_schema, user_table)
        threads_list.append(this_thread)
    return threads_list


def start_all_threads(list_of_threads, thread_count):
    logger.debug(f"Starting {thread_count} threads.")
    for thread in list_of_threads:
        thread.start()
    logger.debug(f"Joining {thread_count} threads.")
    for thread in list_of_threads:
        thread.join()


def connect_to_db2(conn_info):
    connection = ibm_db.connect(f"{conn_info}", "", "")
    print(connection)
    return connection


def get_result_set(conn, schema, table):
    sql = (f"\n"
           f"SELECT\n"
           f"TBCREATOR AS SCHEMA,\n"
           f"TBNAME AS TBNAME,\n"
           f"COLNO AS COL_NUM,\n"
           f"NAME AS COL_NAME,\n"
           f"COLTYPE AS COL_TYPE,\n"
           f"LENGTH AS COL_LENGTH,\n"
           f"SCALE AS COL_SCALE\n"
           f"FROM\n"
           f"SYSIBM.SYSCOLUMNS\n"
           f"WHERE\n"
           f"TBNAME = '{table}'\n"
           f"AND\n"
           f"TBCREATOR = '{schema}'\n"
           f"AND\n"
           f"(NAME NOT LIKE 'ROWID' AND NAME NOT LIKE 'DB2_GENERATED%')"
           f"AND\n"
           f"DEFAULT = 'N'\n"
           f"ORDER BY COL_NUM ASC;\n")
    stmt = ibm_db.exec_immediate(conn, sql)
    # TODO: add error handling for SQLCODE=-1598; this error code is a licensing problem.
    # probably want to kill the entire program if this error occurs
    return ibm_db.fetch_both(stmt), stmt


def calculate_random_value(col_type, col_len, col_scale):
    if col_type == "INTEGER":
        random_value = random.randrange(-2147483648, 2147483647)
    elif col_type == "DECIMAL":
        # calculate number of digits left of decimal
        left_of_decimal = col_len - col_scale
        # generate a random number of length digits_to_left
        value1 = random.randint(10 ** (left_of_decimal - 1), 10 ** left_of_decimal - 1)
        # generate a random number, for the scale (digits to right of decimal place)
        value2 = random.randint(10 ** (col_scale - 1), 10 ** col_scale - 1)
        # concat the two string values; Db2 will handle input strings with all digits and convert to decimal data type
        random_value = str(value1) + '.' + str(value2)
    elif col_type == "SMALLINT":
        random_value = random.randrange(-32768, 32767)
    elif col_type == "BIGINT":
        random_value = random.randrange(-9223372036854775800, 9223372036854775800)
    elif col_type == "FLOAT" or col_type == "DECFLOAT":
        random_value = round(random.uniform(-2147483648, 2147483647), 2)
    elif col_type == "CHAR":
        random_value = str(random.choice(string.ascii_letters))
    elif col_type == "VARCHAR":
        randomlength = random.randrange(1, col_len)
        random_value = str(''.join(random.choice(string.ascii_letters) for i in range(randomlength)))
    elif col_type == "DATE":
        random_value = date(random.randrange(1990, 2019), random.randrange(1, 12), random.randrange(1, 27)).isoformat()
    elif col_type == "TIME":
        rtime = int(random.random() * 86400)
        hours = int(rtime / 3600)
        minutes = int((rtime - hours * 3600) / 60)
        seconds = rtime - hours * 3600 - minutes * 60
        random_value = '%02d:%02d:%02d' % (hours, minutes, seconds)
    elif col_type == "TIMESTAMP" or col_type == "TIMESTMP":
        # random value up to 2019-12-31-23.59.59.000000000
        rand_year = str(random.randrange(1990, 2019))
        rand_month = str(random.randrange(1, 12))
        rand_day = str(random.randrange(1, 27))
        rand_hour = str(random.randrange(00, 23)).rjust(2, "0")
        rand_minute = str(random.randrange(00, 59)).rjust(2, "0")
        rand_second = str(random.randrange(00, 59)).rjust(2, "0")
        rand_nano_second = str(random.randrange(00, 999999999)).rjust(9, "0")
        random_value = f"{rand_year}-{rand_month}-{rand_day}-{rand_hour}.{rand_minute}.{rand_second}.{rand_nano_second}"
    elif col_type == "BOOLEAN":
        random_value = str(random.randrange(0, 2))
    elif col_type == "CLOB" or col_type == "DBCLOB":
        random_value = '1234'
    elif col_type == "BLOB":
        random_value = '1234'
    elif col_type == "XML":
        random_value = '<A>XML</A>'
    else:
        logger.error(f"Error. Cannot process data-type {col_type}")
        raise ValueError
        exit()
    return random_value


def convert_result_set_to_nested_list(results, stmt):
    metaDataList = []
    while results:
        metadataListRow = []
        colNum = results["COL_NUM"]
        colName = str.strip(results["COL_NAME"])
        colType = str.strip(results["COL_TYPE"])
        colLength = results["COL_LENGTH"]
        colScale = results["COL_SCALE"]
        metadataListRow.extend((colNum, colName, colType, colLength, colScale))
        metaDataList.append(metadataListRow)
        results = ibm_db.fetch_both(stmt)
    return metaDataList


def generate_list_of_random_data_rows(metadata, rowcount):
    counter = 0
    randomdatalist = []
    for count in range(rowcount):
        randomDataRow = []
        # use meta data to generate a random data row
        for sublist in metadata:
            # assign list values to variables
            col_type = sublist[2]
            col_len = sublist[3]
            col_scale = sublist[4]
            # generate random value
            randomValue = calculate_random_value(col_type, col_len, col_scale)
            randomDataRow.append(randomValue)

        # append newly-created row of random data to the big list of random data
        randomdatalist.append(randomDataRow)
        logger.debug(f"Generated SQL insert row: {randomdatalist}")
        counter = counter + 1
    return randomdatalist


def generate_mass_insert_format(metaDataList):
    mass_insert_list = []
    for sublist in metaDataList:
        mass_insert_list.append("?")
    massInsertFormat = ", ".join(map(str, mass_insert_list))
    return massInsertFormat


def generate_column_name_list(metaDataList):
    columnNameList = []
    for sublist in metaDataList:
        colName = sublist[1]
        columnNameList.append(colName)
    formattedNameList = ", ".join(map(str, columnNameList))
    logger.debug(f"formatted column names list: {formattedNameList}")
    return formattedNameList


# main
# get user requirements
connInfo, schema, table, userTotalRowCount, threadCount, loggerLevel = read_properties_file()
logger = setup_logging(loggerLevel)

# double-check with user that the parsed connection info is correct
iniIsCorrect = input(f"Are these values correct? (Y/N)\n").upper()

if iniIsCorrect == 'Y':
    print('Starting data generation and insertion...')
    # init global counter variable, used to keep track of total records inserted by all threads
    global_rows_inserted = 0
    # init global lock, used to force each thread to increment global row insertion count
    threadLock = threading.Lock()
    # calculate amount of rows each thread is responsible for
    rowsPerThread = calculate_rows_per_thread(userTotalRowCount, threadCount)
    # create threads to handle user values, start threads
    threadsList = []
    threadsList = build_threads(threadCount, rowsPerThread, connInfo, schema, table)
    start_all_threads(threadsList, threadCount)
    exit()

elif iniIsCorrect == 'N':
    print("Sorry about that! Double-check your properties.ini file and try running the program again.")
    exit()

**Comment by op123singh** [comment] 2021-04-19 18:07
Just posted the whole program. Hope it helps

**Comment by amukherjee28** [comment] 2021-04-20 16:42
Hi,

I tired running a simple threading program and it seems to working for me in both Windows and ZOS connecting to ZOS database server.

APPLICATION CODE

```

import threading
import time
import ibm_db

class MyThread(threading.Thread):
    def __init__(self,id,conn_string):
        threading.Thread.__init__(self)
        self.id = id
        print("======FROM INIT======")
        print(self.id)
        self.conn_string = conn_string


    def run(self):
        print("=> Inside run")
        print("=> CONNECTION STRING : " + self.conn_string)
        conn = connect_to_db2(self.conn_string)
        if conn:
            insert_query = "insert into thread_test values(" + str(self.id) + ",'test_val')"
            exe_insert = ibm_db.exec_immediate(conn,insert_query)

            select_query = "select * from thread_test"
            exe = ibm_db.exec_immediate(conn,select_query)
            row = ibm_db.fetch_tuple(exe)
            print("=> Fetch row")
            while row:
                print(row[0])
                print(row[1])
                row = ibm_db.fetch_tuple(exe)

def build_thread(count,conn_string):
    thread_list = []
    for i in range (1,count+1):
        this_thread = MyThread(i,conn_string)
        thread_list.append(this_thread)
    return thread_list

def start_thread(list_of_threads):
    print("======STARTING THREADS=======")
    for thread in list_of_threads:
        thread.start()
        print("joining threads....")
    for thread in list_of_threads:
        thread.join()

def connect_to_db2(conn):
    print("====MAKING DATABASE CONNECTION=======")
    connection = ibm_db.connect(conn,'','')
    print(connection)
    return connection

def create_table(conn):
    print("=====CREATING TABLE=======")
    connection = ibm_db.connect(conn,'','')
    if connection:
        query_create = "create table thread_test (c1 integer,c2 varchar(30))"
        try:
            exe = ibm_db.exec_immediate(connection,query_create)
        except:
            pass
    print("=> table created")


connection_string="connection string"
create_table(connection_string)
thread_list = []
thread_list = build_thread(4,connection_string)
start_thread(thread_list)
```

Can you try this once.

This is bit simpler from the program that you have send.

Thanks.

**Comment by amukherjee28** [comment] 2021-04-20 17:13
Can you please check your application code once, if thing are going fine there.
I could not run the exact program you gave as I see there is come configuration file that the program reads and then does the connection.
So I constructed a simple program following similar logic you have used.

however I would to happy the run the program you gave, could you also provide me the configuration file you are using.
You can remove the connection details and send me the file.

Thanks.

**Comment by op123singh** [comment] 2021-04-20 20:39
here is the contents of properties.ini file. Hope it helps. 
[PROPERTIES]=
CONNECTION=DATABASE=DSNT5;HOSTNAME=9.30.178.50;PORT=50500;PROTOCOL=TCPIP;UID=xxx;PWD=xxx;
SCHEMA=ADMF001
TABLE=ITEM
RECORDS= 1000
THREADS= 10
LOGLEVEL=1

**Comment by imavo** [comment] 2021-04-21 19:34
@op123singh In your ODBC trace, do you find any other symptom before the HY010 ?  
Specifically anything like CLI0125E or similar?
I've found it necessary to verify success for every ibm_db call before invoking subsequent ibm_db calls.

**Comment by op123singh** [comment] 2021-04-22 00:50
[APPLTRC.zip](https://github.com/ibmdb/python-ibmdb/files/6354697/APPLTRC.zip)

I am attaching the ZIP file of the traces. Please have a look

**Comment by imavo** [comment] 2021-04-22 10:42
@op123singh 

That trace shows ten HY010 (one per thread?) on SQLRowCount() , which means a "function sequence error" , typically a programming error somewhere.

Please make two changes to your code, re run it with odbc trace, and let us know the results.

(1) remove the trailing semicolon from the SQL query, on the line:
`   f"ORDER BY COL_NUM ASC;\n")`
   
   This will reduce noise in the trace, caused by sqlstate 01568 warnings, and 
   also be more performant because no need to log the warning.
    
(2) execute_many() returns either None on error, or count of rows-inserted on success.
    Your code causes `SQLRowCount()` to run twice and that's the function throwing `HY010`.
    Please change your code to check result of `execute_many()` not being `None`
    and then use that for row_count (first initialize row_count = 0).  
    You could also check for the result of execute_many() == rows_to_generate.
    Remove the call to num_rows() from the `finally:` clause.

**Comment by imavo** [comment] 2021-04-22 18:26
Which is more important -  working code,  or avoiding change?

Db2-LUW and Db2-Z/os are different products, different code-bases, different SQL dialect, different catalogue tables.

There is no factual basis to assert that "it should work in this env without any change".

**Comment by op123singh** [comment] 2021-04-23 05:56
You are right - working code is important.  I work for Db2 zOS.  Hence understand where you are going with this. Please tell me the difference you are seeing here. Also I have send u the code hence it would be better if u can modify the code changes and send me the code.

**Comment by imavo** [comment] 2021-04-23 09:11
I do not have a current environment for testing with Db2-Z/os & USS (but others on here may have).   

If the suggested code changes change the symptom, then we can make progress on getting root cause. 

My suggestions are specific and trivial, so the script-developer should be able to easily make the code changes and test (with odbc tracing enabled) if you have a suitable environment with Db2-Z/os and USS.

**Comment by op123singh** [comment] 2021-04-23 12:12
As mentioned earlier the test works from LUW client to Db2 zOS.  The only change is now it is run from USS to Db2 zOS.  Please give me a specific reason why it should not work ( behavior change documented and not a bug ). I will suggest you to have an env and test your suggestion before recommending to a customer. As a friendly customer, I am ready to share my env with you. Please setup a work session/ meeting with me if you want to go that route.

**Comment by imavo** [comment] 2021-04-23 12:40
As mentioned, others on here will have access to USS. 

I have no connection with IBM.  But I do alter ibm_db for private builds when I find issues.

When you post python code containing an obvious issue , maybe do not be surprised if someone suggests to check if removing that issue would alter the  error symptom!  

But you see things differently, so good luck to you.

**Comment by op123singh** [comment] 2021-04-26 17:30
Request you to arrange a call with @amukhe02. We can check what is going wrong. - Binit kumar. 

As proposed in my previous comment, let us meet and resolve this issue. Please let me know what is a good time for you.

**Comment by amukherjee28** [comment] 2021-04-27 06:27
Hi @op123singh 

We can get in touch tomorrow over slack.

**Comment by amukherjee28** [comment] 2021-05-04 07:54
Hi @op123singh 

execute_many API is not supported on Z/OS as platform and hence we were seeing the issue in the program that you were running.
There were work arounds suggested for the same.

I have updated the Z/OS documentation to point the same as well.

I guess we have a conclusion on this issue and we can close this case.

**Comment by SabaKauser** [comment] 2021-05-04 08:07
execute_many is not supported. But I do remember adding a check and we should have exited than executing in first place. @amukherjee28 you might want to check why we don't exit and continue. This should not happen.

**Comment by amukherjee28** [comment] 2021-05-04 08:21
Hi @SabaKauser 

It did exit as expected.
This was just to figure out what was actually going wrong when an application is ported to ZOS from other platforms and also a doc update to point out the same.

Thanks.

**Comment by SabaKauser** [comment] 2021-05-04 08:32
> 
> 
> Hi @SabaKauser
> 
> It did exit as expected.
> This was just to figure out what was actually going wrong when an application is ported to ZOS from other platforms and also a doc update to point out the same.
> 
> Thanks.

perfect.. then what made us investigate this so long?

**Comment by amukherjee28** [comment] 2021-05-04 08:39
We were trying to make the application work without the use of execute_many in ZOS.
that took some time to investigate. Slack call helped.

**Comment by SabaKauser** [comment] 2021-05-04 08:44
ok. SQL_ATTR_CHAINING_BEGIN  and SQL_ATTR_CHAINING_END are not supported by z/OS ODBC and hence I disabled.

**Comment by amukherjee28** [comment] 2021-05-04 08:52
doc updated

**Comment by amukherjee28** [comment] 2021-06-23 09:48
The resolution for this issue was provided.
Hence closing this issue.

**Closed by amukherjee28** 2021-06-23 09:48 UTC
