### ISSUE TITLE
Process finished with exit code 250

### ISSUE THREAD

**Issue by RomanRubiales** [ibmdb/python-ibmdb#742] opened 2022-04-11 07:58 UTC
Hi everyone!,
I am testing an application developed with django, running in local but connected to DB2 in IBM Cloud, and I am receiving exit code 250 when running "runserver" at PyCharm:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/103412209/162689960-4448ffad-01ff-44f9-9f9e-f31ab095696d.png">

My dependencies:
asgiref==3.5.0
backports.zoneinfo==0.2.1
Django==3.2
django-contrib-comments==2.2.0
ibm-db==3.1.1
ibm-db-django==1.5.1.0
pytz==2022.1
regex==2020.7.14
six==1.16.0
sqlparse==0.4.2

(db2) (base) Romans-MacBook-Pro:db2test romanrubiales$ python3 --version
Python 3.8.5

Here my configuration for connecting to DB2.
DATABASES = {

    'default': {

        'ENGINE': 'ibm_db_django',

        'NAME': 'bludb',

        'USER': 'XXXXXXXX',

        'PASSWORD': 'XXXXXXXXXXXXXX',

        'HOST': 'c6e294c6-5584-41ac-af51-fc91481dfe4f.bs2io90l08kqb1od8lcg.databases.appdomain.cloud',

        'PORT': '30893',

        'AUTHENTICATION': 'SERVER',

        'SECURITY': 'ssl',

        'PCONNECT': True,  # Optional property, default is false

    }

}
"makemigrations" and "migrate" commands worked properly, and schemas were uploaded to DB2 in Cloud, but the problem arises when running the application in local connected with the DB2 in Cloud.

In order to isolate the problem I also run the same application but connected to DB2 in local (docker based) and worked fine. This was the configuration used:

DATABASES = {

    'default': {

        'ENGINE': 'ibm_db_django',

        'NAME': 'testdb',

        'USER': 'db2inst1',

        'PASSWORD': 'xxxxxxxxxxxxx',

        'HOST': 'localhost',

        'PORT': '50000',

        #'AUTHENTICATION': 'SERVER',

        #'SECURITY': 'ssl',

        'PCONNECT': True,  # Optional property, default is false

    }

}

I thought about an SSL problem, but the python manage.py migrate works, and the schemas are loaded at IBM Cloud
Any help on that? Thank you in advance.

**Comment by amukherjee28** [comment] 2022-04-11 08:17
@RomanRubiales This issue looks to be Django specific issue hence it would be better if the issue is reported in Django.
Also with respect to the issue reported, I see the difference in connection parameter when tested with db2 on cloud and local database server. While connecting to cloud can it be tested by removing the parameter AUTHENTICATION=SERVER.

As I understand your local system is MAC machine.
In the second case when you say its working could you explain where exactly the server is installed. Is it installed in docker?

Thanks

**Comment by RomanRubiales** [comment] 2022-04-11 09:09
yes, in the second case, the db2 is wasrunning on docker, and this docker under MacOS.

It seems that the problem could be related to the connection configuration. Data for the connection was taken from my “IBM DB2 on Cloud” service:  

<img width="695" alt="image" src="https://user-images.githubusercontent.com/103412209/162703765-0b303430-30fa-476e-a171-cb56879c3bd5.png">

<img width="565" alt="image" src="https://user-images.githubusercontent.com/103412209/162703826-aba06494-18a6-4cd1-9a23-1ea38933e422.png">

The SSL certificate was downloaded and imported to the Mac’s keychain.

**Comment by imavo** [comment] 2022-04-11 09:33
Add some tracing or diagnostics to your code, because the process exit-code by itself is not enough information to allow problem determination.
If the problem is 100% reproducible, and happens quickly , then you can also use tracing built into the clidriver, or use django logging to narrow down the problem.
You should verify that the connection to the cloud-database succeeds , or always fails, or fails only after some period  of time has elapsed.
The big difference between running locally (with db in local containers) versus running locally (with db on cloud) is the latency, and certain adjustments might be necessary in terms of tuning for timeouts.

**Comment by amukherjee28** [comment] 2022-04-11 09:39
With the IBM Db2 on cloud service, use the connection string as follows

HOSTNAME=<hostname_as_highlighted>;DATABASE=BLUDB;PORT=30893;UID=<USERID_AS HIGHLIGHTED>;PWD=<password_as_highlighted>;security=ssl;

Only use these parameters for connection and ignore any other if any. For cloud connection you can connect without using the server certificate provided along with the cloud container. Including security=ssl in the connection is enough to establish could ssl connection. Use these details and check once if it works for your cloud instance.

**Comment by RomanRubiales** [comment] 2022-04-12 08:56
Finally fixed, a missing environment variable no configured at PyCharm was the problem. 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/103412209/162921943-0b263a2f-3700-4ae3-9eae-a59324e501c7.png">
DYLD_LIBRARY_PATH must be set to point to lib folder where clidriver is installed. I had this variable set in my virtual environment, that is why “python3 manage.py migrate” worked, but I forgot to include it at PyCharm configuration. 
Thank you for your help!

**Comment by amukherjee28** [comment] 2022-04-12 10:37
That's great. Can we close this issue as we are able to move forward.

Thanks.

**Comment by RomanRubiales** [comment] 2022-04-12 13:18
Yes, you can close this issue. Thanks.

**Closed** 2022-04-13 05:39 UTC
