### ISSUE TITLE
Unable to install v3.1.0 on z/OS

### ISSUE THREAD

**Issue by kenjaninja** [ibmdb/python-ibmdb#707] opened 2022-01-04 05:22 UTC
# Symptom
Installing v3.1.0 for Python 3 on z/OS fails during the build_ext step. 3.0.4 installs normally.

### 3.1.0
```
2022-01-03T18:40:16,224   running build_ext
2022-01-03T18:40:16,226   creating build/temp.os390-27.00-2964-3.8
2022-01-03T18:40:16,226   /bin/xlc -fno-strict-aliasing -DNDEBUG -O3 -qarch=10 -qlanglvl=extc99 -q64 -Wc,DLL -D_XOPEN_SOURCE_EXTENDED -D_UNIX03_THREADS -D_POSIX_THREADS -D_OPEN_SYS_FILE_EXT -qexportall -qascii -qstrict -qnocsect -Wa,asa,goff -Wa,xplink -qgonumber -qenum=int -I/STLABBA/tmp/pip-install-ht9lx9ow/ibm-db/sdsnc.h -I/u/kenohh1/ibm_db_venv/include -I/SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/include/python3.8 -c ibm_db.c -o build/temp.os390-27.00-2964-3.8/ibm_db.o
2022-01-03T18:40:17,716   FSUM3212 xlc: Command option -fno-strict-aliasing is incorrect for z/OS platform - ignored.
2022-01-03T18:40:18,127   WARNING CCN3236 /usr/include/unistd.h:1169  Macro name _POSIX_THREADS has been redefined.
2022-01-03T18:40:20,588   /bin/xlc build/temp.os390-27.00-2964-3.8/ibm_db.o /STLABBA/tmp/pip-install-ht9lx9ow/ibm-db/libdsnao64c.x -L. -L/usr/lpp/IBM/cyp/v3r8/pyz/lib -o build/lib.os390-27.00-2964-3.8/ibm_db.so
2022-01-03T18:40:22,142    IEW2469E 9907 THE ATTRIBUTES OF A REFERENCE TO dlclose FROM SECTION $PRIV000010
2022-01-03T18:40:22,142             DO NOT MATCH THE ATTRIBUTES OF THE TARGET SYMBOL. REASON  2
2022-01-03T18:40:22,173    IEW2469E 9907 THE ATTRIBUTES OF A REFERENCE TO dlclose FROM SECTION $PRIV000010
2022-01-03T18:40:22,174             DO NOT MATCH THE ATTRIBUTES OF THE TARGET SYMBOL. REASON  2
...
2022-01-03T18:40:22,208    IEW2456E 9207 SYMBOL PyCapsule_Import UNRESOLVED.  MEMBER COULD NOT BE INCLUDED
2022-01-03T18:40:22,208             FROM THE DESIGNATED CALL LIBRARY.
2022-01-03T18:40:22,208    IEW2470E 9511 ORDERED SECTION CEESTART NOT FOUND IN MODULE.
2022-01-03T18:40:22,208    IEW2648E 5111 ENTRY CEESTART IS NOT A CSECT OR AN EXTERNAL NAME IN THE MODULE.
2022-01-03T18:40:22,209    IEW2689W 4C40 DEFINITION SIDE FILE IS NOT DEFINED.
2022-01-03T18:40:22,209   FSUM3065 The LINKEDIT step ended with return code 8.
2022-01-03T18:40:22,209   error: command '/bin/xlc' failed with exit code 3
2022-01-03T18:40:22,216   ERROR: Failed building wheel for ibm-db
2022-01-03T18:40:22,216 Failed to build ibm-db
```
### 3.0.4
```
2022-01-03T18:44:39,376     running build_ext
2022-01-03T18:44:39,378     building 'ibm_db' extension
2022-01-03T18:44:39,378     creating build/temp.os390-27.00-2964-3.8
2022-01-03T18:44:39,378     /bin/xlc -fno-strict-aliasing -DNDEBUG -O3 -qarch=10 -qlanglvl=extc99 -q64 -Wc,DLL -D_XOPEN_SOURCE_EXTENDED -D_UNIX03_THREADS -D_POSIX_THREADS -D_OPEN_SYS_FILE_EXT -qexportall -qascii -qstrict -qnocsect -Wa,asa,goff -Wa,xplink -qgonumber -qenum=int -I/STLABBA/tmp/pip-install-1jkwfkp1/ibm-db/sdsnc.h -I/u/kenohh1/ibm_db_venv/include -I/SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/include/python3.8 -c ibm_db.c -o build/temp.os390-27.00-2964-3.8/ibm_db.o
2022-01-03T18:44:40,756     FSUM3212 xlc: Command option -fno-strict-aliasing is incorrect for z/OS platform - ignored.
2022-01-03T18:44:41,078     WARNING CCN3236 /usr/include/unistd.h:1169  Macro name _POSIX_THREADS has been redefined.
2022-01-03T18:44:43,284     /bin/xlc build/temp.os390-27.00-2964-3.8/ibm_db.o /STLABBA/tmp/pip-install-1jkwfkp1/ibm-db/libdsnao64c.x -L. -o build/lib.os390-27.00-2964-3.8/ibm_db.so -Wl,dll /SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/config-3.8/libpython3.8.x -q64
2022-01-03T18:44:44,873     running install_lib
...
# Installs as normal
```
## Info
Our python installation is at `/SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz`
```
export PYTHON_HOME=/SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz
export PATH=$PYTHON_HOME/bin:$PATH
export LIBPATH=$PYTHON_HOME/lib:$LIBPATH
```
### Python install

The second XLC step is failing for 3.1.0, but not 3.0.4
```bash
# 3.1.0
/bin/xlc build/temp.os390-27.00-2964-3.8/ibm_db.o /STLABBA/tmp/pip-install-ht9lx9ow/ibm-db/libdsnao64c.x -L. -L/usr/lpp/IBM/cyp/v3r8/pyz/lib -o build/lib.os390-27.00-2964-3.8/ibm_db.so

# 3.0.4
/bin/xlc build/temp.os390-27.00-2964-3.8/ibm_db.o /STLABBA/tmp/pip-install-1jkwfkp1/ibm-db/libdsnao64c.x -L. -o build/lib.os390-27.00-2964-3.8/ibm_db.so -Wl,dll /SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/config-3.8/libpython3.8.x -q64
```
The difference being the options shown below:
```bash
# 3.1.0
-L/usr/lpp/IBM/cyp/v3r8/pyz/lib

# 3.0.4
-Wl,dll /SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/config-3.8/libpython3.8.x
-q64
```
`/usr/lpp/IBM/cyp/v3r8/pyz/lib` does not exist on our system, which seems to cause the xlc command to fail. 

--------

It seems like the 3.0.4 install was able to use the set LIBPATH (`/SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/lib:$LIBPATH`) during the install, while the 3.1.0 install does not. Is this intended behavior? Any help would be appreciated.

**Comment by amukherjee28** [comment] 2022-01-04 06:20
@kenjaninja 

I did try installing the latest version using ```pip install ibm_db``` on Z/OS running with python 3.8.

I had no issue installing the driver.

INSTALL LOG

```
pip3 install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.0.tar.gz (797 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (PEP 517) ... done
  Created wheel for ibm-db: filename=ibm_db-3.1.0-cp38-cp38-os390_27_00_8561.whl size=304200 sha256=70b69fb5a91a19160781cd06527d34e9fc88d24b9ea172d4cd0f74f4b9ed7f56
  Stored in directory: /u/ts5977/.cache/pip/wheels/43/71/0a/3065745bc1dc4cafbdcb09e2557082609f7689b16108b670df
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.1.0
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/u/ts5977/ibm_python_venv/bin/python3 -m pip install --upgrade pip' command.
bash-4.3$
```

You are building the code after cloning from git is my understanding.
Are you changing anything in the code or you are building it as it is.

**Comment by kenjaninja** [comment] 2022-01-04 06:43
I am actually just using `pip install ibm-db==3.1.0`, not building the code from a cloned git repo.

**Comment by amukherjee28** [comment] 2022-01-04 08:11
@kenjaninja the logs that you have provided looks to be from source code build and install and so I assumed so.

Coming back to the issue there has be no change in the install logic from 3.0.4 to 3.1.0
The only change that went in was the support for latest setuptools.

The additional Library linking that you have pointed out looks to be the problem. Can you please check your environment variable once if something is setting the additional library flag for the invalid path.

**Comment by kenjaninja** [comment] 2022-01-04 22:09
Grepping the environment variables:
```bash
$ env | grep /usr/lpp/IBM/cyp/v3r8/pyz/lib
FFI_LIB=/SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/lib/ffi
LIBPATH=/SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:.
```
I don't see any reference to the new library flag `-L/usr/lpp/IBM/cyp/v3r8/pyz/lib`

**Comment by amukherjee28** [comment] 2022-01-11 17:57
@kenjaninja new version has been release.
Can you please check with the latest one if the issue still persists for you.

**Comment by kenjaninja** [comment] 2022-01-11 20:24
I am still getting the same issue installing `ibm-db==3.1.1`

**Comment by amukherjee28** [comment] 2022-02-24 10:07
This looks to be a specific env issue. We have tested the release on z/OS machines and installation works fine. None of the test system has any problem with respect to installation. What appears is a specific issue. So I request you to please check your system once.

**Comment by kenjaninja** [comment] 2022-02-24 20:01
I will try. Do you have any suggestions as to which variables/settings in my environment that I can change/check?

**Comment by amukherjee28** [comment] 2022-02-25 09:00
Could you try once installing from the code directly.
The steps are as follows

1. Clone the code from https://github.com/ibmdb/python-ibmdb.git
2. once cloned goto the folder IBM_DB\ibm_db
3. then run command ```python setup.py install```

You can paste me the complete log that you see while doing this. Then I can compare it against my machine and see what goes wrong.

**Comment by kenjaninja** [comment] 2022-02-26 00:33
I tried cloning and running `setup.py`. I'm getting some universal character name errors:
```
$ git clone https://github.com/ibmdb/python-ibmdb.git
$ cd python-ibmdb/IBM_DB/ibm_db/
$ python3 setup.py install
Detected 64-bit Python
running install
running build
running build_py
running egg_info
writing ibm_db.egg-info/PKG-INFO
writing dependency_links to ibm_db.egg-info/dependency_links.txt
writing top-level names to ibm_db.egg-info/top_level.txt
writing manifest file 'ibm_db.egg-info/SOURCES.txt'
reading manifest file 'ibm_db.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.png' under directory 'ibm_db_tests'
warning: no files found matching '*.jpg' under directory 'ibm_db_tests'
warning: no files found matching '*' under directory 'clidriver'
warning: no files found matching '*' under directory 'ibm_db_dlls'
warning: no previously-included files found matching 'config.py'
writing manifest file 'ibm_db.egg-info/SOURCES.txt'
copying certs/ibm_certs.pem -> build/lib.os390-27.00-2964-3.8/certs
running build_ext
building 'ibm_db' extension
creating build/temp.os390-27.00-2964-3.8
/bin/xlc -fno-strict-aliasing -DNDEBUG -O3 -qarch=10 -qlanglvl=extc99 -q64 -Wc,DLL -D_XOPEN_SOURCE_EXTENDED -D_UNIX03_THREADS -D_POSIX_THREADS -D_OPEN_SYS_FILE_EXT -qexportall -qascii -qstrict -qnocsect -Wa,asa,goff -Wa,xplink -qgonumber -qenum=int -I/u/pyusr/python-ibmdb/IBM_DB/ibm_db/sdsnc.h -I/SVT/usr/lpp/python38/usr/lpp/IBM/cyp/v3r8/pyz/include/python3.8 -c ibm_db.c -o build/temp.os390-27.00-2964-3.8/ibm_db.o
FSUM3212 xlc: Command option -fno-strict-aliasing is incorrect for z/OS platform - ignored.
ERROR CCN3191 ./ibm_db.c:1     The character ^? is not a valid C source character.
ERROR CCN3766 ./ibm_db.c:1     The universal character name "0x8a" is not in the allowable range for an identifier.
ERROR CCN3766 ./ibm_db.c:1     The universal character name "0x8e" is not in the allowable range for an identifier.
ERROR CCN3766 ./ibm_db.c:1     The universal character name "0x8b" is not in the allowable range for an identifier.
ERROR CCN3766 ./ibm_db.c:1     The universal character name "0x5" is not in the allowable range for an identifier.
ERROR CCN3766 ./ibm_db.c:1     The universal character name "0x5" is not in the allowable range for an identifier.
...
```

I assume this is due to the files not being correctly tagged when I clone the repository? How should I proceed? Should I manually tag the files with `chtag`?

```
$ ls -T
- untagged    T=off CHANGES.md
- untagged    T=off LICENSE
- untagged    T=off MANIFEST.in
- untagged    T=off NOTES.md
- untagged    T=off README.md
                    build
                    certs
- untagged    T=off config.py.sample
- untagged    T=off ibm_db.c
                    ibm_db.egg-info
- untagged    T=off ibm_db.h
- untagged    T=off ibm_db_dbi.py
                    ibm_db_tests
t ISO8859-1   T=on  libdsnao64c.so
- untagged    T=off libdsnao64c.x
- untagged    T=off pyproject.toml
- untagged    T=off run_all_tests
- untagged    T=off run_individual_tests
                    sdsnc.h
- untagged    T=off setup.py
- untagged    T=off testfunctions.py
- untagged    T=off tests.py
```

**Comment by amukherjee28** [comment] 2022-02-28 08:33
I had the logs collected from my system. 

Here are few details

Install log
```
bash-4.3$ python3 setup.py install
Detected 64-bit Python
running install
running build
running build_py
copying testfunctions.py -> build/lib.os390-27.00-8561-3.8
copying ibm_db_tests/test_000_PrepareDb.py -> build/lib.os390-27.00-8561-3.8/ibm_db_tests
copying ibm_db_tests/test_005_ConnBadUserBadPwd.py -> build/lib.os390-27.00-8561-3.8/ibm_db_tests
copying ibm_db_tests/test_alltypes.py -> build/lib.os390-27.00-8561-3.8/ibm_db_tests
copying ibm_db_tests/test_alltypesarray.py -> build/lib.os390-27.00-8561-3.8/ibm_db_tests
copying ibm_db_tests/test_146a_CallSPINAndOUT_Blob_Param.py -> build/lib.os390-27.00-8561-3.8/ibm_db_tests
copying ibm_db_tests/test_unicodeTable.py -> build/lib.os390-27.00-8561-3.8/ibm_db_tests
running egg_info
writing ibm_db.egg-info/PKG-INFO
writing dependency_links to ibm_db.egg-info/dependency_links.txt
writing top-level names to ibm_db.egg-info/top_level.txt
reading manifest file 'ibm_db.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'clidriver'
warning: no files found matching '*' under directory 'ibm_db_dlls'
warning: no previously-included files found matching 'config.py'
writing manifest file 'ibm_db.egg-info/SOURCES.txt'
running build_ext
building 'ibm_db' extension
/bin/xlc -fno-strict-aliasing -DNDEBUG -O3 -qarch=10 -qlanglvl=extc99 -q64 -Wc,DLL -D_XOPEN_SOURCE_EXTENDED -D_UNIX03_THREADS -D_POSIX_THREADS -D_OPEN_SYS_FILE_EXT -qexportall -qascii -qstrict -qnocsect -Wa,asa,goff -Wa,xplink -qgonumber -qenum=int -I/u/ts5977/PYTHON_GIT/python-ibmdb/IBM_DB/ibm_db/sdsnc.h -I/u/ts5977/ibm_python_venv/include -I/rsusr/pyz/include/python3.8 -c ibm_db.c -o build/temp.os390-27.00-8561-3.8/ibm_db.o
FSUM3212 xlc: Command option -fno-strict-aliasing is incorrect for z/OS platform - ignored.
WARNING CCN3236 /usr/include/unistd.h:1169  Macro name _POSIX_THREADS has been redefined.
WARNING CCN3068 ./ibm_db.c:5782  Operation between types "unsigned short*" and "char*" is not allowed.
WARNING CCN3068 ./ibm_db.c:5788  Operation between types "unsigned short*" and "char*" is not allowed.
WARNING CCN3068 ./ibm_db.c:5795  Operation between types "unsigned short*" and "char*" is not allowed.
/bin/xlc build/temp.os390-27.00-8561-3.8/ibm_db.o /u/ts5977/PYTHON_GIT/python-ibmdb/IBM_DB/ibm_db/libdsnao64c.x -L. -o build/lib.os390-27.00-8561-3.8/ibm_db.so -Wl,dll /rsusr/pyz/lib/python3.8/config-3.8/libpython3.8.x -q64
running install_lib
```

TAGs for the files

```
t ISO8859-1   T=on  config.py
t ISO8859-1   T=on  config.py.sample
t ISO8859-1   T=on  ibm_db.c
FSUMF173 Warning: ibm_db.egg-info is a directory and will not be traversed without -R.
t ISO8859-1   T=on  ibm_db.h
t IBM-1047    T=on  ibm_db.x
t ISO8859-1   T=on  ibm_db_dbi.py
FSUMF173 Warning: ibm_db_tests is a directory and will not be traversed without -R.
t ISO8859-1   T=on  libdsnao64c.so
t IBM-1047    T=on  libdsnao64c.x
b binary      T=off odbc_appl_trace
b binary      T=off odbc_diag_trace
t IBM-1047    T=on  odbc_test.py
b binary      T=off odbc_trace_control
t ISO8859-1   T=on  pyproject.toml
b binary      T=off run_all_tests
b binary      T=off run_all_tests_modified
t ISO8859-1   T=on  run_individual_tests
FSUMF173 Warning: sdsnc.h is a directory and will not be traversed without -R.
t ISO8859-1   T=on  setup.py
t ISO8859-1   T=on  summary.out
t ISO8859-1   T=on  testfunctions.py
t ISO8859-1   T=on  testfunctions.py_modified
t ISO8859-1   T=on  tests.py
```

The only difference I see is in the tags.
Can you change the tags as per mine and check once.
There should not any other differences.

**Comment by amukherjee28** [comment] 2022-03-02 05:33
@kenjaninja this is something that you need check with the python installed in your system.
Python for ZOS is usually a bit different from the others and hence you need to verify the configurations once.
Also check if the pip installed along with the python is working as expected or not,

This is more on python configuration issue rather that package install issue.

Have a check once.

**Comment by amukherjee28** [comment] 2022-03-04 07:47
I have a confusion with the pip install log that you are getting. While doing pip install you should not be able to see the log that you have pasted. Not sure why that is popping up for you.

Here are the few steps I follow while doing ibm_db installation in ZOS.

1. set the following env paths
```
export TERM=xterm
export PATH=/u/USER/ibm_python_venv/bin:$PATH
export STEPLIB=XXXX.DSNC10.SDSNLOAD
export STEPLIB=XXXX.DSNC10.SDSNLOD2:$STEPLIB
export STEPLIB=SSID.SDSNEXIT:$STEPLIB
export DSNAOINI=$HOME/CC1C.ini
export IBM_DB_HOME='XXXX.DSNC10'
```

Once I have these paths set, heres my pip install log

```
bash-4.3$ pip3 install ibm_db
Collecting ibm_db
  Downloading ibm_db-3.1.1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 12.5 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (PEP 517) ... done
  Created wheel for ibm-db: filename=ibm_db-3.1.1-cp38-cp38-os390_27_00_8561.whl size=379071 sha256=b3c7ba953e0e6ff8c48aec5055d20910e4cefe094098ea281ade5f2dd8f5e963
  Stored in directory: /u/ts5977/.cache/pip/wheels/79/ca/5a/0aa8ee4ff812a4d3b02f09150732219e5fccbf03a84005b99c
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.1.1
```

Ideally pip install should not go through the complete output that you see. Your pip  output is more similar to the output we see when installation is done via source code using setup.py

I am not an expert to check the internals in the ZOS systems though, but you need to check why your pip install fails here
```
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /u/pyusr/issue_707/venv/bin/python3 /u/pyusr/issue_707/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp0zrbwjgn
       cwd: /STLABBA/tmp/pip-install-v8b5js_t/ibm-db
```

I am not sure if your ZOS system has all latest PTF's installed and others.
Please check these once, and let me know.

**Comment by amukherjee28** [comment] 2022-03-04 07:49
Also since the installation via source code (using setup.py) goes through fine I can assume that there is no issue with XLC compilation. So it has be some issue with the pip that has to be checked in here.

**Comment by bimalkjha** [comment] 2022-03-04 12:58
@kenjaninja I hope you have configured the clidriver as per [this documentation](https://github.com/ibmdb/node-ibm_db#configure-odbc-driver-on-zos). Please go through this documentation and verify your environment. Thanks.

**Comment by amukherjee28** [comment] 2022-03-23 08:54
@kenjaninja 
Can we have an update on this please.
Was the above link helpful.

Thanks

**Comment by kenjaninja** [comment] 2022-03-23 20:34
### ODBC Driver on z/OS Configuration
UI60551 is installed
ODBC packages are bound
EXECUTE on DSNACLI is granted on PUBLIC
![image](https://user-images.githubusercontent.com/12107190/159789696-39099969-15a6-4fc8-bf2c-b79fd6eeaa67.png)
STEPLIB is set to `STEPLIB=DSNA1.DA11.SDSNEXIT:DSNA1.DA11.SDSNLOAD:DSNA1.DA11.SDSNLOD2`
DSNAOINI is configured
```ini
[COMMON]
MVSDEFAULTSSID=DSNA1
CONNECTTYPE=1
MULTICONTEXT=2
CURRENTAPPENSCH=ASCII
FLOAT=IEEE

[DSNA1]
MVSATTACHTYPE=RRSAF
PLANNAME=DSNACLI

[DSNA1]
AUTOCOMMIT=1
CURSORHOLD=1
```

### pip v22.0.3 output
Updated pip to v22.0.3, `pip install ibm-db==3.1.1` output says:
>note: This error originates from a subprocess, and is likely not a problem with pip.
Full output
```...
   IEW2689W 4C40 DEFINITION SIDE FILE IS NOT DEFINED.
  FSUM3065 The LINKEDIT step ended with return code 8.
  error: command '/bin/xlc' failed with exit code 3
  error: subprocess-exited-with-error

  Building wheel for ibm-db (pyproject.toml) did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /u/pyusr/issue_707/fresh-venv/bin/python3 /u/pyusr/issue_707/fresh-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpjie6bhbc
  cwd: /STLABBA/tmp/pip-install-ehy5pgjs/ibm-db_bacdb6b1a84a40db9b53922299d76429
  Building wheel for ibm-db (pyproject.toml) ... error
  ERROR: Failed building wheel for ibm-db
Failed to build ibm-db
ERROR: Could not build wheels for ibm-db, which is required to install pyproject.toml-based projects
```

**Comment by amukherjee28** [comment] 2022-03-29 10:18
After looking into the install logs provided I could see a difference between the two environmets,
In your case the installation fails in while building wheels
```
Building wheel for ibm-db (pyproject.toml) ... error
```

This step in my environment uses PEP 517
```
Building wheel for ibm-db (PEP 517) ... done
```

We have introduced the pyproject.toml file in the last release for the setuptools dependency.

So could you check if you have setuptools latest version installed via pip.
if not can you try and install setuptools and then install ibm_db.

**Comment by kenjaninja** [comment] 2022-04-05 23:20
I upgraded setuptools to the latest version:
```
Collecting setuptools
  Downloading https://na.artifactory.swg-devops.com/artifactory/api/pypi/hyc-db2z-svt-pypi-virtual/packages/packages/0c/3c/548d361162702df85a0301f0cd0c47d05176b20bb086077a0fda740daf41/setuptools-62.0.0-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 105.9 kB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 60.9.3
    Uninstalling setuptools-60.9.3:
      Successfully uninstalled setuptools-60.9.3
Successfully installed setuptools-62.0.0
```

but I still get the same error:
```
   IEW2648E 5111 ENTRY CEESTART IS NOT A CSECT OR AN EXTERNAL NAME IN THE MODULE.
   IEW2689W 4C40 DEFINITION SIDE FILE IS NOT DEFINED.
  FSUM3065 The LINKEDIT step ended with return code 8.
  error: command '/bin/xlc' failed with exit code 3
  error: subprocess-exited-with-error

  Building wheel for ibm-db (pyproject.toml) did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /u/pyusr/issue_707/fresh-venv/bin/python3 /u/pyusr/issue_707/fresh-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpkogs1xa_
  cwd: /STLABBA/tmp/pip-install-wkxb5lfo/ibm-db_651e20ae7f8b4f6ab0c297ed2ce9111f
  Building wheel for ibm-db (pyproject.toml) ... error
  ERROR: Failed building wheel for ibm-db
Failed to build ibm-db
ERROR: Could not build wheels for ibm-db, which is required to install pyproject.toml-based projects
```

**Comment by amukherjee28** [comment] 2022-04-07 07:13
@kenjaninja I was able to reproduce the issue after updating the python version to 3.9 in my ZOS machine.

Unfortunately this issue is something that all pip packages is having that contains pyproject.toml file. This is not limited to ibm_db package along and can be seen with any package available in pip that uses pyproject.toml file.

I did some research and looks like many people are facing this issue and unfortunately I do not have a immediate resolution to this.

Once I have a resolution on this I will update, Till then may I suggest you to use the source code for installation.

```python setup.py install``` mechanism for now.

Thanks.

**Comment by amukherjee28** [comment] 2022-04-19 11:05
I have the following update for this particular issue.
This works for me and I will update document for the same.

Please try the below solution and let me know if it works for you.

```
Package installation was tested with IBM Python versions 3.8, 3.9 and 3.10 and here is the working solution for all those versions. For each version an isolated virtual environment was created, where ibm_db package was installed and tested.

To install the package ibm_db it is necessary at first to install the build dependency package - wheel:
pip3 install wheel
Install ibm_db with the pip flag --no-build-isolation:
pip3 install ibm_db --no-build-isolation
[_Python < 3.1_] Need to remove tag and set execute permission of the installed library ibm_db.so*:
chtag -r <python_dir>/lib/python/site-packages/ibm_db*.so*
chmod +x <python_dir>/lib/python/site-packages/ibm_db*.so*
```

Thanks

**Comment by amukherjee28** [comment] 2022-05-04 07:25
Did the above help resolve the issue?

**Comment by kenjaninja** [comment] 2022-05-04 17:20
yes, it resolved the issue.

**Closed** 2022-05-05 22:52 UTC
Labels: waiting for response

**Comment by MRabast** [comment] 2022-05-30 17:34
I had same errors and used 
**CPPFLAGS=-I/usr/lpp/python39/v3r9/pyz/include/python3.9**
to get the header files included.

Furthermore I had to
**chtag -r**  /WWW/aaaa/python/lib/python3.9/site-packages/ibm_db.so
**chmod 755**  /WWW/aaaaa/python/lib/python3.9/site-packages/ibm_db.so
to solve this:
ImportError: CEE3512S An HFS load of module /WWW/aaaaa/python/lib/python3.9/site-packages/ibm_db.so failed. The system return code was 0000000111; the reason code was EF076015.
