### ISSUE TITLE
pip install ibm_db==3.0.4 failed

### ISSUE THREAD

**Issue by caixiangibm** [ibmdb/python-ibmdb#758] opened 2022-06-20 07:11 UTC
- Operating System Name: Red Hat Enterprise Linux release 8.5 (Ootpa)
- db2level output from clidriver if in use:
- Target Db2 Server Version:
- Python Version: Python 3.8.8
- ibm_db version:
- For non-Windows, output of below commands:
  uname Linux
  uname -m x86_64
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

Steps to Reproduce:

1. Tried to install ibm_db 3.0.4 on red hat 8.5 or ubi8 Operating System, but failed with error - ERROR: Could not find a version that satisfies the requirement ibm_db==3.0.4 (from versions: 0.2.0, 0.2.6, 0.2.7, 0.2.9, 0.2.9.1, 0.3.0, 0.4.0, 0.4.1, 0.6.0, 0.7.0, 0.7.2, 0.7.2.1, 0.7.2.5, 0.8.0, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.4.1, 2.0.5, 2.0.5.1, 2.0.6.1, 2.0.7, 2.0.8a0, 2.0.8, 2.0.9, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1, 3.1.2)
ERROR: No matching distribution found for ibm_db==3.0.4
The same install command line worked just several days ago, around Jun 16, 2022, but the same command failed today on Jun 20.
Even tried pip install ibm_db==3.1.1 and got the same failure

2. Install command output
```
# pip install ibm_db==3.0.4
Collecting ibm_db==3.0.4
  Downloading ibm_db-3.0.4.tar.gz (796 kB)
     |████████████████████████████████| 796 kB 1.4 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_c6lt8l/ibm-db_d86c90b57f98497a8991937b830fb894/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_c6lt8l/ibm-db_d86c90b57f98497a8991937b830fb894/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_1at0a8t
         cwd: /tmp/pip-install-u_c6lt8l/ibm-db_d86c90b57f98497a8991937b830fb894/
    Complete output (19 lines):
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_c6lt8l/ibm-db_d86c90b57f98497a8991937b830fb894/setup.py", line 240, in <module>
        file_stream = BytesIO(request.urlopen(url, context=context).read())
      File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/dc/7c/26c1eb0ce78689a6a6775337b43f498f8e901790ec0bafd6f24e2ef594af/ibm_db-3.0.4.tar.gz#sha256=2c6a806eb5071eacca5ddea0f0e4b8ad13594b1ba24dd57f00ea88708df289b3 (from https://pypi.org/simple/ibm-db/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement ibm_db==3.0.4 (from versions: 0.2.0, 0.2.6, 0.2.7, 0.2.9, 0.2.9.1, 0.3.0, 0.4.0, 0.4.1, 0.6.0, 0.7.0, 0.7.2, 0.7.2.1, 0.7.2.5, 0.8.0, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.4.1, 2.0.5, 2.0.5.1, 2.0.6.1, 2.0.7, 2.0.8a0, 2.0.8, 2.0.9, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1, 3.1.2)
ERROR: No matching distribution found for ibm_db==3.0.4 
```

**Comment by venkataramanam** [comment] 2022-06-20 11:23
This file https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz is missing. Looks like we will need to wait for those files to be available back again.

**Comment by bimalkjha** [comment] 2022-06-20 15:16
Issue was due to migration of the hosting service to new env yesterday by IBM. The issue is fixed now. Thanks.

**Closed by bimalkjha** 2022-06-20 15:16 UTC
