### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by justinplatz** [ibmdb/python-ibmdb#366] opened 2019-01-22 13:55 UTC
Simply doesnt work and I have followed all of the tips and hints. I am running latest version of Python (3.7+) and latest Mac OS (10.14+). Please fix this package so IBMers like myself can use this!

**Comment by SabaKauser** [comment] 2019-01-23 03:50
Can you do the following:
 otool -L ibm_db.cpython-37m-darwin.so
------------------------
ibm_db.cpython-37m-darwin.so:
        **libdb2.dylib** (compatibility version 0.0.0, current version 0.0.0)  ==> **library path is libdb2.dyib**
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)

Then run install name tool to change old path i.e libdb2.dylib to new path as:
install_name_tool -change libdb2.dylib @loader_path/clidriver/lib/libdb2.dylib ibm_db.cpython-37m-darwin.so

**Comment by saaratstaples** [comment] 2019-01-24 19:59
Two issues with this:
# SSL: CERTIFICATE_VERIFY_FAILED error on downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
# CHANGES, LICENSE, and README.md files are installed in /usr/local which is not writeable as a non-root user. This breaks brew-installed python installed in /usr/local/Cellar since MacOS El Capitan (v10.11) does not allow non-root writes to /usr/local. Brew highly recommends installing as non-root user.

**Comment by kadler** [comment] 2019-01-24 20:24
@saaratstaples 

The issue is the same as #365 and is already fixed in master, though not available on PyPI yet. In the mean time, you can [download](https://github.com/ibmdb/python-ibmdb/archive/master.zip) and unzip the latest code, then run `pip install .` from the unzipped directory.

The second issue, I think the issue is in setup.py on these lines: https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/setup.py#L225-L227 I'm pretty sure I have some changes there that I was working on. I'll see if I can find it.

**Comment by saaratstaples** [comment] 2019-01-24 20:41
@kadler - Thank you. Glad to hear that is fixed. That's what I did. I also set `data_files = []` to avoid the permissions issue when installing locally. I wasn't sure how to relocate those files into Cellar-based folders.

**Comment by SabaKauser** [comment] 2019-02-25 09:27
Fixed in https://github.com/ibmdb/python-ibmdb/pull/377

**Closed by SabaKauser** 2019-02-25 09:27 UTC
