### ISSUE TITLE
Query error when column name contain "Ñ" character

### ISSUE THREAD

**Issue by carlos-merida** [ibmdb/python-ibmdb#439] opened 2019-11-06 10:01 UTC
Hello,

I get query error when the query string contain "Ñ" chars. I cannot avoid this because the "Ñ" is part of column name.

When I run the same query from python in windows this work fine.

This is a query example:

...
conn = ibm_db.connect(connection_string, "", "")
if conn:
    print("Connected to an uncataloged database")
else:
    conn = ibm_db.connect(database, user, password)
    print("Connected to a local or cataloged database")
sql = "SELECT aÑo FROM tablename WHERE id=?"
stmt = ibm_db.prepare(conn, sql, {ibm_db.SQL_ATTR_CURSOR_TYPE: ibm_db.SQL_CURSOR_STATIC})
ibm_db.bind_param(stmt, 1, 1)
result = ibm_db.execute(stmt)
row = ibm_db.fetch_tuple(stmt)
while ( row ):
    row = ibm_db.fetch_tuple(stmt)
...

The ibm_db.client_info(conn) result in Windows is:

DRIVER_NAME: string(10) "DB2CLI.DLL"
DRIVER_VER: string(10) "11.01.0303"
DATA_SOURCE_NAME: string(9) "XXXXXXXX"
DRIVER_ODBC_VER: string(5) "03.51"
ODBC_VER: string(10) "03.01.0000"
ODBC_SQL_CONFORMANCE: string(8) "EXTENDED"
APPL_CODEPAGE: int(1252)
CONN_CODEPAGE: int(1208)

And the result on IBM i is:

DRIVER_NAME: string(13) "QSQCLI.SRVPGM"
DRIVER_VER: string(5) "07020"          
DATA_SOURCE_NAME: string(9) "XXXXXXXX"
DRIVER_ODBC_VER: string(4) "3.00"      
ODBC_VER: string(0) ""                 
ODBC_SQL_CONFORMANCE: string(4) "CORE" 
APPL_CODEPAGE: int(1208)               
CONN_CODEPAGE: int(1208)               

I'm very appreciate your help.

Regards.

Carlos.

**Comment by kadler** [comment] 2019-11-06 16:42
What is the error you get when run on IBM i?

**Comment by kadler** [comment] 2019-11-06 16:43
Can you also give the `DSPFD` and `DSPFFD` for the tables?

**Comment by carlos-merida** [comment] 2019-11-07 07:53
I find the problem.

If I try this query:

sql = "SELECT emp.aÑo, emp.* FROM NOMINAS.WEMPRTHH emp"

on ibm i I get this error:

Exception: El calificador de columna o tabla EMP no está definido. SQLSTATE=42703 SQLCODE=-5001

But if I add an extra whitespace to the end of query:

sql = "SELECT emp.aÑo, emp.* FROM NOMINAS.WEMPRTHH emp "

it work fine.

I think the "prepare" function is computed bad the length of the query string when this contain "special chars".

**Comment by SabaKauser** [comment] 2019-11-07 08:22
I don't think prepare function is computing bad length, otherwise, you should have seen partial table name in error message.

**Comment by carlos-merida** [comment] 2019-11-07 08:33
> I don't think prepare function is computing bad length, otherwise, you should have seen partial table name in error message.

Not, the query string is correct, the problem is when it is run on IBM i, there the query run like "SELECT emp.aÑo, emp.* FROM NOMINAS.WEMPRTHH em", and this is the explanation of this exception message.

**Comment by SabaKauser** [comment] 2020-02-03 05:02
Is this resolved?

**Comment by SabaKauser** [comment] 2020-02-19 05:26
can you confirm if you need more assistance with this?

**Comment by carlosmerida** [comment] 2020-02-24 14:59
Not, it's not resolved.

**Comment by carlosmerida** [comment] 2020-02-24 15:02
I get another similar issue when I try this single query "select * from table" and some column name have "Ñ" char include:

df = pd.read_sql(query, con)

Response:

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py in __get_description(self)
   1035                 column_desc.append(ibm_db.field_name(self.stmt_handler,
-> 1036                                                           column_index))
   1037                 type = ibm_db.field_type(self.stmt_handler, column_index)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Error                                     Traceback (most recent call last)
<ipython-input-77-24c7248c7697> in <module>
----> 1 df = pd.read_sql(query, con)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
    410             coerce_float=coerce_float,
    411             parse_dates=parse_dates,
--> 412             chunksize=chunksize,
    413         )
    414 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py in read_query(self, sql, index_col, coerce_float, params, parse_dates, chunksize)
   1632         args = _convert_params(sql, params)
   1633         cursor = self.execute(*args)
-> 1634         columns = [col_desc[0] for col_desc in cursor.description]
   1635 
   1636         if chunksize is not None:

C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py in __get_description(self)
   1080         except Exception as inst:
   1081             self.messages.append(_get_exception(inst))
-> 1082             raise self.messages[len(self.messages) - 1]
   1083 
   1084         return self.__description

Error: ibm_db_dbi::Error: UnicodeDecodeError('ascii', b'A\xd1O', 1, 2, 'ordinal not in range(128)')

**Comment by carlos-merida** [comment] 2020-02-24 16:00
Not, it's not resolved.

**Comment by carlos-merida** [comment] 2020-02-24 16:00
df = pd.read_sql(query, con)

Response:

UnicodeDecodeError Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py in __get_description(self)
1035 column_desc.append(ibm_db.field_name(self.stmt_handler,
-> 1036 column_index))
1037 type = ibm_db.field_type(self.stmt_handler, column_index)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Error Traceback (most recent call last)
in
----> 1 df = pd.read_sql(query, con)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
410 coerce_float=coerce_float,
411 parse_dates=parse_dates,
--> 412 chunksize=chunksize,
413 )
414

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py in read_query(self, sql, index_col, coerce_float, params, parse_dates, chunksize)
1632 args = _convert_params(sql, params)
1633 cursor = self.execute(*args)
-> 1634 columns = [col_desc[0] for col_desc in cursor.description]
1635
1636 if chunksize is not None:

C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py in __get_description(self)
1080 except Exception as inst:
1081 self.messages.append(_get_exception(inst))
-> 1082 raise self.messages[len(self.messages) - 1]
1083
1084 return self.__description

Error: ibm_db_dbi::Error: UnicodeDecodeError('ascii', b'A\xd1O', 1, 2, 'ordinal not in range(128)')

**Comment by kadler** [comment] 2020-02-24 17:20
I was able to reproduce this. This seems to be a bug in QSQCLI handling of statement text coming in as UTF-8. It converts the text from UTF-8 to job CCSID, but uses the UTF-8 length instead of the converted length since it assumes a one-to-one byte mapping, which is not always the case with UTF-8.

You can work around this by padding the end with blanks for each extra byte of UTF-8 data.

```python
import os
import subprocess
import ibm_db_dbi

# Set job to CCSID 284 (Spanish)
proc = subprocess.run(['getjobid', '-s', str(os.getpid())], stdout=subprocess.PIPE)   
jobname = proc.stdout.decode().rstrip()
proc = subprocess.run(['system', 'CHGJOB {} CCSID(284)'.format(jobname)], stdout=subprocess.PIPE)


conn = ibm_db_dbi.connect()
cur = conn.cursor()
cur.execute('create table birthday(aÑo decimal(4,0))    ')

query = 'select aÑo from birthday'
try:
    cur.execute(query)
    print('"{}" succeeded'.format(query))
except ibm_db_dbi.ProgrammingError as e:
    print('"{}" failed'.format(query))
    print(e)

try:
    query = query + ' '
    cur.execute(query)
    print('"{}" succeeded'.format(query))
except ibm_db_dbi.ProgrammingError as e:
    print('"{}" failed'.format(query))
    print(e)
```

This gives me:
```
"select aÑo from birthday" failed
ibm_db_dbi::ProgrammingError: BIRTHDA in KADLER type *FILE not found. SQLSTATE=42704 SQLCODE=-204
"select aÑo from birthday " succeeded
```

**Comment by carlos-merida** [comment] 2020-02-24 21:36
> I was able to reproduce this. This seems to be a bug in QSQCLI handling of statement text coming in as UTF-8. It converts the text from UTF-8 to job CCSID, but uses the UTF-8 length instead of the converted length since it assumes a one-to-one byte mapping, which is not always the case with UTF-8.
> 
> You can work around this by padding the end with blanks for each extra byte of UTF-8 data.
> 
> ```python
> import os
> import subprocess
> import ibm_db_dbi
> 
> # Set job to CCSID 284 (Spanish)
> proc = subprocess.run(['getjobid', '-s', str(os.getpid())], stdout=subprocess.PIPE)   
> jobname = proc.stdout.decode().rstrip()
> proc = subprocess.run(['system', 'CHGJOB {} CCSID(284)'.format(jobname)], stdout=subprocess.PIPE)
> 
> 
> conn = ibm_db_dbi.connect()
> cur = conn.cursor()
> cur.execute('create table birthday(aÑo decimal(4,0))    ')
> 
> query = 'select aÑo from birthday'
> try:
>     cur.execute(query)
>     print('"{}" succeeded'.format(query))
> except ibm_db_dbi.ProgrammingError as e:
>     print('"{}" failed'.format(query))
>     print(e)
> 
> try:
>     query = query + ' '
>     cur.execute(query)
>     print('"{}" succeeded'.format(query))
> except ibm_db_dbi.ProgrammingError as e:
>     print('"{}" failed'.format(query))
>     print(e)
> ```
> 
> This gives me:
> 
> ```
> "select aÑo from birthday" failed
> ibm_db_dbi::ProgrammingError: BIRTHDA in KADLER type *FILE not found. SQLSTATE=42704 SQLCODE=-204
> "select aÑo from birthday " succeeded
> ```

Yes Kadler, I have already used that provisional solution.

**Comment by carlos-merida** [comment] 2020-02-24 22:40
> I was able to reproduce this. This seems to be a bug in QSQCLI handling of statement text coming in as UTF-8. It converts the text from UTF-8 to job CCSID, but uses the UTF-8 length instead of the converted length since it assumes a one-to-one byte mapping, which is not always the case with UTF-8.
> 
> You can work around this by padding the end with blanks for each extra byte of UTF-8 data.
> 
> ```python
> import os
> import subprocess
> import ibm_db_dbi
> 
> # Set job to CCSID 284 (Spanish)
> proc = subprocess.run(['getjobid', '-s', str(os.getpid())], stdout=subprocess.PIPE)   
> jobname = proc.stdout.decode().rstrip()
> proc = subprocess.run(['system', 'CHGJOB {} CCSID(284)'.format(jobname)], stdout=subprocess.PIPE)
> 
> 
> conn = ibm_db_dbi.connect()
> cur = conn.cursor()
> cur.execute('create table birthday(aÑo decimal(4,0))    ')
> 
> query = 'select aÑo from birthday'
> try:
>     cur.execute(query)
>     print('"{}" succeeded'.format(query))
> except ibm_db_dbi.ProgrammingError as e:
>     print('"{}" failed'.format(query))
>     print(e)
> 
> try:
>     query = query + ' '
>     cur.execute(query)
>     print('"{}" succeeded'.format(query))
> except ibm_db_dbi.ProgrammingError as e:
>     print('"{}" failed'.format(query))
>     print(e)
> ```
> 
> This gives me:
> 
> ```
> "select aÑo from birthday" failed
> ibm_db_dbi::ProgrammingError: BIRTHDA in KADLER type *FILE not found. SQLSTATE=42704 SQLCODE=-204
> "select aÑo from birthday " succeeded
> ```

How can I change the CCSID???

I try your code:

# Set job to CCSID 284 (Spanish)
proc = subprocess.run(['getjobid', '-s', str(os.getpid())], stdout=subprocess.PIPE)   
jobname = proc.stdout.decode().rstrip()
proc = subprocess.run(['system', 'CHGJOB {} CCSID(284)'.format(jobname)], stdout=subprocess.PIPE)

but I get error in first line:

FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

I'm trying in Anaconda enviroment in Windows.

**Comment by kadler** [comment] 2020-02-25 16:14
Running `CHGJOB` will only work when run _on_ IBM i. If you're running on Windows, you'd have to do it through a Db2 Connect option or something.

You seem to have two problems in this issue, though both due to the non-ASCII character in the column name. One is on Windows, which uses the Db2 Connect driver and code here and one on IBM i, which uses IBM i CLI and my fork.

To keep things understandable, I would suggest you close this issue out and re-open it on my fork https://github.com/kadler/python-ibmdb/issues

Then, open another issue here for the Windows issue referenced in https://github.com/ibmdb/python-ibmdb/issues/439#issuecomment-590402465. You can easily do that by clicking on the ... menu on the comment and choosing "Reference in new issue"
![image](https://user-images.githubusercontent.com/7004340/75266061-71e9c980-57b7-11ea-8560-365716d5f391.png)

**Closed** 2020-02-25 22:18 UTC
