### ISSUE TITLE
Installation fails with urllib.error.HTTPError: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by hemlatabhatt** [ibmdb/python-ibmdb#354] opened 2018-11-12 06:09 UTC
_From @klada on November 6, 2018 9:2_

When installing `ibm-db` through `pip install` I get the following error:

```
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jrmourne/ibm-db/setup.py", line 164, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

It seems that the setup.py script depends on the availability of public.dhe.ibm.com. Please move the CLI drivers to a more reliable server or serve them through Github.

_Copied from original issue: ibmdb/python-ibmdb-django#36_

**Comment by kadler** [comment] 2018-11-12 16:52
Seems to be a duplicate of #350

**Comment by SabaKauser** [comment] 2018-11-30 04:54
closing. We are working on alternate solution to see if this can be avoided in future.

**Closed by SabaKauser** 2018-11-30 04:54 UTC
