### ISSUE TITLE
Execute many fails for larger number of records (600K records)

### ISSUE THREAD

**Issue by ba4ekiko1** [ibmdb/python-ibmdb#424] opened 2019-09-16 11:29 UTC
Hi, i am trying to insert some data from dataframe to a table and the below code works perfectly if i want to insert 100, 1 000 or even 100 000 records. However it fails if i try to insert all the dataframe  (close to 600 000 records).

```
num_cols = len(coverage.columns)
cols = ','.join(list(coverage.columns))
qmarks = '?' * num_cols
placeholders = ','.join([qmarks[i] for i in range(num_cols)])


tuple_of_tuples = tuple([tuple(x) for x in coverage.values])

sql1 = "TRUNCATE TABLE IZ_GSI.CSM_O_CUS_SEGMENTATION_MOD IMMEDIATE"
sql2= f"INSERT INTO IZ_GSI.CSM_O_CUS_SEGMENTATION_MOD VALUES({placeholders})"

stmt = ibm_db.prepare(conn, sql1)

try:
    ibm_db.execute(stmt)
except:
    print('Error')
else:
    print('Truncation complete')
    
    
try:
    stmt = ibm_db.prepare(conn, sql2)
    ibm_db.execute_many(stmt,tuple_of_tuples)
except:
    print("Transaction couldn't be completed:" , ibm_db.stmt_errormsg())
else: print("Load complete.")
```

The other strange thing is that i get black exception message so i am not sure what the issue is:
![image](https://user-images.githubusercontent.com/25074675/64954463-b717e000-d896-11e9-99d2-7218098b5d2a.png)

**Comment by SabaKauser** [comment] 2019-09-18 12:55
Let me try to reproduce. I will get back to you.

**Comment by SabaKauser** [comment] 2019-09-26 09:24
I tried with 2 columns and inserted 610107 records. I am unable to reproduce. Can you share your table definition.

**Comment by ba4ekiko1** [comment] 2019-09-26 10:29
Hi, sure
[table_structure.xlsx](https://github.com/ibmdb/python-ibmdb/files/3657320/table_structure.xlsx)

**Comment by SabaKauser** [comment] 2019-10-03 08:54
Thank you.
I am able to insert the rows successfully using your table definition.

I inserted as many as 8 lac rows.
db2 "select count(*) from tabmany"

1
-----------
     800000

  1 record(s) selected.

```python

data={'ID':['11111111111111111111111111111111111111111111111111111111111111111111111111111111','22222222222222222222222222222222222222222222222222222222222222222222222222222222','33333333333333333333333333333333333333333333333333333333333333333333333333333333','44444444444444444444444444444444444444444444444444444444444444444444444444444444'],\
          'BRANCH':['BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBR','BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBR','BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBR','BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBR'],\
	      'COVCNT':[1,2,3,4],\
          'COVEXECINTERNETID':['COVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVID','COVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVID','COVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVID','COVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVIDCOVID'],\
          'COVEXECNAME':['COVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNM','COVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNM','COVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNM','COVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNM'],\
		  'COVNAME':['COVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNM','COVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNM','COVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNM','COVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNMCOVNM'],\
          'COVTYPEID':['COVTYPEID','COVTYPEID','COVTYPEID','COVTYPEID'],\
          'CUSTCNT':[1,2,3,4],\
          'REVENUE_1H_2019':[100,200,300,400],\
          'SIGNINGS_1H_2019':[100,200,300,400],\
          'ISSUINGCOUNTRYNO':['111','222','333','444'],\
          'NEXTCOVNAME':['NEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTC',\
                         'NEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTC',\
                         'NEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTC',\
                         'NEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTCNEXTC'],\
          'NEXTCOVTYPEID':['NEXTCOVID', 'NEXTCOVID','NEXTCOVID','NEXTCOVID'],\
          'NEXTSEGMENT':['NXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSG','NXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSG',\
                         'NXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSG','NXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSGNXTSG'],\
          'REVENUE_2018':[100,200,300,400],'SIGNINGS_2018':[100,200,300,400],'REVENUE_1H_2018':[100,200,300,400],'SIGNINGS_1H_2018':[100,200,300,400],\
          'REPORTINGCOUNTRYNO':['111','222','333','444'],\
          'REPORTINGMARKETCD':['11','22','33','44'],\
          'REPORTINGMARKETNAME':['RPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMN',\
                                 'RPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMN',\
                                 'RPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMN',\
                                 'RPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMNRPTMN'],\
          'SEGMENT':['SEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMT','SEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMT',\
                     'SEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMT','SEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMTSEGMT'],\
          'SIAIND':['111','222','333','444'],\
          'SUBBRANCH':['SBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCH',\
                       'SBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCH',\
                       'SBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCH',\
                       'SBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCHSBRCH'],\
          'TOTID':['TOTID1111','TOTID2222','TOTID3333','TOTID4444'],\
          'TOTNAME':['TOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOT',\
                     'TOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOT',\
                     'TOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOT',\
                     'TOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOTTOTNAMETOT'],\
          'GEO':['GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12',\
                 'GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12',\
                 'GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12',\
                 'GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12GEO12'],\
          'DOMINANTGEOSEGMENT':['DOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMT',\
                                'DOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMT',\
                                'DOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMT',\
                                'DOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMTDOMGEOSGMT'],\
          'NEXTDOMINANTGEOSEGMENT':['NXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOS',\
                                    'NXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOS',\
                                    'NXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOS',\
                                    'NXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOSNXTDOMGEOS'],\
          'DOMINANTWWSEGMENT':['DOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMT',\
                               'DOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMT',\
                               'DOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMT',\
                               'DOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMTDOMWWSEGMT'],\
          'NEXTDOMINANTWWSEGMENT':['NXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSG',\
                                   'NXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSG',\
                                   'NXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSG',\
                                   'NXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSGNXTDOMWWSG'],\
          'REQUEST_ID':['REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1',\
                        'REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1',\
                        'REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1',\
                        'REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1REQUESTID1'],\
          'REQUEST_REASON':['REQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSN',\
                            'REQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSN',\
                            'REQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSN',\
                            'REQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSNREQUESTRSN'],\
          'LASTUPDATETIME':['LSTUPDTIMELSTUPDTIMELSTUPDTIME','LSTUPDTIMELSTUPDTIMELSTUPDTIME','LSTUPDTIMELSTUPDTIMELSTUPDTIME','LSTUPDTIMELSTUPDTIMELSTUPDTIME']\
          }
    df1=pd.DataFrame(data)
    tuple_of_tuples = tuple([tuple(x) for x in df1.values] )
    params = tuple_of_tuples * 200000
    #print(tuple_tuples)
    #print(params)
    stmt_insert = ibm_db.prepare(conn, insert)
    ibm_db.execute_many(stmt_insert, params)
    row_count = ibm_db.num_rows(stmt_insert)
    print(row_count)
```

Tried to insert the data to max column lengths.

**Comment by SabaKauser** [comment] 2019-11-13 02:27
should I keep this open?

**Comment by SabaKauser** [comment] 2019-12-06 04:49
closing as I am unable to reproduce the problem. If you have details on how I can reproduce, please re-open

**Closed by SabaKauser** 2019-12-06 04:49 UTC
