### ISSUE TITLE
import error of ibm_db on M1

### ISSUE THREAD

**Issue by niju3063** [ibmdb/python-ibmdb#730] opened 2022-03-15 16:11 UTC
[import ibm_db

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ibm_db.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_SQLAllocHandle']()

does any solution exists for above query

**Comment by bimalkjha** [comment] 2022-03-16 06:03
@niju3063 Its a duplicate of closed issue #726 . Please check that for solution. Thanks.

**Closed by bimalkjha** 2022-03-16 06:03 UTC
