### ISSUE TITLE
Slow DB2 connection when running in Docker on Mac

### ISSUE THREAD

**Issue by ThomasMatthewFletcher** [ibmdb/python-ibmdb#737] opened 2022-03-29 10:26 UTC
We are migrating from an  IBM Db2 on Cloud single server DB2 instance, to a HADR instance.
Connecting to the current instance takes only a few seconds, but connecting to the new instance takes over 2 minutes.

This only appears to be the case on our Mac development machines and doesn't occur in our production environment.

- Operating System Name: macOS Monterey (12.2.1), running in Docker image python:3.10
- db2level output from clidriver if in use:
```
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11054" with level identifier "0605010F".
Informational tokens are "DB2 v11.5.4.0", "s2006161200", "DYN2006161200MAC",
and Fix Pack "0".
Product is installed at "/Applications/dsdriver".
```
- Target Db2 Server Version:
- Python Version: 3.10
- ibm_db version: 3.1.1
- For non-Windows, output of below commands:
  uname: Linux
  uname -m: x86_64
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Test script:
```
import ibm_db
from time import time

db_configs = [
    {
        'host': 'e0f165e8-9436-4858-ad52-fd7d57511c0f.bv7c3o6d0vfhru3npds0.databases.appdomain.cloud',
        'port': 31810,
        'name': 'BLUDB',
        'username': <REDACTED>,
        'password': <REDACTED>,
        'cert': 'src/db2.crt'
    },
    {
        'host': 'a5315f82-3f56-4aa8-9f23-1ebbb43de337.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud',
        'port': 31255,
        'name': 'BLUDB',
        'username': <REDACTED>,
        'password': <REDACTED>,
        'cert': 'src/db1.crt'
    }
]


def db_connection_test(config):
    print(f'Begin connecting to {config["host"]}')
    start = time()

    conn = ibm_db.pconnect(
        f'DATABASE={config["name"]};'
        f'HOSTNAME={config["host"]};'
        f'PORT={config["port"]};'
        f'PROTOCOL=TCPIP;'
        f'UID={config["username"]};'
        f'PWD={config["password"]};'
        f'SSLServerCertificate={config["cert"]};'
        f'SECURITY=SSL;',
        '',
        ''
    )

    end = time()

    if conn:
        print(f'Connected to {config["host"]}')
    else:
        print(f'Failed to connect to {config["host"]}')


    duration = end - start
    print(f'Duration: {duration:.2f}s')


db_connection_test(db_configs[0])
db_connection_test(db_configs[1])
```

Output:
```
Begin connecting to e0f165e8-9436-4858-ad52-fd7d57511c0f.bv7c3o6d0vfhru3npds0.databases.appdomain.cloud
Connected to e0f165e8-9436-4858-ad52-fd7d57511c0f.bv7c3o6d0vfhru3npds0.databases.appdomain.cloud
Duration: 5.61s
Begin connecting to a5315f82-3f56-4aa8-9f23-1ebbb43de337.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud
Connected to a5315f82-3f56-4aa8-9f23-1ebbb43de337.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud
Duration: 122.89s
```

**Comment by amukherjee28** [comment] 2022-03-29 10:49
@ThomasMatthewFletcher This is something that has to be verified from the server end rather the python driver.
Ideally the delay in response could be due to multiple reason primary among them could be the latency in the server connection time.
A similar issue was seen before
https://github.com/ibmdb/python-ibmdb/issues/630

collection performance trace is one option to verify.

Could you please collect the performance trace for both the cases as told in the above mentioned issue and send it.
We can check where the latency is created.

**Comment by ThomasMatthewFletcher** [comment] 2022-03-29 13:27
Thanks for your quick response, I've attached both perf.out files:
[perf.a5315f82.out.txt](https://github.com/ibmdb/python-ibmdb/files/8371806/perf.a5315f82.out.txt)
[perf.e0f165e8.out.txt](https://github.com/ibmdb/python-ibmdb/files/8371807/perf.e0f165e8.out.txt)

**Comment by amukherjee28** [comment] 2022-03-31 09:05
Hi @ThomasMatthewFletcher 

I went thought the trace file and analyzed them.

In the file : perf.e0f165e8.out.txt

```
1          0.000031000 sqljrUpdateDBDirDisk
1          0.039561000 sqleuBindParametersForServerActivation 
1          3.168102000 SQLDriverConnect2
1          0.000008000 CLI_utlTraceKeywordList
1          3.168785000 SQLDriverConnectW
```

The connect time is 3.16 seconds

However in the second case
In the file : perf.a5315f82.out.txt
```
1          0.000078000 sqljcGetApplicationIdentifier
1          0.000009000 sqlzercci
1          0.034536000 sqleuBindParametersForServerActivation
1        122.528429000 SQLDriverConnect2
1          0.000010000 CLI_utlTraceKeywordList
1        122.529033000 SQLDriverConnectW
```

The same connect time is 122 seconds.

It is this that is causing the delay. The server itself is getting a delay in connection and ibm_db driver is doing nothing from its side to cause this.

This is something that is purely from the server side. You might want to check with the server team once what is causing the latency.

Thanks

**Comment by bimalkjha** [comment] 2022-03-31 10:43
@ThomasMatthewFletcher We see that you have installed dsdriver v11.5.4 as /Applications/dsdriver but your IBM_DB_HOME is empty. Please confirm, have you set this env var or you are able to see clidriver under site-packages directory. Share the output of `site-packages/clidriver/bin/db2level`. 
It seems, this mac has problem is resolving the hostname. i.e. getting ip address from hostname. There might be some bug with dsdriver v11.5.4.0, so better to use [this clidriver](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz) which is of v11.5.6.0 and try. Thanks.

**Comment by ThomasMatthewFletcher** [comment] 2022-03-31 10:47
Thanks @amukherjee28 and @bimalkjha
I followed the instructions in [Example 1 on db2trc docs](https://www.ibm.com/docs/en/db2/11.5?topic=commands-db2trc-trace) to create a dump.
[db2trc.flw.txt](https://github.com/ibmdb/python-ibmdb/files/8388569/db2trc.flw.txt)

When I raised the issue I was a little confused about which driver output was needed, sorry.
This is the output of running `db2level` inside of the Docker container:
```
root@7eeb4fb7c15e:/usr/local/lib/python3.10/site-packages/clidriver/bin# ./db2level
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11056" with level identifier "0607010F".
Informational tokens are "DB2 v11.5.6.0", "special_13806",
"DYN2201171140AMD64_13806", and Fix Pack "0".
Product is installed at "..".
```

I have previously tried resolving the hostname `a5315f82-3f56-4aa8-9f23-1ebbb43de337.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud` to `169.48.136.34` and connecting using this, but had a similar delay.

Let me know if there's anything else you need me to provide

**Comment by ThomasMatthewFletcher** [comment] 2022-04-05 09:14
Hi @bimalkjha, is there anything else you need to help me with this issue? Thank you

**Comment by amukherjee28** [comment] 2022-04-07 07:23
@ThomasMatthewFletcher 

We analyzed the FLW trace file that you have send and looks like there is still hostname resolution logic triggered which is consuming some time as seen in the traces.

Can you use the IP address to connect to the HADR and then collect the traces.

Once you have the traces can you send across the following trace files

```
db2trc fmt trc.dmp trc.fmt
db2trc flw trc.dmp trc.flw
db2trc fmt -c trc.dmp trc.drda
db2trc fmt -cli trc.dmp trc.cli
```

Also could you send the same set of trace file after connecting using the complete hostname as well.

This will help us to check and compare the traces to see where the problem might be hapenning.

Thanks

**Comment by ThomasMatthewFletcher** [comment] 2022-04-07 13:09
I have taken these traces by connecting to a5315f82-3f56-4aa8-9f23-1ebbb43de337.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud

I then took the same traces by running nslookup on the above hostname and connecting directly to the first IP result which was 169.48.136.34

I saw similar connection times of around 2 minutes

Thank you for looking into this for us, please let me know if there's anything more I can do

[hostname.trc.cli.txt](https://github.com/ibmdb/python-ibmdb/files/8443044/hostname.trc.cli.txt)
[hostname.trc.drda.txt](https://github.com/ibmdb/python-ibmdb/files/8443045/hostname.trc.drda.txt)
[hostname.trc.flw.txt](https://github.com/ibmdb/python-ibmdb/files/8443046/hostname.trc.flw.txt)
[hostname.trc.fmt.txt](https://github.com/ibmdb/python-ibmdb/files/8443047/hostname.trc.fmt.txt)
[ip.trc.cli.txt](https://github.com/ibmdb/python-ibmdb/files/8443049/ip.trc.cli.txt)
[ip.trc.drda.txt](https://github.com/ibmdb/python-ibmdb/files/8443050/ip.trc.drda.txt)
[ip.trc.flw.txt](https://github.com/ibmdb/python-ibmdb/files/8443051/ip.trc.flw.txt)
[ip.trc.fmt.txt](https://github.com/ibmdb/python-ibmdb/files/8443052/ip.trc.fmt.txt)
[nslookup.txt](https://github.com/ibmdb/python-ibmdb/files/8443057/nslookup.txt)

**Comment by amukherjee28** [comment] 2022-04-08 08:23
Thanks you for providing the details we asked for. We are looking into the trace file in details. Let us have some analysis on the same and we will get back with the details.

**Comment by ThomasMatthewFletcher** [comment] 2022-04-25 08:07
Hi @amukherjee28, is there any update to this?
Do I need to raise a support ticket with DB2?

**Comment by bimalkjha** [comment] 2022-04-26 21:46
@ThomasMatthewFletcher Problem is not with `a5315f82-3f56-4aa8-9f23-1ebbb43de337.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud` or `169.48.136.34`, but the problem is the wrong hostname `c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local`, port 55000 configured at HADR server.

In file hostname.trc.fmt.txt, we can see below list of servers are sent by the server to client:
```
4322	data DB2 UDB DRDA Communication Manager sqljcReceive fnc (3.3.54.3.0.1178)
	pid 10 tid 140000123623232 cpid -1 node -1 sec 8 nsec 82012000 probe 1178
	bytes 676

	RECEIVE BUFFER(AR):

            SECCHKRM RPYDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  0015D0420001000F 1219000611490000   ...B.........I..  ..}.............
  0010  000511A400                          .....             ...u.

            ACCRDBRM RPYDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  01E8D052000201E2 2201000611490000   ...R...."....I..  .Y}....S........
  0010  000C112EE2D8D3F1 F1F0F5F7000D002F   .............../  ....SQL11057....
  0020  D8E3C4E2D8D3E7F8 F6001C0035000611   ............5...  QTDSQLX86.......
  0030  9C04B80006119D04 B00006119E04B800   ................  ................
  0040  06191304B8000621 036255008C1912D6   .......!.bU.....  ...............O
  0050  D8836081F5F3F1F5 86F8F260F386F5F6   ..`........`....  Qc-a5315f82-3f56
  0060  60F48181F860F986 F2F360F185828282   `....`....`.....  -4aa8-9f23-1ebbb
  0070  F4F38485F3F3F760 9460F04B836081F5   .......`.`.K.`..  43de337-m-0.c-a5
  0080  F3F1F586F8F260F3 86F5F660F48181F8   ......`....`....  315f82-3f56-4aa8
  0090  60F986F2F360F185 828282F4F38485F3   `....`..........  -9f23-1ebbb43de3
  00A0  F3F760944BF7F8F6 F6F8F2F7F684F7F4   ..`.K...........  37-m.78668276d74
  00B0  81F481F28282F884 F6F483F681F8F182   ................  a4a2bb8d64c6a81b
  00C0  F2F2F0F3F54BA2A5 834B8393A4A2A385   .....K...K......  22035.svc.cluste
  00D0  994B939683819300 0621252435000C11   .K.......!%$5...  r.local.........
  00E0  A0F9F0C2C2C2C1F7 C200FF244E000624   ...........$N..$  .90BBBA7B...+...
  00F0  4C00020004244D00 06244F0001008C19   L....$M..$O.....  <.....(...!.....
  0100  12D6D8836081F5F3 F1F586F8F260F386   ....`........`..  .OQc-a5315f82-3f
  0110  F5F660F48181F860 F986F2F360F18582   ..`....`....`...  56-4aa8-9f23-1eb
  0120  8282F4F38485F3F3 F7609460F04B8360   .........`.`.K.`  bb43de337-m-0.c-
  0130  81F5F3F1F586F8F2 60F386F5F660F481   ........`....`..  a5315f82-3f56-4a
  0140  81F860F986F2F360 F185828282F4F384   ..`....`........  a8-9f23-1ebbb43d
  0150  85F3F3F760944BF7 F8F6F6F8F2F7F684   ....`.K.........  e337-m.78668276d
  0160  F7F481F481F28282 F884F6F483F681F8   ................  74a4a2bb8d64c6a8
  0170  F182F2F2F0F3F54B A2A5834B8393A4A2   .......K...K....  1b22035.svc.clus
  0180  A385994B93968381 930006244F000000   ...K.......$O...  ter.local...!...
  0190  5919127A1781F5F3 F1F586F8F260F386   Y..z.........`..  ...:.a5315f82-3f
  01A0  F5F660F48181F860 F986F2F360F18582   ..`....`....`...  56-4aa8-9f23-1eb
  01B0  8282F4F38485F3F3 F74B83F395F4F183   .........K......  bb43de337.c3n41c
  01C0  9484F09598959992 F3F9A4F9F8874B84   ..............K.  md0nqnrk39u98g.d
  01D0  81A3818281A285A2 4B81979784969481   ........K.......  atabases.appdoma
  01E0  89954B839396A484                    ..K.....          in.cloud
```
clidriver calls sqloPdbTcpIpGetAddrInfo() function to verify the hostname and store it. Below trace entries shows that sqloPdbTcpIpGetAddrInfo() takes 60 seconds to resolve the hostname of `c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local` and finally it fails with UNKNOWN HOST error.
```
4367	entry DB2 UDB oper system services sqloPdbTcpIpGetAddrInfo fnc (1.3.15.1270.0)
	pid 10 tid 140000123623232 cpid -1 node -1 sec 8 nsec 82035000

	bytes 160

	Data1 	(PD_TYPE_STRING,134) String:
	c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local
	Data2 	(PD_TYPE_STRING,0) String:
	Object not dumped: Address: 0x000000000089AFE6 Size: 0 Reason: Zero-length data
	Data3 	(PD_TYPE_UINT,2) unsigned integer:
	5

4368	data DB2 UDB oper system services sqloPdbTcpIpGetAddrInfo fnc (3.3.15.1270.0.5)
	pid 10 tid 140000123623232 cpid -1 node -1 sec 8 nsec 82035000 probe 5
	bytes 36

	Data1 	(PD_TYPE_UINT,4) unsigned integer:
	0
	Data2 	(PD_TYPE_UINT,4) unsigned integer:
	1
	Data3 	(PD_TYPE_UINT,4) unsigned integer:
	6

4369	data DB2 UDB oper system services sqloPdbTcpIpGetAddrInfo fnc (3.3.15.1270.0.10)
	pid 10 tid 140000123623232 cpid -1 node -1 sec 68 nsec 102039000 probe 10
	bytes 10

	Data1 	(PD_TYPE_SINT,2) signed integer:
	6

4370	exit DB2 UDB oper system services sqloPdbTcpIpGetAddrInfo fnc (2.3.15.1270.0)
	pid 10 tid 140000123623232 cpid -1 node -1 sec 68 nsec 102040000
	rc = 0xFFFFFFFD = -3
```
Similar pattern we notice in ip.trc.fmt.txt file where it takes 60 second to resolve the hostname `c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local`. Below server lists are sent by the server to client:
```
4251	data DB2 UDB DRDA Communication Manager sqljcReceive fnc (3.3.54.3.0.1178)
	pid 10 tid 140002787178304 cpid -1 node -1 sec 5 nsec 999828000 probe 1178
	bytes 676

	RECEIVE BUFFER(AR):

            SECCHKRM RPYDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  0015D0420001000F 1219000611490000   ...B.........I..  ..}.............
  0010  000511A400                          .....             ...u.

            ACCRDBRM RPYDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  01E8D052000201E2 2201000611490000   ...R...."....I..  .Y}....S........
  0010  000C112EE2D8D3F1 F1F0F5F7000D002F   .............../  ....SQL11057....
  0020  D8E3C4E2D8D3E7F8 F6001C0035000611   ............5...  QTDSQLX86.......
  0030  9C04B80006119D04 B00006119E04B800   ................  ................
  0040  06191304B8000621 036309008C1912D6   .......!.c......  ...............O
  0050  D8836081F5F3F1F5 86F8F260F386F5F6   ..`........`....  Qc-a5315f82-3f56
  0060  60F48181F860F986 F2F360F185828282   `....`....`.....  -4aa8-9f23-1ebbb
  0070  F4F38485F3F3F760 9460F04B836081F5   .......`.`.K.`..  43de337-m-0.c-a5
  0080  F3F1F586F8F260F3 86F5F660F48181F8   ......`....`....  315f82-3f56-4aa8
  0090  60F986F2F360F185 828282F4F38485F3   `....`..........  -9f23-1ebbb43de3
  00A0  F3F760944BF7F8F6 F6F8F2F7F684F7F4   ..`.K...........  37-m.78668276d74
  00B0  81F481F28282F884 F6F483F681F8F182   ................  a4a2bb8d64c6a81b
  00C0  F2F2F0F3F54BA2A5 834B8393A4A2A385   .....K...K......  22035.svc.cluste
  00D0  994B939683819300 0621252435000C11   .K.......!%$5...  r.local.........
  00E0  A0F9F0C2C2C2C1F7 C200FF244E000624   ...........$N..$  .90BBBA7B...+...
  00F0  4C00020004244D00 06244F0001008C19   L....$M..$O.....  <.....(...!.....
  0100  12D6D8836081F5F3 F1F586F8F260F386   ....`........`..  .OQc-a5315f82-3f
  0110  F5F660F48181F860 F986F2F360F18582   ..`....`....`...  56-4aa8-9f23-1eb
  0120  8282F4F38485F3F3 F7609460F04B8360   .........`.`.K.`  bb43de337-m-0.c-
  0130  81F5F3F1F586F8F2 60F386F5F660F481   ........`....`..  a5315f82-3f56-4a
  0140  81F860F986F2F360 F185828282F4F384   ..`....`........  a8-9f23-1ebbb43d
  0150  85F3F3F760944BF7 F8F6F6F8F2F7F684   ....`.K.........  e337-m.78668276d
  0160  F7F481F481F28282 F884F6F483F681F8   ................  74a4a2bb8d64c6a8
  0170  F182F2F2F0F3F54B A2A5834B8393A4A2   .......K...K....  1b22035.svc.clus
  0180  A385994B93968381 930006244F000000   ...K.......$O...  ter.local...!...
  0190  5919127A1781F5F3 F1F586F8F260F386   Y..z.........`..  ...:.a5315f82-3f
  01A0  F5F660F48181F860 F986F2F360F18582   ..`....`....`...  56-4aa8-9f23-1eb
  01B0  8282F4F38485F3F3 F74B83F395F4F183   .........K......  bb43de337.c3n41c
  01C0  9484F09598959992 F3F9A4F9F8874B84   ..............K.  md0nqnrk39u98g.d
  01D0  81A3818281A285A2 4B81979784969481   ........K.......  atabases.appdoma
  01E0  89954B839396A484                    ..K.....          in.cloud
  ```

So, problem is the invalid hostname configured at the server. Please contact your HADR server admin and tell to remove hostname `c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local` and port 55000 from the HARD setup. Thanks.

**Comment by bimalkjha** [comment] 2022-05-08 19:01
@ThomasMatthewFletcher Please let us know if you have corrected the hostname and issue is resolved so that we can close the ticket. Thanks.

**Comment by Earammak** [comment] 2022-06-16 08:56
@ThomasMatthewFletcher Can we have an update on this?

**Comment by bimalkjha** [comment] 2022-06-16 09:21
Using the correct hostname on HADR server should fix the issue. It is a HADR setup related issue and not ibm_db issue. Hence, closing it. Thanks.

**Closed by bimalkjha** 2022-06-16 09:21 UTC

**Comment by ThomasMatthewFletcher** [comment] 2022-06-27 08:55
Hi @bimalkjha, sorry for the delayed reply.

We have not been able to make any progress via HADR support, with the following response:

> We would not be able to assist with the docker container itself but we have not really isolated the exact location of the problem.  It may be docker it may be mac?

> There are many users who connect to the service and have not had a problem as mentioned through various platforms we have seen successful connection without problem thus the configuration appears fine otherwise all platforms should experience similar behavior.

What is the next step for us here?

**Comment by bimalkjha** [comment] 2022-07-19 10:24
@ThomasMatthewFletcher Find the clidriver directory under site_packages. Cd to clidriver/bin, run below command and share the complete output:
```
cd /usr/local/lib/python3.10/site-packages/clidriver/bin
./db2cli execsql -connstring ""DATABASE=BLUDB;HOSTNAME=c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local;PORT=55000;PROTOCOL=TCPIP;UID=90bbba7b;PWD=****************;SSLServerCertificate=src/db1.crt;SECURITY=SSL;"
quit
```
You'll notice the failure. 

As I have shared the detail in my previous update, the delay is caused by the hostname `c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local` that comes from server to client. Please contact the Db2 server team and ask why `c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local:55000` is sent by server to client as a valid server is and why ip address of c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m-0.c-a5315f82-3f56-4aa8-9f23-1ebbb43de337-m.78668276d74a4a2bb8d64c6a81b22035.svc.cluster.local is unidentifiable? Thanks.
