### ISSUE TITLE
ibm-db-dbi returns [IBM][CLI Driver] CLI0115E  Invalid cursor state. SQLSTATE=24000 SQLCODE=-99999 on fetchmany

### ISSUE THREAD

**Issue by setinam** [ibmdb/python-ibmdb#662] opened 2021-09-20 08:08 UTC
On calling fetchmany on one table out of more that 600 (and many other on other DB API 2.0) ibm-db-dbi returns the error:
[IBM][CLI Driver] CLI0115E  Invalid cursor state. SQLSTATE=24000 SQLCODE=-99999
The error occurs when previous fetchmany did not return full number of rows requested. Normally the result set would be empty, but in this case exception is raised.
     cur.execute(args.test_query)
     while True:     
       rows = cur.fetchmany(5)      
       if rows is None or len(rows)==0:
         break
       for r in rows:
         print(r)
As I understand the DB API 2.0 there is no cursor state argument to check.
The exception was raised on 3.0.2 and 3.0.4

**Comment by amukherjee28** [comment] 2021-09-20 09:38
Hi @setinam 

I tried to reproduce the issue with this sample code 

```
query = "select * from test1"

_CURR = _CONN_OBJ.cursor()

_CURR.execute(query)

while True:
    rows = _CURR.fetchmany(44)
    if(rows is None or len(rows) == 0):
        break
    else:
        for row in rows:
            print(row)

query = "select * from act"

_CURR = _CONN_OBJ.cursor()

_CURR.execute(query)

while True:
    rows = _CURR.fetchmany(44)
    if(rows is None or len(rows) == 0):
        break
    else:
        for row in rows:
            print(row)
```

In this case the first returns no rows and the second query has 18 rows.

I am able to run this with no error. I am not sure if my example is in par with your issue.

In case my understanding is not correct here could you please explain a bit more when you say 
"The error occurs when previous fetchmany did not return full number of rows requested. Normally the result set would be empty, but in this case exception is raised."

**Comment by setinam** [comment] 2021-09-20 10:02
> Hi @setinam
> 
> I tried to reproduce the issue with this sample code
> 
> ```
> query = "select * from test1"
> 
> _CURR = _CONN_OBJ.cursor()
> 
> _CURR.execute(query)
> 
> while True:
>     rows = _CURR.fetchmany(44)
>     if(rows is None or len(rows) == 0):
>         break
>     else:
>         for row in rows:
>             print(row)
> 
> query = "select * from act"
> 
> _CURR = _CONN_OBJ.cursor()
> 
> _CURR.execute(query)
> 
> while True:
>     rows = _CURR.fetchmany(44)
>     if(rows is None or len(rows) == 0):
>         break
>     else:
>         for row in rows:
>             print(row)
> ```
> 
> In this case the first returns no rows and the second query has 18 rows.
> 
> I am able to run this with no error. I am not sure if my example is in par with your issue.
> 
> In case my understanding is not correct here could you please explain a bit more when you say
> "The error occurs when previous fetchmany did not return full number of rows requested. Normally the result set would be empty, but in this case exception is raised."

**Comment by setinam** [comment] 2021-09-20 10:03
Closed by mistake

**Comment by setinam** [comment] 2021-09-20 10:07
@amukherjee28 in my case there are multple rows so that the loop is executed multiple times. On the final resultset there is only 1 row in resultset. After that if fetchmany is called the exception is raised.
As I mentioned I have 600 more tables where this procedure works with no problem. but this one fails. WIll post the table column types to get as much info as possible. I hope we can get repeatability

**Comment by amukherjee28** [comment] 2021-09-20 10:34
I looped through all the tables of the sample database in DB2 (72 tables) in my case and it went through fine.

```
print("List Tables present ..... ")

_list_tables = _CONN_OBJ.tables('NEWTON','EMP%')

print(type(_list_tables))
for _table in _list_tables:
    #print(_table['TABLE_NAME'])
    table = _table['TABLE_NAME']

    print("Printing data from : " + table)
    query = "select * from " + table

    _CURR = _CONN_OBJ.cursor()

    _CURR.execute(query)

    while True:
        rows = _CURR.fetchmany(44)
        if(rows is None or len(rows) == 0):
            break
        else:
            for row in rows:
                print(row)
```

My guess is in your case there might be some error occurring in between the 600 select execution and the flow is lost and hence the error.

I understand 600 tables is a lot but could you check once looping through a bit less number of tables.

**Comment by setinam** [comment] 2021-09-20 10:41
@amukherjee28 thank you for you contribution. It moved me to the right mode.
The problem is with the data in the select we are doing on the table. 
The table actualy has more rows that are returned before error. But I do not see the problematic row as the underlying cursor disrupted. It should not have returned just one row. This one row in the dataset is a result of an underlying error I am not seeing. It happens with a coalesce function one field of type integer and nullable. The user made an error and made a default for coalesce an '' . The DB2 and the driver bolted and forgot to report a correct problem.

Is this something that can be fixed or do we close the case?

**Comment by amukherjee28** [comment] 2021-09-20 10:59
Oki good to know that we have narrowed down the problem.
Now coming to the issue with the COALESCE keyword in select Statement, this is more on the SQL side than something to be handled from the DBI.
I suggest let move ahead and close this case and there is nothing much that could be done from the ibm_db_dbi as of now in these kind of exceptions.
The execute API is working as expected with respect to the data. This is a very particular scenario that you have came across.

**Closed** 2021-09-20 11:18 UTC

**Comment by Umair444** [comment] 2025-01-17 12:26
In my case the problem was with the data. I tried to CAST(COLUMN AS INTEGER) which originally was VARCHAR. The DBI driver failed at row with column value = ''. 

Using:
`CASE WHEN COLUMN= '' THEN 0 ELSE CAST(COLUMN AS INTEGER) END`
fixed my problem
