### ISSUE TITLE
ibm_db overwrites memory when callproc() used incorrectly

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#547] opened 2020-08-24 13:19 UTC
When callproc() is invoked incorrectly, it can overwrite memory .  Here is a specific example.

Getting "**_Exception: Supplied statement object parameter is invalid_**" (because memory overwrite has invalidated the object parameter).

from `ibm_db.fetch_assoc()` after `ibm_db.callproc()` for a specific built-in Db2-LUW stored procedure , but for other stored-procedures `fetch_assoc()` works correctly, because the invocation statement is incorrect.

Using python 3.6.8 with ibm_db 3.0.2 with Db2-LUW v11.1.4.5 on Linux ubuntu 16.04.

With the same credentials, I can call the same stored-procedure from the Db2 command-line (clp ) successfully, it returns its result-set OK to the Db2 clp.

But when I call this specific stored procedure from python, the callproc() succeeds, but fetch_assoc() throws `invalid statement object parameter`. Same for fetch_tuple() or other forms of fetch. 

Easy to recreate with this sample code below:

```
#!/usr/bin/python
import sys 
import os  
import ibm_db


db_name='whatever'
db_user='whatever'
db_pwd='whatever'

ibm_db_conn = ibm_db.IBM_DBConnection()
stmt = ibm_db.IBM_DBStatement()

try:
    ibm_db_conn = ibm_db.connect(db_name, db_user, db_pwd)  
    print("\nSuccessfully connected to the database\n")
except:
    print ( "\nFailed to connect to database " + db_name + " as user " + db_user + "\n")
    print (ibm_db.conn_errormsg())
    sys.exit(1)


try:
    action="Call stored procedure "
    stmt = ibm_db.callproc(ibm_db_conn, 'SYSPROC.REORGCHK_TB_STATS', ('T', 'USER'))
    if ( stmt is None ):
        print ("\ncallproc returned None for statement object, unexpected\n")
        sys.exit(1)

    action="fetch first row"
    row = ibm_db.fetch_assoc(stmt)

    while (row):
        print(row['TABLE_SCHEMA'].strip(), row['TABLE_NAME'].strip(), "\n")
        action="fetch next row"
        row = ibm_db.fetch_assoc(stmt)
 
    ibm_db.free_result(stmt)
    ibm_db.close(ibm_db_conn)
    sys.exit(0)

except:
    print("\nFailed on step " + action + "\n")
    if stmt:
        print(ibm_db.stmt_errormsg(stmt))
    if ibm_db_conn:
        if ibm_db.active(ibm_db_conn):
            ibm_db.close(ibm_db_conn)
    sys.exit(1)

```

**Comment by imavo** [comment] 2020-08-29 09:25
python ibm_db.call_proc __always__ copies the stored-procedure parameter values (even for literal values)  to the returned tuple, regardless of whether the programmer specified such a tuple.  

The ibm_db.call_proc() API states "The parameters tuple must contain one entry for each argument (IN/OUT/INOUT) that the procedure expects." . So that's clear.

But if the programmer fails to provide that tuple with the required number of entries, the consequence is that memory will be overwritten (instead of getting a run time error).

So in the test program the following line:
`stmt = ibm_db.callproc(ibm_db_conn, 'SYSPROC.REORGCHK_TB_STATS', ('T', 'USER'))`

will cause python ibm_db to write two values 'T' and 'USER' (i.e. copies of the input parameters) , and I did not provide variables to store those values, so python ibm_db overwrites memory which invalidates the statement handle.

To be compliant with the API, the python code should read instead something like:

`(stmt, p1, p2)  = ibm_db.callproc(ibm_db_conn, 'SYSPROC.REORGCHK_TB_STATS', ('T', 'USER'))`


It would be better (safer?) if python ibm_db was able to issue a runtime error instead of overwriting memory.

**Comment by Earammak** [comment] 2022-06-21 07:49
@imavo 
The issue is from sample code. 
I tried the below script [ modified form your sample code ], it is working fine. 

#!/usr/bin/python
import sys
import os
import ibm_db

db_name=<db_name>
db_user=<user_id>
db_pwd=<password>

ibm_db_conn = ibm_db.IBM_DBConnection()
stmt = ibm_db.IBM_DBStatement()

try:
    ibm_db_conn = ibm_db.connect(db_name, db_user, db_pwd)
    print("\nSuccessfully connected to the database\n")
except:
    print ( "\nFailed to connect to database " + db_name + " as user " + db_user + "\n")
    print (ibm_db.conn_errormsg())
    sys.exit(1)

try:
    action="Call stored procedure "
    (stmt,p1,p2)= ibm_db.callproc(ibm_db_conn, 'SYSPROC.REORGCHK_TB_STATS', ('T', 'USER'))

    if stmt is None:
        print ("\ncallproc returned None for statement object, unexpected\n")
        sys.exit(1)

    action="fetch first row"
    row = ibm_db.fetch_assoc(stmt)

    while (row):
        print(row['TABLE_SCHEMA'].strip(), row['TABLE_NAME'].strip(), "\n")
        action="fetch next row"
        row = ibm_db.fetch_assoc(stmt)

except:
    print("\nFailed on step " + action + "\n")
    if stmt:
        print(ibm_db.stmt_errormsg(stmt))
    if ibm_db_conn:
        if ibm_db.active(ibm_db_conn):
            ibm_db.close(ibm_db_conn)
    sys.exit(1)

ibm_db.free_result(stmt)
ibm_db.close(ibm_db_conn)
sys.exit(0)

**Comment by Earammak** [comment] 2022-06-21 11:26
@imavo The functionality of ibm_db.callproc is to return tuple of 3 values.
It's developer resposibility to assign these returned values to a tuple.
ibm_db.callproc will not know weather returned tuple is being assigned to a tuple of 3 variables or not.

**Closed** 2022-07-06 09:55 UTC
