### ISSUE TITLE
SSL Verification fails for newer versions of python

### ISSUE THREAD

**Issue by rohitvg** [ibmdb/python-ibmdb#365] opened 2019-01-17 23:12 UTC
When installing `ibm_db`  or even any other package that has `ibm_db` as a dependency, the installation fails when ibm_db tries to download the `clidriver` from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/.

For python v3.6+ for `macOS` bundle downloaded and installed from the python website, which does not install certificates as mentioned in the release notes: 
https://www.python.org/downloads/release/python-360/
https://www.python.org/downloads/release/python-370/

<img width="548" alt="image" src="https://user-images.githubusercontent.com/46798762/51353153-9e83cb80-1a64-11e9-8b99-e653402c6672.png">

Since the error that occurs during installation of the package does not explicitly mention the solution, it would be great if this issue is fixed.

One possible way would be to catch this error in the setup.py and re-try with ssl verification disabled, or else to bundle the clidriver with the ibm_db client.

**Comment by SabaKauser** [comment] 2019-01-18 04:17
Hi Rohit,
You need to install the certificates on MAC. This problem would be seen not just with ibm_db, but with any package that uses https. The solution is outside ibm_db setup.

**Comment by SabaKauser** [comment] 2019-01-18 04:19
Another way to workaround the problem is to do the following:
export IBM_DB_HOME=<existing installation of clidriver in your machine>
and retry install. 
check https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/README.md#environment-variables

**Comment by germanattanasio** [comment] 2019-01-18 10:31
Can we ignore the self-signed certificates when downloading the driver?
I saw you use `urllib` so we could create and use a context where self-signed certificates are ignored.

```py
from urllib.request import urlopen
import ssl

response = urlopen('https://ibm.com', context=ssl._create_unverified_context())
```

**Comment by rohitvg** [comment] 2019-01-18 21:06
@SabaKauser the suggested approach can be invoked only if the download fails for the above reason. Its a simple change which I tested out: https://github.com/ibmdb/python-ibmdb/compare/master...rohitvg:clidriver-retry.

The current approach, user needs to:
1. set env variables or install certificates
2. install ibm_db
3. set additional env variables
4. use ibm_db

If this is addressed then it simplifies the process a bit. Please let us know if this is something that can be done.

**Comment by kadler** [comment] 2019-01-18 21:43
> Can we ignore the self-signed certificates when downloading the driver?

The drivers are hosted on an IBM site and the certs are signed by DigiCert. The only reason they appear self-signed is because the new macOS Python installer doesn't ship any CA certificates in its trust store.

**Comment by germanattanasio** [comment] 2019-01-23 18:18
@kadler now that we know the problem, how do we fix it without asking the user to run some obscure command in their terminal?

**Comment by kadler** [comment] 2019-01-23 19:54
I've added a PR to include the necessary certificates. This will work until 2027, when the GeoTrust CA expires. Hopefully Python can fix their issue on macOS by then :grin:. If not, we just have to include the new CA.

**Comment by rohitvg** [comment] 2019-01-23 20:00
@kadler thanks for this!

**Comment by SabaKauser** [comment] 2019-01-24 06:05
I have merged the fix to git.

**Closed** 2019-01-24 06:04 UTC
