### ISSUE TITLE
Python Driver ibm_db Workload balancing bug when connected with Member ip address.

### ISSUE THREAD

**Issue by Manojkumarbyibm** [ibmdb/python-ibmdb#969] opened 2024-11-18 11:11 UTC
Operating System Name: 
Windows / Mac

db2level output from clidriver if in use:

DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL12010" with level identifier "02010110".
Informational tokens are "DB2 v12.1.0.975", "s2409261256", "DYN2409261256WIN64",
and Fix Pack "0".
Product is installed at "C:\IBMDSD" with DB2 Copy Name "IBMDBCL1".

==============================================================================

Target Db2 Server Version: 

**Db2 V13 for z/OS**

Python Version:
**Python 3.9.11**

ibm_db version:
**ibm-db == 3.2.1**

===============================================================================
Value of below environment variables if set:
===============================================================================
Client information for the current copy (copy name: IBMDBCL1):
===============================================================================

Client Package Type       : IBM Data Server Driver Package
Client Version (level/bit): DB2 v12.1.0.975 (s2409261256/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\IBMDSD

Common App Data Path      : C:\IBMDSD\\IBM\DB2\IBMDBCL1
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path *    : C:\IBMDSD\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

* - Warning: db2dsdriver.cfg configuration file is found at the location which
will be deprecated soon. It is recommended to move this file to the location:
"C:\IBMDSD\\IBM\DB2\IBMDBCL1\cfg\".

======================================================================
List of all IBM Data Server client packages on the current workstation:
======================================================================

Copyname      Version Package Language Installed-Location
-------------------------------------------------------------------------------
IBMDBCL1[C,D] 12.1.00 DSD     EN       C:\IBMDSD
-------------------------------------------------------------------------------
 DSD: IBM Data Server Driver Package
-------------------------------------------------------------------------------

=====================================================================
db2dsdriver.cfg schema validation for the entire file:
=====================================================================

Success: The system db2dsdriver.cfg schema validation completed successfully without any errors.

=====================================================================
The validation is completed.
=====================================================================

=====================================================================

Db2 Setup:
-----------
Db2 Group : DSNR3
DDVIPA IP : 9.30.179.1 Port: 51600
Sysplex WLB enabled

DSNR3 has 4 members:
Member DR31:  9.30.179.161
Member DR32:  9.30.179.162
Member DR33:  9.30.179.164
Member DR34:  9.30.179.165
=======================================================================

Problem:
---------
While trying to connect to a DB2 member ip with Workload balancing on, the first connection should go to the member IP and rest of the connections should get distributed as per WLB. But in this case, all the connections are going only to the member IP provided in the connection details. Workload balancing is working fine without DDVIPA (Group) IP address.

WLB is getting picked up by DSdriver Config file:
<database name="DSNR3" host="9.30.179.1" port="51600">
	  <parameter name="enableWLB" value="true"/>
      <parameter name="CurrentSchema" value="SAPT01"/>
      <parameter name="QueryTimeout" value="20"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <parameter name="StreamOutputLOBonCall" value="true"/>
      <parameter name="UserID" value="db2adm"/>
      <parameter name="Password" value="fantom"/>
      <parameter name="ClientAccountingString" value="ddf_pyds"/>
      <parameter name="CurrentPackageSet" value="NULLID"/>
      <wlb>

Same workload balancing on JDBC working fine with member IP address and DDVIPA (Group) IP address.

Program to Reproduce Bug (9.30.179.161 is member IP):
------------------------------------------------------
import os
os.add_dll_directory(r'C:\IBMDSD\bin')
import sys
import ibm_db

conn_str="DATABASE=DSNR3;HOSTNAME=9.30.179.161;PORT=51600;PROTOCOL=TCPIP;UID=user1;PWD=passwd;"

conn = ibm_db.connect(conn_str,'','')

for i in range(0,10):
    if conn:
        stmt = ibm_db.exec_immediate(conn,"SELECT CURRENT MEMBER FROM SYSIBM.SYSDUMMY1")
        if stmt:
            while (ibm_db.fetch_row(stmt)):
                member = ibm_db.result(stmt, 0)
                print("I am on :",member)
                ibm_db.commit(conn)
        else:
            print(ibm_db.stmt_errormsg())

**Comment by Manojkumarbyibm** [comment] 2024-11-18 11:26
/*
  <database name="DSNR3" host="9.30.179.1" port="51600">
	  <parameter name="enableWLB" value="true"/>
      <parameter name="CurrentSchema" value="SAPT01"/>
      <parameter name="QueryTimeout" value="20"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <parameter name="StreamOutputLOBonCall" value="true"/>
      <parameter name="UserID" value="db2adm"/>
      <parameter name="Password" value="fantom"/>
      <parameter name="ClientAccountingString" value="ddf_pyds"/>
      <parameter name="CurrentPackageSet" value="NULLID"/>
      <wlb>
*/

**Comment by Manojkumarbyibm** [comment] 2024-11-18 11:31
<configuration>
  <dsncollection>
    <dsn alias="DSNL7" name="DSNL7" host="9.30.178.45" port="53900">
     <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="STMTDB" name="STMTDB" host="svlxdbta.svl.ibm.com" port="60000">
    </dsn>
    <dsn alias="DC2G" name="DC2G" host="9.30.179.1" port="51200">
     <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSND1" name="DSND1" host="9.30.179.1" port="52600">
     <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNL6" name="DSNL6" host="9.30.179.1" port="53800">
    </dsn>
    <dsn alias="DSNL5" name="DSNL5" host="9.30.179.1" port="52500">
     <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNL4" name="DSNL4" host="9.30.179.1" port="51800">
     <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNI1" name="DSNI1" host="9.30.178.50" port="52100">
      <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNT5" name="DSNT5" host="9.30.178.50" port="50500">
      <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNT2" name="DSNT2" host="9.30.178.50" port="50200">
      <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNT3" name="DSNT3" host="9.30.178.50" port="50300">
      <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNA1" name="DSNA1" host="9.30.178.50" port="52000">
      <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNE4" name="DSNE4" host="9.30.178.50" port="54200">
     <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
    <dsn alias="DSNR3" name="DSNR3" host="9.30.179.1" port="51600">
     <parameter name="Authentication" value="Server_Encrypt"/>
    </dsn>
  </dsncollection>

  <databases>
      <database name="DSNT2" host="9.30.178.50" port="50200">
      <parameter name="CurrentSchema" value="GREYGOOSE"/>
      <parameter name="QueryTimeout" value="20"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <parameter name="StreamOutputLOBonCall" value="true"/>
      <parameter name="UserID" value="LGB0099"/>
      <parameter name="Password" value="pilsner"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="1000"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
      </database>  

      <database name="DSNR3" host="9.30.179.1" port="51600">
	  <parameter name="enableWLB" value="true"/>
      <parameter name="CurrentSchema" value="SAPT01"/>
      <parameter name="QueryTimeout" value="20"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <parameter name="StreamOutputLOBonCall" value="true"/>
      <parameter name="UserID" value="db2adm"/>
      <parameter name="Password" value="fantom"/>
      <parameter name="ClientAccountingString" value="ddf_pyds"/>
      <parameter name="CurrentPackageSet" value="NULLID"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="1000"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
      </database>  

      <database name="DSNL7" host="9.30.178.45" port="53900">
      <parameter name="CurrentSchema" value="GREYGOOSE"/>
      <parameter name="QueryPrefetch" value="1"/>
      <parameter name="QueryTimeout" value="0"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <parameter name="StreamOutputLOBonCall" value="true"/>
      <parameter name="UserID" value="LGB0099"/>
      <parameter name="Password" value="pilsner"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="1000"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
      </database>  
      <database name="STMTDB" host="svlxdbta.svl.ibm.com" port="60000">
      </database>  
      <database name="DSNI1" host="9.30.178.50" port="52100">
      <parameter name="CurrentSchema" value="TPCSSC12"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="QueryTimeout" value="2"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="1000"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
       <specialregisters> 
         <parameter name="CURRENT QUERY ACCELERATION" value="NONE"/>
       </specialregisters> 
      </database>  

      <database name="DSND1" host="9.30.179.1" port="52600">
      <parameter name="CurrentSchema" value="DB2APPL"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="QueryTimeout" value="20"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="25"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
        <alternategroup>
          <parameter name="enableAlternateGroupSeamlessACR" value="true"/>
	  <database name="DSNI1" host="9.30.178.50" port="52100"/>
        </alternategroup>
       </acr>
      </database>  

      <database name="DC2G" host="9.30.179.1" port="51200">
        <parameter name="CurrentSchema" value="CCEAPPL"/>
        <parameter name="enableDirectXA" value="true" />
        <parameter name="ConnectionTimeout" value="5"/>
        <parameter name="CommitOnEOF" value="0"/>
        <parameter name="QueryTimeout" value="20"/>
        <parameter name="tcpipConnectTimeout" value="2"/>

        <wlb>
            <parameter name="enableWLB" value="true"/>
            <parameter name="maxTransports" value="50"/>
        </wlb>
        <acr>
            <parameter name="enableAcr" value="true"/>
            <parameter name="enableSeamlessAcr" value="true"/>
        </acr>
      </database>  
      <database name="DSNT5" host="9.30.178.50" port="50500">
      <parameter name="CurrentSchema" value="DB2APPL"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="FetchBufferSize" value="128K"/>
      <parameter name="QueryTimeout" value="20"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <parameter name="StreamOutputLOBonCall" value="true"/>
      <parameter name="UserID" value="LGB0099"/>
      <parameter name="Password" value="pilsner"/>
      <parameter name="CurrentPackagePath" value="KEPLER"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="1000"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
        <alternategroup>
          <parameter name="enableAlternateGroupSeamlessACR" value="true"/>
	  <database name="DSND1" host="9.30.179.1" port="52600"/>
        </alternategroup>
       </acr>
      </database>  



      <database name="DSNL6" host="9.30.179.1" port="53800">
      <parameter name="StatementConcentrator" value="Literals"/>
      <parameter name="CurrentSchema" value="DB2APPL"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="FetchBufferSize" value="128K"/>
      <parameter name="QueryTimeout" value="20"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <parameter name="StreamOutputLOBonCall" value="true"/>
      <parameter name="UserID" value="LGB0099"/>
      <parameter name="Password" value="pilsner"/>
      <parameter name="CurrentPackagePath" value="KEPLER"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="1000"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
      </database>  

      <database name="DSNT3" host="9.30.178.50" port="50300">
      <parameter name="CurrentSchema" value="DB2APPL"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="FetchBufferSize" value="128K"/>
      <parameter name="QueryTimeout" value="20"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <parameter name="UserID" value="LGB0099"/>
      <parameter name="Password" value="pilsner"/>
      <parameter name="StreamOutputLOBonCall" value="true"/>
      <parameter name="CurrentPackagePath" value="KEPLER"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="1000"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
      </database>  


      <database name="DSNA1" host="9.30.178.50" port="52000">
      <parameter name="CurrentSchema" value="DB2APPL"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="FetchBufferSize" value="128K"/>
      <parameter name="QueryTimeout" value="2"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="25"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
        <alternategroup>
          <parameter name="enableAlternateGroupSeamlessACR" value="true"/>
	  <database name="DSND1" host="9.30.179.1" port="52600"/>
        </alternategroup>
       </acr>
      </database>  


      <database name="DSNL5" host="9.30.179.1" port="52500">
      <parameter name="CurrentSchema" value="DB2APPL"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="QueryTimeout" value="400"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="1000"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
      </database>  

      <database name="DSNL4" host="9.30.179.1" port="51800">
      <parameter name="CurrentSchema" value="DB2APPL"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="FetchBufferSize" value="128K"/>
      <parameter name="QueryTimeout" value="2"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="25"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
      </database>  

      <database name="DSNE4" host="9.30.178.50" port="54200">
      <parameter name="CurrentSchema" value="SAP2SC01"/>
      <parameter name="enableDirectXA" value="true" />
      <parameter name="ConnectionTimeout" value="5"/>
      <parameter name="CommitOnEOF" value="0"/>
      <parameter name="FetchBufferSize" value="128K"/>
      <parameter name="QueryTimeout" value="0"/>
      <parameter name="tcpipConnectTimeout" value="2"/>
      <wlb>
	<parameter name="enableWLB" value="true"/>
        <parameter name="maxTransports" value="25"/>
       </wlb>
       <acr>
        <parameter name="enableAcr" value="true"/>
        <parameter name="enableSeamlessAcr" value="true"/>
       </acr>
       <specialregisters> 
         <parameter name="CURRENT QUERY ACCELERATION" value="ALL"/>
       </specialregisters> 
      </database>  
  </databases>
  <parameters>
     <parameter name="diaglevel" value="4"/>
     <parameter name="CommProtocol" value="TCPIP"/>
     <parameter name="DisableCursorHold" value="1"/> 
     <parameter name="InterruptProcessingMode" value="2"/>  
  </parameters>
  </configuration>

**Comment by bimalkjha** [comment] 2024-11-18 12:55
@Manojkumarbyibm Is it duplicate of https://github.com/cpd-partners/db2connect/issues/52#issuecomment-2482792478?

Please note that WLB is not handled by python driver but the dsdriver that you are using. So, you need to collect db2traces for the issue and open db2tracker for IBM connectivity team to look into as these functionalities are in DRDA layer handled by IBM. Thanks.

**Comment by bimalkjha** [comment] 2024-11-25 14:31
@Manojkumarbyibm I see issue https://github.com/cpd-partners/db2connect/issues/51 is closed now. It was setup issue. Could you please check that and close this issue also? Thanks.

**Closed** 2024-11-29 15:22 UTC
