### ISSUE TITLE
ibm_db.stmt_errormsg() return "UnicodeDecodeError: ..." only in Python3 

### ISSUE THREAD

**Issue by fmeoli** [ibmdb/python-ibmdb#421] opened 2019-09-06 09:55 UTC
Hi,

I working on a client Win 10:
- DB2 v11.1.3031.295 "s1804271300" ,"DYN1804271300WIN64" and Fix Pack "3a";
- Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
- ibm-db==3.0.1
- print(sys.getdefaultencoding())  -> utf-8
- sys.stdout.encoding -> 'utf-8'

The statement "print ibm_db.stmt_errormsg()" return "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 50: ordinal not in range(128)"

Here my code with the results:

Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
> import ibm_db
> ibm_db_conn = ibm_db.connect('database','userid1','secret')
> select = 'select max(ccaf) from ftaf'
> ibm_db.exec_immediate(ibm_db_conn, select)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception
> print(ibm_db.stmt_errormsg())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 50: ordinal not in range(128)**

The statements above in the same enviroment but with Python 2.7 do the right thing:
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
> import ibm_db
> ibm_db_conn = ibm_db.connect('database','userid1','secret')
> select = 'select max(ccaf) from ftaf'
> ibm_db.exec_immediate(ibm_db_conn, select)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 **SQLCODE=-204BM][CLI Driver][DB2/NT64] SQL0204N  "USERID1.FTAF" Þ un nome non definito.  SQLSTATE=42704**

I don't know how to fix it. 
Thanks!

**Comment by SabaKauser** [comment] 2019-09-11 03:13
Hello,
SQLCODE=-204BM][CLI Driver][DB2/NT64] SQL0204N "USERID1.FTAF" Þ un nome non definito. 

The error message is not in English(En_US). what is your  client code page?

**Comment by fmeoli** [comment] 2019-09-16 07:23
Hello, 

my client codepage is Italian but I think I haven't explained it well before ... my problem is the absence of the sql error code in the python3 version of the ibm_db library.

To simulate the problem I executed an incorrect statement (select from a non-existent table) to cause an sql error and highlight the difference in behavior between the python2 version (correct) and python3 (incorrect) of the ibm_db component; in the latter the error code is not displayed due to an error **"UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 50: ordinal not in range(128)"**

thanks

**Comment by SabaKauser** [comment] 2019-09-18 12:59
I think the problem is due to "Þ" in your error message. Which language is this?

**Comment by fmeoli** [comment] 2019-09-18 13:06
The language is Italian and the symbol corresponds to the "è" character (translation from English "is")

**Comment by fmeoli** [comment] 2019-09-18 13:13
The correct message in italian is:

 SQLCODE=-204BM][CLI Driver][DB2/NT64] SQL0204N  "USERID1.FTAF" è un nome non definito.  SQLSTATE=42704

**Comment by SabaKauser** [comment] 2019-09-19 05:41
Thanks.
Can you replace your ibm_db.dll under site-packages/ibm_db_dlls with the one attached and see if the problem is resolved.
I have compiled it with python 3.6.


[ibm_db.zip](https://github.com/ibmdb/python-ibmdb/files/3629577/ibm_db.zip)

**Comment by fmeoli** [comment] 2019-09-19 07:39
Thanks!
with the new dll I can display the error message correctly by calling the 'ibm_db.stmt_errormsg ()' method.
The only remaining difference compared to the python2.7 version is that the error is not set on the Exception: I tried both with the prepare / execute method and with the immediate method. The following are the test sessions in the two environments:

`Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> ibm_db_conn = ibm_db.connect('db','userid1','pwd')
>>> select = 'select max(ccaf) from ftaf'
>>> ibm_db.exec_immediate(ibm_db_conn, select)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception
>>> print(ibm_db.stmt_errormsg())
 SQLCODE=-204ver][DB2/NT64] SQL0204N  "USERID1.FTAF" è un nome non definito.  SQLSTATE=42704
>>> stmt = ibm_db.prepare(ibm_db_conn, select)
>>> ibm_db.execute(stmt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception
>>> print(ibm_db.stmt_errormsg())
 SQLCODE=-204ver][DB2/NT64] SQL0204N  "USERID1.FTAF" è un nome non definito.  SQLSTATE=42704
>>>


Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> ibm_db_conn = ibm_db.connect('db','userid1','pwd')
>>> select = 'select max(ccaf) from ftaf'
>>> ibm_db.exec_immediate(ibm_db_conn, select)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 SQLCODE=-204BM][CLI Driver][DB2/NT64] SQL0204N  "USERID1.FTAF" è un nome non definito.  SQLSTATE=42704
>>> print(ibm_db.stmt_errormsg())
 SQLCODE=-204ver][DB2/NT64] SQL0204N  "USERID1.FTAF" è un nome non definito.  SQLSTATE=42704
>>> stmt = ibm_db.prepare(ibm_db_conn, select)
>>> ibm_db.execute(stmt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: Statement Execute Failed: [IBM][CLI Driver][DB2/NT64] SQL0204N  "USERID1.FTAF" è un nome non definito.  SQLSTATE SQLCODE=-204`

**Comment by SabaKauser** [comment] 2019-09-26 08:34
Hello,
I don't follow the problem. I tried this:
create_table = "create table index_test(id int, data VARCHAR(50)"
try:
    rc = ibm_db.exec_immediate(conn, create_table)
except Exception as inst:
    print(str(inst))
    print("Query ' {} ' failed with ".format(create_table))
    print("Error : {}".format(ibm_db.stmt_errormsg()))

And I could see the error message from both inst and stmt_errormsg() on Python 3.7.

**Comment by fmeoli** [comment] 2019-09-26 11:27
Hello,
unfortunately not the same behavior in my environment. 
The **print(str(inst) return nothing** while the second two instructions return:

> Query ' create table index_test(id int, data VARCHAR(50) ' failed with
Error : [IBM][CLI Driver][DB2/NT64] SQL0104N  Un token imprevisto  "END-OF-STATEMENT" è stato rilevato dopo "nt, data VA SQLCODE=-104I token previsti possono includere: ")".  SQLSTATE=42601

Thank you for your contribution

**Comment by SabaKauser** [comment] 2019-09-30 09:03
hmm. Not sure why is the execption not set in your environment.
If you see the code of ibm_db_exec(), you can see we are setting exception message:
```c
ibm_db.c:
Py_BEGIN_ALLOW_THREADS;
        rc = SQLExecDirectW((SQLHSTMT)stmt_res->hstmt, stmt, SQL_NTS);
        Py_END_ALLOW_THREADS;
        if ( rc < SQL_SUCCESS ) {
            _python_ibm_db_check_sql_errors(stmt_res->hstmt, SQL_HANDLE_STMT, -1,
                1, return_str, DB2_ERRMSG,
                stmt_res->errormsg_recno_tracker);
```
And _python_ibm_db_check_sql_errors(..) has this:
```c
static void _python_ibm_db_check_sql_errors( SQLHANDLE handle, SQLSMALLINT hType, int rc, int cpy_to_global, char* ret_str, int API, SQLSMALLINT recno )
{
.
.
rc1 =  SQLGetDiagRec( hType, handle, recno, sqlstate, &sqlcode, msg,
                          SQL_MAX_MESSAGE_LENGTH + 1, &length );
    if ( rc1 == SQL_SUCCESS )
    {
        while ((p = strchr( (char *)msg, '\n' ))) {
            *p = '\0';
        }
        sprintf((char*)errMsg, "%s SQLCODE=%d", (char*)msg, (int)sqlcode);
        if (cpy_to_global != 0 && rc != 1 ) { **//cpy_to_global is 1 and rc == -1**
            **PyErr_SetString(PyExc_Exception, (char *) errMsg);**
        }
.
}
}

```

**Comment by fmeoli** [comment] 2019-10-02 09:00
I've seen it and I don't understand the behavior on my environment. Anyway I will change my code by displaying the sql error that with the new dll return correctly, thank you.
Last thing, the dll patch will be part of an upcoming release? Can I know approximately the date?

**Comment by SabaKauser** [comment] 2019-10-03 03:00
Thanks.
Yes, the fix will be part of new release. I may release a new version by end of this year.

**Comment by SabaKauser** [comment] 2019-11-13 02:28
is there anything outstanding on this?

**Comment by fmeoli** [comment] 2019-11-14 15:38
No, thanks

**Closed** 2019-11-15 02:56 UTC

**Comment by kxmatjob** [comment] 2021-12-05 02:25
why è in ibm_db.stmt_errormsg()? Return garbled code when using database of codeset=gbk, help me.
