### ISSUE TITLE
Python 3 with IBM DB2 Connect

### ISSUE THREAD

**Issue by Ravikumarnl** [ibmdb/python-ibmdb#308] opened 2018-03-08 13:11 UTC
db_name = "Databasename"
host_name  = "host.com"
port =  5010
auth_user = "userID"
auth_pass = "password"
conn_str = "DATABASE=%s;HOSTNAME=%s;PORT=%d;PROTOCOL=TCPIP;UID=%s;PWD=%s;"%(db_name, host_name, port, auth_user, auth_pass)

conn = ibm_db.connect(conn_str, '', '')

and I am getting the below issues:
SystemError: <built-in function connect> returned NULL without setting an error
[Finished in 1.1s with exit code 1]

Could you please help me for what reason this issue is coming up; I am not able to debug this as well by changing different parameters

**Comment by SabaKauser** [comment] 2018-03-08 14:51
Hi Ravi,
Can you try this dll and see if the problem goes away.


[ibm_db.cp36-win_amd64.zip](https://github.com/ibmdb/python-ibmdb/files/1793582/ibm_db.cp36-win_amd64.zip)

similar problem reported here ->
https://github.com/ibmdb/python-ibmdb/issues/294

and google forum-> https://groups.google.com/forum/#!topic/ibm_db/zzo5S2MqEoU

**Comment by gygabyte017** [comment] 2018-03-15 15:09
Same issue. Here is the output with your dll:

```
Not a persistent connection. check for max connections. resued = 0
Allocate env handle
Connection attempted, but failed. Hence free env and dbc
connection is in error with conn_res = 00000000022D4870
rc is not success. Error message printed. Returning NULL. rc = -2
Traceback (most recent call last):
  File "P:\Users\934334\Desktop\test_db2.py", line 3, in <module>
    conn = ibm_db.connect("HOSTNAME=;PORT=;DATABASE=;UID=;PWD=;", "", "")
SystemError: <built-in function connect> returned NULL without setting an error
```

What's wrong?

**Comment by SabaKauser** [comment] 2018-03-21 06:13
Would it be possible for you to generate assembly via visual studio for ibm_db.connect() run that is failing. 
I do not see any problem with the code.  the code that executes for connect is this:

	if ( !conn_res->henv ) {
			rc = SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &(conn_res->henv));
			printf("Allocate env handle\n");
			if (rc != SQL_SUCCESS) {
				_python_ibm_db_check_sql_errors( conn_res->henv, SQL_HANDLE_ENV, rc,
					1, NULL, -1, 1);
				break;
			}
			rc = SQLSetEnvAttr((SQLHENV)conn_res->henv, SQL_ATTR_ODBC_VERSION, 
				(void *)SQL_OV_ODBC3, 0);
		}

		if (!reused) {  **==> resused = 0 from debug output, but the condition is evaluating to FALSE**
			/* Alloc CONNECT Handle */
			rc = SQLAllocHandle(SQL_HANDLE_DBC, conn_res->henv, &(conn_res->hdbc));
			printf("Allocate conn handle: conn_res=%p\n", conn_res);
			if (rc != SQL_SUCCESS) {
				_python_ibm_db_check_sql_errors(conn_res->henv, SQL_HANDLE_ENV, rc, 
					1, NULL, -1, 1);
				break;
			}
		}
From above piece of code and from the debug output, we can see its allocating env handle. Since reused=0, I would expect control to enter the loop for allocating connection handle SQL_HANDLE_DBC but its not for some reason which I can't understand. 
Since we do not have a valid connection handle allocated, we error out.

If you can attach to debugger in VS and step into _python_ibm_db_connect_helper() function, we might be able to dig this further. I am using windows 10 and I can't reproduce. Even with Windows 7, I am unable to reproduce this proble,.

**Comment by gygabyte017** [comment] 2018-03-22 11:30
Unfortunately one of the tries I did was to completely remove everything ibm related and do a fresh install. After that, it works again. So I cannot debug it, sorry!

**Comment by SabaKauser** [comment] 2018-03-22 11:36
ok. I shall close this for now. When the problem appears again, it would be good to have some debug data or assembly.
Thank you!

**Closed by SabaKauser** 2018-03-22 11:36 UTC
