### ISSUE TITLE
UnicodeDecodeError: After upgrading from V7R2 to V7R3 ibm_db.result() is failing

### ISSUE THREAD

**Issue by nadir-syed** [ibmdb/python-ibmdb#585] opened 2020-12-21 20:51 UTC
Versions/Env:
python 3.6.10
ibm-db 2.0.5.12
OS: IBM i 7.2
local database: DB2

ibm_db.result(stmt, 'STRMNAME') is failing with "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 38: invalid continuation byte". Data in STRMNAME does NOT have 38th position, infact Column itself is 30 char long.

Here is the data:

STREAMID | STRMNAME | TRANDT | TRANTOT | TRANCAT | TRANDESC
1 | DAD SMITH | 1/1/2019 | 5833.33 | PAYCHECK | DAD SMITH PAYROLL
1 | DAD SMITH | 2/1/2019 | 5833.33 | PAYCHECK | DAD SMITH PAYROLL
1 | DAD SMITH | 3/1/2019 | 5833.33 | PAYCHECK | DAD SMITH PAYROLL
1 | DAD SMITH | 4/1/2019 | 5833.33 | PAYCHECK | DAD SMITH PAYROLL
1 | DAD SMITH | 5/1/2019 | 5833.33 | PAYCHECK | DAD SMITH PAYROLL
1 | DAD SMITH | 6/1/2019 | 9724.33 | PAYCHECK | DAD SMITH PAYROLL

Same python script works in python 3.6.9 and ibm-db 2.0.5.9 in same env IBM i and DB2 database.

Why is it failing? How can I make it work in ibm-db 2.0.5.12?

**Comment by amukherjee28** [comment] 2020-12-22 07:24
Hi,

Looks like this is something to do with the i-series support of ibm_db.
@kadler can you please look at this one once.

Thanks.

**Comment by kadler** [comment] 2020-12-22 16:26
@nadir-syed can you please reopen the bug at https://github.com/kadler/python-ibmdb/

**Comment by nadir-syed** [comment] 2020-12-22 16:40
@kadler I think it's probably more than just version. As in same env I downgraded ibm-db from 2.0.5.12 to 2.0.5.9 and still got error though now for different position 31. Do you still want me to open the bug in 2.0.5.12? 
I was thinking version is the cause as same code works in 2.0.5.9 on other ibm i box.

2020-12-22 08:05:46,761 - root - ERROR - 'utf-8' codec can't decode byte 0xb0 in                                                                                                                                                              position 31: invalid start byte
Traceback (most recent call last):
  File "voianalytics.py", line 170, in <module>
    summarize_income_stream(stmt)
  File "voianalytics.py", line 69, in summarize_income_stream
    prvStrmName = ibm_db.result(stmt, 'STRMNAME')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 31: invalid                                                                                                                                                              start byte

Everytime I change code to add print statements for debugging, position & byte is changing like:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 38: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 42: invalid start byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 40: invalid continuation byte

**Comment by nadir-syed** [comment] 2020-12-22 21:59
@kadler I opened the defect [https://github.com/kadler/python-ibmdb/issues/8](url)

**Comment by nadir-syed** [comment] 2021-01-08 21:03
Issue is specifically in ibm_db.result(stmt, 'STRMNAME') when result set is fetched using ibm_db.fetch_row(stmt). Code works If I fetch result set using dict = ibm_db.fetch_assoc(stmt) and use dict['STRMNAME'] to fetch column data.

ibm_db.result(stmt, xxx) is probably not getting correct length or something else. Not sure what is causing the issue in ibm_db.result method.

**Comment by amukherjee28** [comment] 2021-09-21 08:11
https://github.com/kadler/python-ibmdb/issues/8

Duplicate of the issue.

**Comment by amukherjee28** [comment] 2022-03-23 08:59
closing the issue as we have the base issue reported for IBMi closed.
https://github.com/kadler/python-ibmdb/issues/8
Thanks

**Closed by amukherjee28** 2022-03-23 08:59 UTC
