### ISSUE TITLE
data type conversion bug pandas int64 to DB2 BIGINT?

### ISSUE THREAD

**Issue by sebschlue** [ibmdb/python-ibmdb#612] opened 2021-03-09 22:36 UTC
pandas dataframe has column of type "int64" that contains large positive integers.

DB2 column is of type "BIGINT"

SQL bulk insert is being performed via

```
ibm_db.execute_many(insert_prepared_statement, tuple([tuple(x) for x in df.values]))`
```
python classifies these large integers inside the tuple of tuples as `<class 'int'>` and their values are printed correctly at the console.

But said values are not correctly inserted into DB2 database - they become some different, negative numbers instead. So this seems to be a data conversion bug.

It does not happen to "small" integers that are also classified as "int64" in pandas. I guess it only happens for integers that are actually "larger" than what would fit into "int32".

From my point of view this seems to be a bug in python-ibmdb - python/pandas seems to be fine.

My current workaround is to convert these values to strings just before performing the bulk insert.

```
df['xyz'] = df[xyz'].apply(str)
```
I am not quite sure if the client driver or the DB2 database server itself then performs the data conversion from String to BIGINT but conversion if performed correctly then.

From my naive understanding I would guess that in case of pandas int64 ---> DB2 BIGINT no data conversion should be necessary at all, which makes this bug even weirder to me.

ibm-db 3.0.3
pandas 1.2.3
python 3.9.2

DB2 11.5.5.0

Linux x86_64

**Comment by sebschlue** [comment] 2021-03-10 13:24
The problem also happens when using Pandas with SQLAlchemy.

sqlite driver works fine.

Bug is triggered when performing

```
engine1 = create_engine('db2+ibm_db:// . . . ')
engine2 = create_engine('sqlite:// . . . ')
df1 = pd.read_sql('SELECT * FROM A', engine1)
df1.to_sql('B', engine1, if_exists='replace', index=False, dtype={'id': BIGINT, . . . })
df2 = pd.read_sql('SELECT * FROM B', engine1)
```

Bug is NOT triggered when performing

```
engine1 = create_engine('db2+ibm_db:// . . . ')
engine2 = create_engine('sqlite:// . . . ')
df1 = pd.read_sql('SELECT * FROM A', engine1)
df1.to_sql('B', engine2, if_exists='replace', index=False, dtype={'id': BIGINT, . . . })
df2 = pd.read_sql('SELECT * FROM B', engine2)
```

**Comment by sebschlue** [comment] 2021-03-10 13:57
It seems the number is converted to a little endian signed 32bit integer.

7988165349711605663 becomes -56299520

**Comment by amukherjee28** [comment] 2021-03-11 17:41
Hi,

Thanks a lot of detailed explanation.

Please allow me to work on this and I will get back with details.

Thanks.

**Comment by amukherjee28** [comment] 2021-03-16 11:57
I did some debugging on this and here's my analysis.

I used a sample program to fetch data from a table both using normal ibm_db api and pandas API.
The table consists of columns with INT and BIGINT datatype.

I am trying to fetch data using both normal python ibm_db API and then using PANDAS API, for me the data from both API are same.

SAMPLE PROGRAM
----------------------------

import pandas as pd
import ibm_db
import ibm_db_dbi

#creating connection

print("Creating connection.......")
conn_string = "DATABASE=<DBNAME>;HOSTNAME=<HOSTNAME>;PORT=<PORT>;UID=<UID>;PWD=<PASSWORD>"
conn1 = ibm_db.connect(conn_string,"","")
conn = ibm_db_dbi.Connection(conn1)
if conn:
    print("Connection ...... [SUCCESS]")
else:
    print("Connection ...... [FAILURE]")

#creating table

print("Creating table............")
table_create = "CREATE Table PANDA_TEST (c1 INT, C2 BIGINT)"

try:
    res = ibm_db.exec_immediate(conn1,table_create)
    print("Table Created ..... [SUCCESS]")
except:
    print("=> TABLE Exists!!")

#inserting values in table

print("Inserting data into table ..............")
val = "INSERT into PANDA_TEST values(1,1234567899987),(2,7988165349711605663)"

res = ibm_db.exec_immediate(conn1,val)
print("Data inserted ..... [SUCCESS]")

#selecting data

print("Selecting data............")
select_data = "select * from PANDA_TEST"

exe = ibm_db.exec_immediate(conn1,select_data)

row = ibm_db.fetch_tuple(exe)
while row:
    print("|\t" + str(row[0]) + "|\t" + str(row[1]) + "|")
    print("----------------------------------------")
    row = ibm_db.fetch_tuple(exe)

print("Printing data using pandas ................")
panda_query = pd.read_sql(select_data,conn)

df = pd.DataFrame(panda_query,columns=['C1','C2'])

print(df)

ibm_db.exec_immediate(conn1,"Drop table PANDA_TEST")


OUTPUT
------------------------

Creating connection.......
Connection ...... [SUCCESS]
Creating table............
Table Created ..... [SUCCESS]
Inserting data into table ..............
Data inserted ..... [SUCCESS]
Selecting data............
|       1|      1234567899987|
----------------------------------------
|       2|      7988165349711605663|
----------------------------------------
Printing data using pandas ................
   C1                   C2
0   1        1234567899987
1   2  7988165349711605663

Let me know if my understanding here is in line with what you have reported.

Let me know your input on this.

Thanks.

**Comment by sebschlue** [comment] 2021-03-16 12:32
This test does not trigger the error because the large values originate from the `String`

```
val = "INSERT into PANDA_TEST values(1,1234567899987),(2,7988165349711605663)"
```

Here is a sample program to show the error:

```
from sqlalchemy import create_engine
from sqlalchemy.types import INT
from sqlalchemy.types import BIGINT

data = (1, 1234567899987), (2, 7988165349711605663)

df1 = pd.DataFrame(list(data), columns=['c1', 'c2'])
print(df1)
print(df1.dtypes)

print()

df1.to_sql('pandas_test', db2_engine, if_exists='replace', index=False, dtype={'c1': INT, 'c2': BIGINT})
df2 = pd.read_sql('SELECT * FROM pandas_test', db2_engine)
print(df2)
print(df2.dtypes)
```

And this is its output:

```
   c1                   c2
0   1        1234567899987
1   2  7988165349711605663
c1    int64
c2    int64
dtype: object

   c1          c2
0   1  1912286035
1   2   -56299617
c1    int64
c2    int64
dtype: object
```

**Comment by sebschlue** [comment] 2021-03-16 12:39
And now with workaround:

```
data = ((1, 1234567899987), (2, 7988165349711605663))

df1 = pd.DataFrame(list(data), columns=['c1', 'c2'])
print(df1)
print(df1.dtypes)

print()

# workaround
df1['c1'] = df1['c1'].apply(str)
df1['c2'] = df1['c2'].apply(str)

df1.to_sql('pandas_test', db2_engine, if_exists='replace', index=False, dtype={'c1': INT, 'c2': BIGINT})
df2 = pd.read_sql('SELECT * FROM pandas_test', db2_engine)
print(df2)
print(df2.dtypes)
```

```
   c1                   c2
0   1        1234567899987
1   2  7988165349711605663
c1    int64
c2    int64
dtype: object

   c1                   c2
0   1        1234567899987
1   2  7988165349711605663
c1    int64
c2    int64
dtype: object```

**Comment by amukherjee28** [comment] 2021-03-16 12:45
Is there by any chance can you verify when the incorrect values are seen in the select statement, The data in the database is also inserted incorrectly.
Can you check the data in the database after panda is inserting the value.

Thanks.

**Comment by sebschlue** [comment] 2021-03-16 12:47
Yes, the data is inserted incorrectly into the database.

**Comment by sebschlue** [comment] 2021-03-16 12:51
I am sure that I could also create a sample program that does not use SQLAlchemy at all (just to rule that out) that shows the same error. Please tell me if that would be helpful.

**Comment by amukherjee28** [comment] 2021-03-16 13:03
That would be really helpful if you can give me a sample program.

that will help me to get traces and analyze more.

Thanks

**Comment by amukherjee28** [comment] 2021-03-16 13:19
Hi,

I am able to dig a bit more into this.

sample program 

'''
import pandas as pd
import ibm_db
import ibm_db_dbi
import ibm_db_sa
import sqlalchemy

#creating connection

print("Creating connection.......")
conn = sqlalchemy.create_engine('ibm_db_sa:////user:pass@host:port/db')
if conn:
    print("Connection ...... [SUCCESS]")
else:
    print("Connection ...... [FAILURE]")

data = ((3, 1234567899987), (4, 7988165349711605663))

print("Inserting using pandas..........")

df = pd.DataFrame(data,columns=['c1','c2'])
print(df)
print(df.dtypes)

df.to_sql('panda_test',conn,if_exists='append',index=False,schema='SCHEMA_NAME')

df = pd.read_sql('SELECT * FROM PANDA_TEST', conn)
print(df)
'''

OUTPUT

'''
Creating connection.......
Connection ...... [SUCCESS]
Inserting using pandas..........
   c1                   c2
0   3        1234567899987
1   4  7988165349711605663
c1    int64
c2    int64
dtype: object
DB2/LINUXX8664
   c1                   c2
0   1        1234567899987
1   2  7988165349711605663
2   3        1234567899987
3   4  7988165349711605663
4   3        1234567899987
5   4  7988165349711605663
'''

I am using DB2/LUW server.


Can you please specify what server you are connecting to.

Thanks.

**Comment by sebschlue** [comment] 2021-03-16 13:50
I am connecting to DB2 11.5.5.0 on Linux x86_64.

I am using Python 3.9.2.

**Comment by amukherjee28** [comment] 2021-03-16 13:57
Even I am using similar setup to run the sample programs.

But I am not able to hit the same issue that you are seeing.

PROGRAM

```
import pandas as pd
import ibm_db
import ibm_db_dbi
import ibm_db_sa
import sqlalchemy
from sqlalchemy.types import INT
from sqlalchemy.types import BIGINT

#creating connection

print("Creating connection.......")
conn = sqlalchemy.create_engine('db2+ibm_db://newton:A2m8test@waldevdbclnxtst06.dev.rocketsoftware.com:60000/IBMDB')
if conn:
    print("Connection ...... [SUCCESS]")
else:
    print("Connection ...... [FAILURE]")

data = ((3, 1234567899987), (4, 7988165349711605663))

print("Inserting using pandas..........")

df = pd.DataFrame(data,columns=['c1','c2'])
print(df)
print(df.dtypes)

df.to_sql('panda_test',conn,if_exists='append',index=False,schema='NEWTON',dtype={'c1': INT, 'c2': BIGINT})

df = pd.read_sql('SELECT * FROM PANDA_TEST', conn)
print(df)
```

OUTPUT

```
Creating connection.......
Connection ...... [SUCCESS]
Inserting using pandas..........
   c1                   c2
0   3        1234567899987
1   4  7988165349711605663
c1    int64
c2    int64
dtype: object
DB2/LINUXX8664
   c1                   c2
0   1        1234567899987
1   2  7988165349711605663
2   3        1234567899987
3   4  7988165349711605663
```

**Comment by sebschlue** [comment] 2021-03-16 14:33
Here is a sample program that uses neither SQLAlchemy nor Pandas and still shows the error:

```
ibm_db2_con = ibm_db.connect('database=db;hostname=hostname;port=port;protocol=tcpip;uid=user;pwd=pass','','')
ibm_db2_dbi_con = ibm_db_dbi.Connection(ibm_db2_con)

try:
    ibm_db.exec_immediate(ibm_db2_con, 'DROP TABLE "PANDAS_TEST"')
except:
    pass

ibm_db.exec_immediate(ibm_db2_con, 'CREATE TABLE "PANDAS_TEST" ("C1" INTEGER , "C2" BIGINT) IN "USERSPACE1"')

data = ((1, 1234567899987), (2, 7988165349711605663))

insert_statement = 'INSERT INTO "PANDAS_TEST" VALUES(?, ?)'
insert_prepared_statement = ibm_db.prepare(ibm_db2_con, insert_statement)
ibm_db.execute_many(insert_prepared_statement, data)

select_statement = 'SELECT "C1", "C2" FROM "PANDAS_TEST"'
cursor = ibm_db2_dbi_con.cursor()
cursor.execute(select_statement)
result = cursor.fetchall()
print(result)
```

```
[(1, 1912286035), (2, -56299617)]
```

**Comment by sebschlue** [comment] 2021-03-16 14:34
Can you tell me the version numbers of python, ibm_db and DB2 that you are using?

**Comment by imavo** [comment] 2021-03-16 14:57
@amukherjee28  I am using ibm_db v3.0.3 with  local Db2-LUW instances  of both V11.5.5.0 and V11.1.4.6.  Your sample code above inserts and returns incorrect values for me, and I recreate the behaviour reported by @sebschlue 

The code in `ibm_db.c` function `_python_ibm_db_bind_data` for TYPE(bind_data) = PYTHON_FIXNUM, the (param_node *) curr -> ivalue  is  always SQLINTEGER  (and there's no SQLBIGINT in that param_node structure).

**Comment by amukherjee28** [comment] 2021-03-16 17:43
Hi,

Okay finally I have reproduced the issue.

It is really wired as when I am trying from windows machine everything works fine. I am not facing any issue.

When I started running the same programs from Linux machines I started seeing the issue.

Can you please confirm @imavo @sebschlue are you also using non windows machines to run the programs.

Thanks.

**Comment by imavo** [comment] 2021-03-16 18:16
I'm using Linux x64 (ubuntu 20.04).

**Comment by amukherjee28** [comment] 2021-03-16 18:41
Hi,

After going through the traces here is the analysis.

WINDOWS
-----------------

In windows when the insert statement is prepared for the BIGINT field the bind parameter automatically is binded with SQL_C_CHAR
SQLBindParameter( hStmt=1:1, iPar=2, fParamType=SQL_PARAM_INPUT, fCType=SQL_C_CHAR, fSQLType=SQL_BIGINT, cbColDef=19, ibScale=0, rgbValue=&0000028c825c5540, cbValueMax=19, pcbValue=<NULL pointer> )
    ---> Time elapsed - +0.000000E+000 seconds

And hence during execute proper value is send to the server

SQLExecute( hStmt=1:1 )
    ---> Time elapsed - +0.000000E+000 seconds
( Row=1, iPar=1, fCType=SQL_C_LONG, rgbValue=1 )
( Row=1, iPar=2, fCType=SQL_C_CHAR, rgbValue="" - x'' )

LINUX
----------------

In Linux however the behavior is quite different.

For the BIGINT field bind param is binding the value with SQL_C_LONG
SQLBindParameter( hStmt=1:1, iPar=2, fParamType=SQL_PARAM_INPUT, fCType=SQL_C_LONG, fSQLType=SQL_BIGINT, cbColDef=19, ibScale=0, rgbValue=&00007fad432d96f0, cbValueMax=0, pcbValue=<NULL pointer> )
    ---> Time elapsed - -3.276600E-002 seconds

And hence incorrect value is send to the server at the time of execute

SQLExecute( hStmt=1:1 )
    ---> Time elapsed - +4.859193E+008 seconds
( Row=1, iPar=1, fCType=SQL_C_LONG, rgbValue=3 )
( Row=1, iPar=2, fCType=SQL_C_LONG, rgbValue=1912286035 )

I will work on this more to check how this can be corrected.

Thanks.

**Comment by sebschlue** [comment] 2021-03-17 08:11
Sorry for my late reply. I experience this issue on Linux and MacOS - haven't tried Windows.

**Comment by imavo** [comment] 2021-03-22 13:12
The ibm_db changes for version 3.0.3  may have caused this issue for Linux x64. Specifically running the ibm_db version 3.0.2 on Linux x64 does not recreate the symptom, whereas version 3.0.3 exhibits the symptom.  Maybe related to zODBC support?

On Windows x64 the version 3.0.3 has BIGINT_IS_SHORTER_THAN_LONG = 1 , while that is 0 on Linux x64.

**Comment by amukherjee28** [comment] 2021-03-22 13:23
Hi @imavo 

Yes a new check was introduced for ZODBC support __LP64 flag.

Because of this check Linux and Mac is setting the flag to true and windows as false and hence the value of BIGINT_IS_SHORTER_THAN_LONG is 0 in Linux and Mac and 1 in windows.

I am working on this as to see what impact it has on ZOS.

Thanks.

**Comment by imavo** [comment] 2021-03-22 13:34
Looks like incomplete environment testing of ibm_db prior to release. Hope you folks can improve the test coverage to find bloopers like this before release.

**Comment by amukherjee28** [comment] 2021-04-09 18:12
This issue has been fixed in the latest release.

Please check and let me know.
Thanks

**Comment by imavo** [comment] 2021-04-09 20:24
ibm_db v3.0.4 worked for my bigint case on linux (ubuntu 20.04) with db2 v11.5.5.0, so the issue that previously impacted v3.0.3 appears to be fixed in v3.0.4.

**Comment by amukherjee28** [comment] 2021-04-10 11:01
@imavo thanks for your inputs.

**Comment by sebschlue** [comment] 2021-04-10 11:25
I can also confirm that the sample test program now works fine. MaxOS X and Python 3.9.4, test program running against DB2 v11.5.5.0 on Linux on x86_64

**Comment by sebschlue** [comment] 2021-04-10 11:28
Thank you very much, I think this issue can be closed.

**Closed** 2021-04-10 11:39 UTC
