### ISSUE TITLE
Float value is retrieved incorrectly when using SELECT FLOAT(value) FROM ...

### ISSUE THREAD

**Issue by lyangus** [ibmdb/python-ibmdb#725] opened 2022-02-17 05:57 UTC
Use the following python application to run a simple select stmt:
SELECT FLOAT(0.1), FLOAT(0.5), FLOAT(1.0), DECIMAL(0.5, 3, 3) FROM SYSIBM.SYSDUMMY
It should be returned as : 
0.1, 0.5, 1.0
It returned the following values:
6.4,  512.0,  262144.0

From ODBC application trace:
0.100000,  0.500000,1.000000  are returned from SQLFetch()

Sample program:
from __future__ import print_function
import sys
import ibm_db
print('ODBC Test start')
conn = ibm_db.connect('','','')

query ='SELECT FLOAT(0.1), FLOAT(0.5), FLOAT(1.0) FROM SYSIBM.SYSDUMMY1;'

options = {ibm_db.SQL_ATTR_CURSOR_TYPE: ibm_db.SQL_CURSOR_FORWARD_ONLY}
try:
    stmt = ibm_db.prepare(conn, query, options)
    result = ibm_db.execute(stmt)
    row = ibm_db.fetch_tuple(stmt)
    print("QUERY 1 using ibm-db setup")
    while (row):
      for i in row:
          print(i)
          row = ibm_db.fetch_tuple(stmt)
except:
  print(ibm_db.stmt_errormsg)

ibm_db.close(conn)

**Comment by amukherjee28** [comment] 2022-02-17 06:04
@lyangus Are you using ibm_db driver on ZOS platform. Please do let me know.
Also please let me know if you are using the latest version of the driver, if not please mention the version as well.

**Comment by amukherjee28** [comment] 2022-02-17 06:46
I have tried sample code in Different Platforms and were not able to reproduce the issue.

I tried running the code in Linux connection to db2 LUW and ZOS and the results were as per expectation.
Also I ran the same code from ZOS machine as well and it was working fine for me.

Sample program
----------------------

```
import ibm_db

print("=> Creating the connection")
conn = ibm_db.connect("","","")

serverInfo = ibm_db.server_info(conn)

print("Server Type = " + serverInfo.DBMS_NAME)

query ='SELECT FLOAT(0.1), FLOAT(0.5), FLOAT(1.0) FROM SYSIBM.SYSDUMMY1;'

options = {ibm_db.SQL_ATTR_CURSOR_TYPE: ibm_db.SQL_CURSOR_FORWARD_ONLY}
try:
	stmt = ibm_db.prepare(conn, query, options)
	result = ibm_db.execute(stmt)
	row = ibm_db.fetch_tuple(stmt)
	print("QUERY 1 using ibm-db setup")
	while (row):
		for i in row:
			print(i)
			row = ibm_db.fetch_tuple(stmt)
except:
	print(ibm_db.stmt_errormsg)

ibm_db.close(conn)
```

OUTPUT SEEN
---------------------
```
python float1.py
=> Creating the connection
Server Type = DSN12015
QUERY 1 using ibm-db setup
0.1
0.5
1.0
```

INI FILE USED
-----------------

```
[COMMON]
MVSDEFAULTSSID=SSID
CURRENTAPPENSCH=UNICODE
FLOAT=IEEE
APPLTRACE=0
APPLTRACEFILENAME=./odbc_appl_trace
DIAGTRACE=0
DIAGTRACE_NO_WRAP=0
DIAGTRACE_BUFFER_SIZE=60000000
[SSID]
MVSATTACHTYPE=CAF
MULTICONTEXT=0
PLANNAME=DSNACLI
[DATABASE_NAME]
AUTOCOMMIT=1
```

Could you please share the INI file configuration that was used when the incorrect result is seen.

**Comment by lyangus** [comment] 2022-02-17 17:44
I will request that from customer and upload here. Thanks

**Comment by lyangus** [comment] 2022-02-17 17:44
Any other information do we need to collect?

**Comment by lyangus** [comment] 2022-02-24 06:56
when the INI file using:
CURRENTAPPENSCH=ASCII and remove FLOAT=IEEE
The output:
6.4
512.0
262144.0

**Comment by amukherjee28** [comment] 2022-03-23 07:55
Can we close this issue. Solution to the issue is to have the FLOAT=IEEE present in the ODBC INI file.

**Closed** 2022-03-30 03:52 UTC
Labels: waiting for response
