### ISSUE TITLE
Cannot connect to remote DB with regular user - SystemError: <built-in function connect> returned NULL without setting an error

### ISSUE THREAD

**Issue by slavchomitov** [ibmdb/python-ibmdb#294] opened 2018-01-04 07:56 UTC
I'm using the latest version of Python and ibm_db on windows 7 machine. I'm trying a very simple code:
`#! python3
import ibm_db

# Getting the previous last device and card ids
database_name = 'masked'
database_hostname = 'masked'
database_port = 'masked'
database_protocol = 'TCPIP'
database_user = 'masked'
database_password = 'masked'
database_connection = 'DATABASE={};HOSTNAME={};PORT={};PROTOCOL={};UID={};PWD={};'.format(database_name, database_hostname, database_port, database_protocol, database_user, database_password)

conn = ibm_db.connect(database_connection, "", "")
print('Connection to DB successful')`

When I run it, I get the following error:
`Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\Documents\Python\test DB2 connection.py", line 14, in <module>
    conn = ibm_db.connect(database_connection, "", "")
SystemError: <built-in function connect> returned NULL without setting an error
`

ibm_db.conn_error and ibm_db. conn_errormsg don't return anything. 
The remote DB itself is up and running and I'm able to connect to it using other means. 

If I try to run the script as Administrator I'm able to connect though. 

I've tried re-installing python and ibm_db. I've also tried installing python for all users or just for my user, but the issue remains.

**Comment by SabaKauser** [comment] 2018-01-09 04:20
Hello,

Would it be possible for you to provide me with db2 and cli traces for the problem.
You can collect traces as:
cd <clidriver install path>(If you are using the driver that is automatically installed with ibm_db setup, it would be located under site-packages and db2trc exe is under clidriver/adm.

db2trc on -f trc.dmp
<run your application>
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -cli trc.dmp trc.cli

and send me trc.flw, trc.fmt and trc.cli files.

Thanks!

**Comment by slavchomitov** [comment] 2018-01-09 11:12
Hi,

First to mention that I had to run the above commands as Admin, because I was not allowed as user. 
I'm attaching the results from the connection attempt as admin and as user. 
[ibm_db issue.zip](https://github.com/ibmdb/python-ibmdb/files/1614864/ibm_db.issue.zip)

Please let me know, if you need further information from me.

**Comment by SabaKauser** [comment] 2018-01-09 13:50
ibm_db issue.zip trace files does not show up any processing at db2 client level and hence the reason you do not see any error returned from ibm_db.conn_error and ibm_db. conn_errormsg .
 I am assuming the error has something to do with privilege of the user.  Do you have a debuggable version of python installed? would it be possible for you to attach to debugger and put breakpoint in ibm_db_connect API ?

**Comment by slavchomitov** [comment] 2018-01-09 15:14
Here is the debugging result from user:
```
C:\Users\IBM_ADMIN\Documents\Python>python -m pdb "test DB2 connection.py"
> c:\users\ibm_admin\documents\python\test db2 connection.py(3)<module>()
-> import ibm_db
(Pdb) continue
Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\pdb.py", line 1548, in _runscript
    self.run(statement)
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\users\ibm_admin\documents\python\test db2 connection.py", line 3, in <module>
    import ibm_db
SystemError: <built-in function connect> returned NULL without setting an error
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> c:\users\ibm_admin\documents\python\test db2 connection.py(3)<module>()
-> import ibm_db
(Pdb)
```
and here is the debug when the script is run by Admin:
```
C:\Users\IBM_ADMIN\Documents\Python>python -m pdb "test DB2 connection.py"
> c:\users\ibm_admin\documents\python\test db2 connection.py(3)<module>()
-> import ibm_db
(Pdb) cont
Connection to DB successful
The program finished and will be restarted
> c:\users\ibm_admin\documents\python\test db2 connection.py(3)<module>()
-> import ibm_db
```

**Comment by SabaKauser** [comment] 2018-01-10 03:16
ok. As I can see, this is error from python module.  import ibm_db is failing and not the ibm_db.connect() API. In this case, this query should be posted in python forum.

**Comment by slavchomitov** [comment] 2018-01-10 07:49
Hi Saba,

All other imports work fine for me. Only this one is failing. Also it used to work, but then stopped. We've tested with couple of colleagues and in some machines it works fine and in some it doesn't. If only the ibm_db cannot be imported, isn't that an issue with this particular library?

**Comment by SabaKauser** [comment] 2018-01-10 13:33
Hello Slavcho,

sql30082N error, reason code 15 states "security processing failed at server" and as per error response, it states this:
_User response:

Ensure that the proper userid and/or password is supplied.

The userid may be disabled, the userid may be restricted to accessing
specific workstations, or the userid may be restricted to certain hours
of operation._

This is just one of the possible reasons and I thought you might check if this helps you.

As per our ST chat, using 'cont' is able to hit the control to ibm_db. but the control should have reached python driver seamlessly without any prompt. 
I will see if I can post your stacks and scenario in python forum to get some pointers.

NOTE:running through pdb with 'cont' produces this result as per chat:

(Pdb) cont
Post mortem debugger finished. The test DB2 connection.py will be restarted
> c:\users\ibm_admin\documents\python\test db2 connection.py(2)<module>()
-> import ibm_db
(Pdb) cont
Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\pdb.py", line 1548, in _runscript
    self.run(statement)
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\users\ibm_admin\documents\python\test db2 connection.py", line 2, in <module>
    import ibm_db
 SQLCODE=-30082][CLI Driver] SQL30082N  Security processing failed with reason "15" ("PROCESSING FAILURE").  SQLSTATE=08001
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> c:\users\ibm_admin\documents\python\test db2 connection.py(2)<module>()
-> import ibm_db
(Pdb) cont
Post mortem debugger finished. The test DB2 connection.py will be restarted
> c:\users\ibm_admin\documents\python\test db2 connection.py(2)<module>()
-> import ibm_db
(Pdb) cont
Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\pdb.py", line 1548, in _runscript
    self.run(statement)
  File "C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python36-32\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\users\ibm_admin\documents\python\test db2 connection.py", line 2, in <module>
    import ibm_db
 SQLCODE=-30082][CLI Driver] SQL30082N  Security processing failed with reason "15" ("PROCESSING FAILURE").  SQLSTATE=08001
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> c:\users\ibm_admin\documents\python\test db2 connection.py(2)<module>()
-> import ibm_db
(Pdb)

**Comment by SabaKauser** [comment] 2018-01-10 13:57
I have raised an issue in https://bugs.python.org/issue32527

**Comment by SabaKauser** [comment] 2018-02-22 08:17
Hello Slavcho,
Is the problem solved with the patch?

-Saba

**Comment by slavchomitov** [comment] 2018-02-22 14:18
Hi Saba,
 
I had to migrate to Win 10 due to other reasons and I don't have the problem with Win 10. I'll probably ask one of my colleagues who has the problem to test.
Kind Regards 
                                                                                                                                                                                        Slavcho Mitov                         Bulgaria                                                                                                                                Managed Network Support Services Specialist                                                                                 Intelligent Networking Support                                                                                  e-mail:                        slavcho.mitov@bg.ibm.com                                                                                                                                                                                                                                                                            
 
 
 
----- Original message -----From: Saba Kauser <notifications@github.com>To: ibmdb/python-ibmdb <python-ibmdb@noreply.github.com>Cc: slavchomitov <slavcho.mitov@bg.ibm.com>, Author <author@noreply.github.com>Subject: Re: [ibmdb/python-ibmdb] Cannot connect to remote DB with regular user - SystemError: <built-in function connect> returned NULL without setting an error (#294)Date: Thu, Feb 22, 2018 10:17 AM 
Hello Slavcho,Is the problem solved with the patch?
-Saba
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

 
This email is intended solely for the addressee(s) and may contain confidential and/or privileged information. If you are not the intended recipient, you are not authorized to read, print, save, process or disclose this message. If you have received this email in error, please notify the sender immediately, delete this email, its attachments and copies and do not copy it or disclose its contents. Thank you!

Освен ако не е предвидено друго по-горе: / Unless otherwise stated above:
“Ай Би Ем България” ЕООД 
ЕИК 040698335
с. рег. по ф.д. 28237/1992 на СГС
IBAN BG17RZBB91551060040210 (SWIFT: RZBBBGSF), Райфайзенбанк

**Comment by SabaKauser** [comment] 2018-02-22 15:15
Thank you!

**Comment by SabaKauser** [comment] 2018-05-08 09:07
closing as problem is not reproducible.

**Closed by SabaKauser** 2018-05-08 09:07 UTC

**Comment by ammarlam10** [comment] 2019-07-15 07:35
Hi Saba,
Im using windows 10 and Ive come across the same problem. Im able to connect to the database using a different machine but when I run the same script to connect to the database on the current machine it throws 

```
<built-in function connect> returned NULL without setting an error` 
```

**Comment by ksaket1998** [comment] 2024-07-01 08:42
Hi @SabaKauser, I made a script to connect to DB2 using ibm_db python module. It works fine when ran through script but when I convert it to exe using pyinstaller command I get error as `<built-in function connect> returned NULL without setting an error`. When I run the command for next time the error message comes as `[IBM][CLI Driver] SQL10007N Message "0" could not be retrieved. Reason code: "6". SQLCODE=-1042`
Can you pls help on this.
I'm using windows 10 64 bit with the ibm_db module 3.2.3 for python

**Comment by imavo** [comment] 2024-07-05 14:09
@ksaket1998 as this ticket is CLOSED, and because it relates to Windows-7 and this ticket  does not involve pyinstaller, you should create a NEW ticket here, and carefully and fully describe your workstation, exactly what IBM components are installed on your workstation, show your PATH value in full, and show the `pip list` output, and the `db2level` for your db2cli etc,  and show your pyinstaller command-line etc.  Most likely your specific workstation has a configuration that is causing this symptom, and unless you have the ability to fully describe your workstation components, it is unlikely that people can help you.

**Comment by bimalkjha** [comment] 2024-07-05 15:17
@ksaket1998 Please follow [this comment](https://github.com/ibmdb/python-ibmdb/issues/704#issuecomment-2202705953). Thanks.
