### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by gabrielmonteiro0** [ibmdb/python-ibmdb#817] opened 2022-12-15 13:10 UTC
I'm getting this error when I try to use python ibm-db

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libdb2.dylib                  	       0x1367ee0d0 sqloGetServByName + 224
1   libdb2.dylib                  	       0x136ab0ad8 sqljrInternalConnect(db2UCconHandle*, bool*, int*, bool) + 4088

DYLD_LIBRARY_PATH/LD_LIBRARY_PATH =/Users/gabrieldmonteiro/PycharmProjects/project/venv/lib/python3.9/site-packages/clidriver/lib

MacOS: Ventura 13.1

[Error log with details](https://pastebin.com/m38e1d4C)

How can I fix that error?

**Comment by bimalkjha** [comment] 2022-12-15 17:42
@gabrielmonteiro0 Looking on the stack trace, it seems crash is happening inside sqloGetServByName() function of IBM ODBC and CLI Driver. Do you have IBM Support contract for Db2? If yes, you can open an IBM Support ticket for IBM ODBC and CLI Driver. ibm_db uses this driver internally for connectivity.
If you are able to reproduce the problem using a test program, then I would suggest to collect db2trace using below commands:
```
export PATH=/Users/gabrieldmonteiro/PycharmProjects/project/venv/lib/python3.9/site-packages/clidriver/lib:$PATH
db2trc on -f 1.trc
python test.py
db2trc off
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
```
zip all the generated 1.* files and share here for investigation.
We can not download Error log with details shared on `pastebin.com` as this site is blocked by our company due to content filtering. You can attached those files here on github.

Most probably, this issue happens due to use of hostname in the connection string. It looks, this function is unable to resolve the hostname to IP Address. So, try your test program by replacing the hostname with IP Address and update here about the result. Thanks.

**Comment by bimalkjha** [comment] 2022-12-27 06:21
Closing the issue as no update received since 2 weeks. Please share the requested info here if issue still exists. Thanks.

**Closed** 2022-12-27 06:20 UTC
