### ISSUE TITLE
ImportError: DLL load failed while importing ibm_db: The specified module could not be found

### ISSUE THREAD

**Issue by LokeshViswa** [ibmdb/python-ibmdb#871] opened 2023-07-19 13:08 UTC
Hi,
I'm using
Python version: 3.11.0
Ibm_db-3.1.4

I am getting error like ImportError: DLL load failed while importing ibm_db: The specified module could not be found

I installed ibm_db package

Please suggest any solution As soon as possible

It's little bit urgent

**Comment by bimalkjha** [comment] 2023-07-19 13:32
You are getting this message on Windows or Linux? What is the exact error message and how to reproduce? Can you share any screenshot of error? Please provide answer of all questions requested in new issue template. Skipping that is not going to help. Thanks.

**Comment by bimalkjha** [comment] 2023-07-25 06:27
Duplicate of #872.

**Closed by bimalkjha** 2023-07-25 06:27 UTC
