### ISSUE TITLE
Unable to install ibm_db

### ISSUE THREAD

**Issue by rachelshirin007** [ibmdb/python-ibmdb#911] opened 2024-02-09 18:40 UTC
HI! Im unable to install ibm_db

- Operating System Name: Windows 11 64 bit
- db2level output from clidriver if in use: no answer
- Target Db2 Server Version: DB2 on cloud
- Python Version: Python 3.12.1
- ibm_db version: not installed yet

I don't have DB2 on my system. I plan to connect to DB2 on cloud.

- Value of below environment variables if set:
  IBM_DB_HOME: C:\Users\kotav\Downloads\v11.5.4_ntx64_odbc_cli\clidriver\bin
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: C:\Users\kotav\Downloads\v11.5.4_ntx64_odbc_cli\clidriver\lib

I have downloaded the EN driver from [here](https://www.ibm.com/support/fixcentral/swg/downloadFixes?parent=ibm%7EInformation%20Management&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.5.*&platform=All&function=fixId&fixids=DSClients-ntx64-dsdriver-11.5.9000.352-FP000&includeRequisites=1&includeSupersedes=0&downloadMethod=http)

I have installed by following [this page](https://www.ibm.com/support/pages/db2-odbc-cli-driver-download-and-installation-information#%5B%3Ch2%3E%5DDownload%5B%3C%2Fh2%3E%5D)
i ran command prompt as admin and 
specifically typed command:
cd <uncompressed driver folder>/bin
db2cli install -setup

User and System env variables:
IBM_DB_HOME - C:\Users\kotav\Downloads\v11.5.4_ntx64_odbc_cli\clidriver\
IBM_DB_INSTALLER_URL - C:\Users\kotav\Downloads\v11.5.4_ntx64_odbc_cli\clidriver\
LIB - C:\Users\kotav\Downloads\v11.5.4_ntx64_odbc_cli\clidriver\lib

After downloading the driver i got this DB2LOG file:
[dsdriver_log-Fri Feb 09 12_52_32 2024.log](https://github.com/ibmdb/python-ibmdb/files/14225307/dsdriver_log-Fri.Feb.09.12_52_32.2024.log)

Output:

```
C:\Users\kotav\OneDrive\Documents\Connecting-DB2-Flask>pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.2.1.tar.gz (210 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: ibm_db
  Building wheel for ibm_db (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ibm_db (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [201 lines of output]
      <string>:65: SyntaxWarning: invalid escape sequence '\d'
      <string>:435: UserWarning: Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the ibm_db module install

      Detected 64-bit Python
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      copying ibm_db_dbi.py -> build\lib.win-amd64-cpython-312
      copying testfunctions.py -> build\lib.win-amd64-cpython-312
      copying ibmdb_tests.py -> build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\certs
      copying certs\__init__.py -> build\lib.win-amd64-cpython-312\certs
      creating build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_000_PrepareDb.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_001_ConnDb.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_002_ConnDbUncatalogedConn.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_003_NumAffectedRows.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_004_ConnWrongUserPwd.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_005_ConnBadUserBadPwd.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_006_ConnPassingOpts.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_007_pConnPassingOpts.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_008_ColumnInfo.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_010_UpdateRowCount.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_011_DeleteRowCount.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_012_KeysetDrivenCursorSelect01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_013_KeysetDrivenCursorSelect02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_014_KeysetDrivenCursorNegativeRow.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_015_InsertDeleteRowCount_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_016_InsertDeleteRowCount_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_017_selectRowcountPrefetchSTMTOpt.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_018_selectRowcountPrefetchSetOpt.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_019_selectRowcountPrefetchPrepOpt.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_020_RollbackDelete.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_021_CommitDelete.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_022_RollbackInsert.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_023_ColumnPrivileges.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_024_ForeignKeys.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_025_PrimaryKeys.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_030_Result.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_031_ResultIndexPosition.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_032_ResultIndexName.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_033_ResultOutSequenceColumn.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_034_FetchAssoc.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_035_FetchRow_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_036_FetchRow_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_037_FetchRowIndexPos.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_038_FetchRowIndexPosNested_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_039_FetchRowIndexPosNested_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_03a_ResultNonExistCol.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_040_FetchTuple.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_041_FetchTupleMany_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_042_FetchTupleMany_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_043_FetchTupleMany_03.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_044_FetchTupleMany_04.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_045_FetchTupleBinaryData_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_046_FetchTupleMany_05.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_047_FetchTupleMany_06.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_048_FetchTupleBinaryData_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_049_InsertNoneParam.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_050_AutocommitStatus.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_051_SetAutocommit_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_052_SetAutocommit_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_053_AttrThruConn.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_054_CursorType.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_060_Tables_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_061_Tables_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_062_Tables_03.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_063_Tables_04.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_064_Tables_05.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_065_FilterTableName.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_066_TableObjects.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_070_Close.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_071_CloseSuccess.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_080_ConnWrongDbAlias.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_081_ConnWrongUser.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_082_ConnWrongPwd.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_090_ConnmsgWrongDbAlias.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_091_ConnmsgWrongUser.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_092_ConnmsgWrongPwd.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_100_SelectDeleteInsertFieldCount.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_101_InsertDeleteFieldCount.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_102_NumFieldsSelect_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_103_NumFieldsSelect_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_110_FieldNum.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_111_FieldNumAddCol.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_112_FieldNumDiffCaseColNames.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_113_DateTest.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_114_NumericTest_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_115_NumericTest_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_116_ConnActive.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_120_FieldName.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_121_FieldNameAddCol.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_122_FieldNameDiffCaseColNames.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_123_FieldNamePos_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_124_FieldNamePos_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_125_FieldNamePos_03.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_130_PrepExecuteSelectStmt.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_131_PrepareExecuteSelectStatementParams.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_132_ExecuteStatementArrayMultipleParams.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_133_ExecuteLongInputParams.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_140_BindParamSelectStmt.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_141_BindParamSelectStmtMultipleParams_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_142_BindParamSelectStmtMultipleParams_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_143_BindParamInsertStmtNoneParam.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_144_BindParamInsertStmtPARAM_FILE.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_145_BindRetrieveNoneEmptyString.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_146a_CallSPINAndOUT_Blob_Param.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_146_CallSPINAndOUTParams.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_147_PrepareWithWrongType.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_148_CallSPDiffBindPattern_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_150_FetchAssocSelect_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_151_FetchAssocSelect_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_152_FetchAssocSelect_03.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_153_FetchAssocSelect_04.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_154_AllFetches.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_155_FetchAssocSelect_05.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_156_FetchAssocNestedSelects_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_157a_FetchAssocWithoutScrollableCursorErr.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_157b_FetchAssocScrollableCursor_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_157_FetchAssocScrollableCursor_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_158_FetchAssocNestedSelects_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_159a_FetchAssocSeveralRows_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_159_FetchAssocSeveralRows_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_160_FetchBoth.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_161_FetchBothNestedSelects_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_162_FetchBothNestedSelects_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_180_StmtErrMsg.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_190_ColumnsTable_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_191_ColumnsTable_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_195_InsertRetrieveXMLData_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_196_InsertRetrieveXMLData_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_197_StatisticsIndexes.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_200_MultipleRsltsetsUniformColDefs.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_201_MultipleRsltsetsDiffColDefs.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_210_FieldDisplaySize_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_211_FieldDisplaySize_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_212_FieldDisplaySize_03.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_213_FieldDisplaySize_04.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_220_PersistentConn.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_221_100PersistentConns.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_230_FieldTypePos.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_231_FieldTypeName.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_232_FieldTypePosName.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_240_FieldWidthPosName_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_241_FieldWidthPosName_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_250_FreeResult_01.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_251_FreeResult_02.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_260_FetchTupleMany_07.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_261_FetchObjectAccess.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_264_InsertRetrieveBIGINTTypeColumn.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_265_NoAffectedRows.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_300_ServerInfo.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_310_ClientInfo.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_311_InsertSelectDeleteNumLiterals.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_52949_TestSPIntVarcharXml.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_6528_ScopingProblemBindParam.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_6561_InsertNULLValues.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_6755_ExtraNULLChar_ResultCLOBCol.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_6792_FieldTypeRetStrDatetimeTimestamp.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_alltypes.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_alltypesarray.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_booleanInsertSelect.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_bool_callproc.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_checkBooleanType.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_createdbNX.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_createDropDB.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_currentschema.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_cursortype.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_decfloat.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_decimal.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_err_executemany.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_execute_many.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_InsertRetrieveDateTimeTypeColumn.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_recreateDB.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_setgetOption.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_SPInOutBlob.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_SPInOutZero.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_trusted_context_connect.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_trusted_context_pconnect.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_unicodeTable.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\test_warn.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      copying ibm_db_tests\__init__.py -> build\lib.win-amd64-cpython-312\ibm_db_tests
      running egg_info
      writing ibm_db.egg-info\PKG-INFO
      writing dependency_links to ibm_db.egg-info\dependency_links.txt
      writing top-level names to ibm_db.egg-info\top_level.txt
      reading manifest file 'ibm_db.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.png' under directory 'ibm_db_tests'
      warning: no files found matching '*.jpg' under directory 'ibm_db_tests'
      warning: no files found matching '*' under directory 'clidriver'
      warning: no files found matching '*' under directory 'ibm_db_dlls'
      warning: no previously-included files found matching 'config.py'
      adding license file 'LICENSE'
      writing manifest file 'ibm_db.egg-info\SOURCES.txt'
      copying certs\ibm_certs.pem -> build\lib.win-amd64-cpython-312\certs
      running build_ext
      building 'ibm_db' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ibm_db
Failed to build ibm_db
ERROR: Could not build wheels for ibm_db, which is required to install pyproject.toml-based projects
```

**Comment by bchoudhary6415** [comment] 2024-02-10 04:38
Hi @rachelshirin007 
Please use python 3.11.x version, currently python 3.12.x is not in support for python ibm_db.
Also download clidriver from - https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/v11.5.9/
And Also
Try to set environmental variables - IBM_DB_HOME and LIB shown here - https://github.com/ibmdb/python-ibmdb#envvar
 Please follow the link to install ibm_db on Windows - https://github.com/ibmdb/python-ibmdb#windows

Thanks

**Comment by bimalkjha** [comment] 2024-02-10 12:18
It is duplicate of existing issue #890 . Hence closing it. Thanks.

**Closed by bimalkjha** 2024-02-10 12:18 UTC
