### ISSUE TITLE
Intermittent Error SQL10013N The specified library "" could not be loaded

### ISSUE THREAD

**Issue by singhshraddha** [ibmdb/python-ibmdb#631] opened 2021-06-02 14:35 UTC
Intermittently failing with error SQL10013N The specified library "" could not be loaded. SQLSTATE=42724 SQLCODE=-10013

**Package versions**
ibm_db v3.0.4
ibm_db_sa v0.3.4 (cannot update to latest because of https://github.com/ibmdb/python-ibmdbsa/issues/96)

**Stack Trace**
db_engine is a sqlalchemy engine created using as database connection string (with host, user, password and other information) and create_engine method in sqlalchemy

```
with db_engine.connect() as con:
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2206, in connect
return self._connection_cls(self, **kwargs)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
else engine.raw_connection()
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2306, in raw_connection
self.pool.unique_connection, _connection
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
e, dialect, self
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
util.raise_from_cause(sqlalchemy_exception, exc_info)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
raise value.with_traceback(tb)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
return fn()
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
return _ConnectionFairy._checkout(self)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
fairy = _ConnectionRecord.checkout(pool)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
rec = pool._do_get()
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
self._dec_overflow()
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
raise value
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
return self._create_connection()
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
return _ConnectionRecord(self)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
self.__connect(first_connect_check=True)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
connection = pool._invoke_creator(self)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
return dialect.connect(*cargs, **cparams)
File "/var/www/python_venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 481, in connect
return self.dbapi.connect(*cargs, **cparams)
File "/var/www/python_venv/lib/python3.7/site-packages/ibm_db_dbi.py", line 631, in connect
raise _get_exception(inst)
sqlalchemy.exc.ProgrammingError: (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: [IBM][CLI Driver] SQL10013N The specified library "" could not be loaded. SQLSTATE=42724 SQLCODE=-10013
(Background on this error at: http://sqlalche.me/e/f405)
```

**Operating System Info**
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

**Connection type**
SSL

Let me know if any other information is required for debugging

**Comment by amukherjee28** [comment] 2021-06-02 16:15
Hi,

Can you provide the details of the platform on which this error is seen (windows, linux or mac).

Also are you using normal connection or SSL connection ?

Thanks

**Comment by singhshraddha** [comment] 2021-06-02 17:32
Updated the issue with detailed comments. It's a linux platform (RHEL) and we're using a SSL connection

**Comment by imavo** [comment] 2021-06-02 19:13
Some detailed problem determination needed at your site...

Are you connecting to local or remote databases?

If the databases are remote, are they also on Db2-LUW, or are they on Z/OS?

If the databases are remote on Z/OS, are you using certificate authentication?

Are you using the clidriver or the Db2 client with python ibm_db ?

If using the Db2-client, which GSKit version are you using?

On the RHEL host, is more than one Db2 product installed (e.g, both clidriver and a Db2 product)?

On the RHEL host, is more than one GSKit installed, or more than one version of it?

If the symptom is intermittent, can it be recreated on demand?

Is there some pattern when the symptom appears? (for example, only when specific jobs run, or specific scheduled jobs etc, or only when a certificate is revoked/renewed etc., or only when specific userids run the jobs etc. 


What details are in the Db2-client (or clidriver) diagnostics , or the linux messages log
when the symptom happens.

**Comment by singhshraddha** [comment] 2021-06-02 19:52
We are using database as service hosted by IBM Cloud. The issue shows up across multiple python projects where we are interfacing with a remote db2 using sqlalchemy engine, and can be easily recreated in our regressions (where we perform api server calls). The platform where the error occurs is RHEL, I am not sure about the platform DB2 is hosted on. 

I'll get back to you with further details on this as I get them myself

**Comment by falkzoll** [comment] 2021-06-09 12:21
We also see this happening from time to time in a linux/amd64 based environment. It is highly intermittent and occurs a few times in a few thousand executions. The code is contained in a docker image and the image is always the same. But some of the executions show this exception:
```
stderr: [] - ERROR - Exception('[IBM][CLI Driver] SQL10013N  The specified library \"\" could not be loaded.  SQLSTATE=42724 SQLCODE=-10013')
```
While the remaining executions work completely fine. As the image is always the same, the execution environment is always the same. So it might be a timing/race issue that sometimes leads to this exception.

**Comment by imavo** [comment] 2021-06-10 13:05
@falkzoll is there any additional info from clidriver diagnostics or from system message log in the container?  Does the container also connect to Db2-on-cloud? ,  also which image is the container based on (which distro etc) ? Are you encrypting the connection with SSL also?

**Comment by amukherjee28** [comment] 2021-06-10 15:36
Hi @falkzoll @singhshraddha 

I was not able to reproduce the issue at all. Tried running against DB2 on Cloud multiple times but never faced the issue.

My request in case you come across the issue, please check if you can capture the trace.
I understand that since the issue is intermittent and there is no consistency, it is very difficult to capture the trace, but you find any particular patter, then do reproduce and capture traces.

@singhshraddha since you mentioned that the issue is easily recreated in your regression environment, would it be possible for you to capture the traces?

Thanks

**Comment by amukherjee28** [comment] 2021-06-23 09:30
Hi @falkzoll @singhshraddha 

Did you have this issue occurring again in your environment.

In case the issue resurfaces will it be possible to capture traces in that case ?

**Comment by amukherjee28** [comment] 2021-08-10 18:58
Hi @falkzoll @singhshraddha can this closed for now ?

**Comment by amukherjee28** [comment] 2021-09-21 07:58
closing the issue for now. In case you have the error please open a new issue.

**Closed by amukherjee28** 2021-09-21 07:58 UTC
